### ISSUE TITLE
Guard attacks player, when not in blacklist

### ISSUE THREAD

**Issue by Coffeehedake** [CitizensDev/Citizens#100]
When a guard is set to aggro, using the /npc move command, he immediately attacks the player who was using the command after the move takes place. The attack ignores god mode. Moving out of the guard's radius causes the attack to cease, but there are 2 bugs here.

Guards should not ignore god mode, and for some reason are attacking non-blacklisted players.

Build 145

Flags for this Guard are set with only "mob" flags. There is nothing populated in any of the other flag types (Players or Groups)

**Comment by defaultsucks** [comment]
Here's a workaround: stop your server and go to npc-profiles.yml then look for the guard and check the flags. If there are any flags mentioning a player, remove it by hand and start your server again.
