### ISSUE TITLE
Equipment deleted and no LookClose?

### ISSUE THREAD

**Issue by gabessdsp** [CitizensDev/Citizens#1006]
To clarify this is an issue with the latest dev build. When I startup my server I am told that the variable lookclose does not exit, in-game I can still assign the lookclose to an npc but then if I startup the server I get the same error again, also it doesn't work in-game which is expected. After I equipped some armor and a sword to my npc's I also got an error on next startup and all of the equipment was deleted:

4/27/2012 6:27:51 AM [SEVERE] java.lang.NullPointerException
4/27/2012 6:27:51 AM [SEVERE]   at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:43)
4/27/2012 6:27:51 AM [SEVERE]   at net.citizensnpcs.api.util.ItemStorage.loadItemStack(ItemStorage.java:13)
4/27/2012 6:27:51 AM [SEVERE]   at net.citizensnpcs.api.trait.trait.Equipment.load(Equipment.java:53)
4/27/2012 6:27:51 AM [SEVERE]   at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
4/27/2012 6:27:51 AM [SEVERE]   at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:291)
4/27/2012 6:27:51 AM [SEVERE]   at net.citizensnpcs.Citizens.access$000(Citizens.java:52)
4/27/2012 6:27:51 AM [SEVERE]   at net.citizensnpcs.Citizens$1.run(Citizens.java:168)
4/27/2012 6:27:51 AM [SEVERE]   at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
4/27/2012 6:27:51 AM [SEVERE]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:517)
4/27/2012 6:27:51 AM [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
4/27/2012 6:27:51 AM [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by fullwall** [comment]
Fixed.
