### ISSUE TITLE
NPC's gone on restart.

### ISSUE THREAD

**Issue by blackwith123** [CitizensDev/Citizens#1015]
hello,
i know this is a known issue, i haven't found any solvings yet so i might ask it again.
2 days ago my citizens was working correctly and i made up a whole training for my players with NPC giving hints and tips.
but when i finished it and EDIT: 'Restart (stop and start)' my server for some rank update and some plugins that became outdated all the NPC's where gone. I don't know where the problem is, and how to fix it..
So i could use some help.
Thanks already
kind regards,
Xx_lwd_xX

**Comment by fzman** [comment]
Citizens doesnt support reloads, use the npc save feature before reloading. Stopping the server also automatically saves.

**Comment by nrdennis** [comment]
will citizens support reloads in the future? cause im having the same problem

**Comment by cheeselife** [comment]
I had this problem too, what i did i disabled   use-economy: true  to false in the citizens.yml. Hope it helps.

**Comment by fredghostkyle** [comment]
same, do /citizens save BEFORE you reload and restart
 and the  use-economy: true to false in the citizens.yml, will probably not help, that is with /eco or/and /bal. (your economy)

**Comment by blackwith123** [comment]
when i actually changed the economy from true to false the problem did never occur again, tho this is very annoying if i want to create shops from citizens. Hoping that there will be an update that fixes this problems.
thanks for the helping comments.

Topic closed.

**Comment by nrdennis** [comment]
dude! are you deaf?
I just said use vault so that you can have economy = true
http://dev.bukkit.org/server-mods/vault/

**Comment by fredghostkyle** [comment]
@iforgot290 AND @blackwith123 

Ok, iforgt i can see that,
and blackwith WTF, get vault (i think 99.9% or plugins use it, well it seams) and make it true, you wont to have a shop right? so get it.
