### ISSUE TITLE
Npcs move while on half blocks

### ISSUE THREAD

**Issue by zackb1079** [CitizensDev/Citizens#103]
I am running Citizens 1.09d  and while Npcs are on a half slab (such as a wooden slab) they can be pushed around by the player, but when teleported back to a regular block they work perfectly fine. This was tested on multiple Npcs.

**Comment by defaultsucks** [comment]
It'd be great if you could verify this on the newest builds. Here's the link :

http://jenkins.citizensnpcs.net:81/job/Citizens/

Don't forget to back up your citizens.jar and citizens folder.

**Comment by zackb1079** [comment]
They were still moveable with the latest build from that link.
