### ISSUE TITLE
Citizens class .jar file

### ISSUE THREAD

**Issue by Jarsen-** [CitizensDev/Citizens#104]
I'm not used to compile stuff, but I would like to test the newest release of Citizens. There is a precompiled .jar of the main plugin, but I can't find any precompile .jar of any of the classes you can assign to an NPC. Is it possible that you would compile them, or am I doomed to wait until you release the final version?

**Comment by defaultsucks** [comment]
Here's a link with all the newest builds:

http://jenkins.citizensnpcs.net:81/job/Citizens/

**Comment by Jarsen-** [comment]
Thank you
