### ISSUE TITLE
Suggestion for Quests - Similar to delivery type

### ISSUE THREAD

**Issue by RincewindSCC** [CitizensDev/Citizens#105]
Hi,

Would it be possible for a new quest type where you just walk to a NPC and the quest will end there? Currently in deliver quests you walk to the NPC, give them their item and walk back to the original ones. A lot of MMO's have a type of quest similar to this.

**Comment by defaultsucks** [comment]
I agree. This should definitely exist in citizens.

**Comment by kris76** [comment]
And by extend make possible that the reward is given by another pnj than the one who gave the quest ?

**Comment by fullwall** [comment]
Should be possible now.
