### ISSUE TITLE
Delivery Quest Bug

### ISSUE THREAD

**Issue by RincewindSCC** [CitizensDev/Citizens#106]
On #148-#150 currently when you walk to the destination NPC it will say go back to the original NPC but doesn't take the items from the player.

The quest for reference below.

delivery:
    texts:
        description: A Delivery Quest!
        completion: <g> DELIVERY QUEST DONE.  
        acceptance: <g> DELIVERY ACCEPTED.
    repeats: 0
    objectives:
        '0':
            '0':
                type: delivery
                npcdestination: 1
                materialid: 4
                amount: 4
                message: DELIVERY DONE. GET BACK HERE.

**Comment by defaultsucks** [comment]
This has been fixed in the latest dev builds somewhat. The problem could be in the amount. Try setting it to one. I didn't have any luck in having more than one item delivered as well.
