### ISSUE TITLE
NPC Trader isn't showing the buy menu.

### ISSUE THREAD

**Issue by BodyshotzVG** [CitizensDev/Citizens#108]
Sorry, but I've tried like ALL the permission nodes I could find. But, none of them allow my people to access the Trader's Buy/Sell Menu. Please help, as I would really like to stop hearing "CAN I SELL TO THE NPCS NOW?". Thanks in return.

**Comment by defaultsucks** [comment]
Try the permission node citizens.trader.use.trade: true . If you're using permissions instead of permissionsbukkit, just drop the : true.
