### ISSUE TITLE
Guards will not attack

### ISSUE THREAD

**Issue by joker11940** [CitizensDev/Citizens#1098]
followed this to the letter, but  they just stand there

http://www.youtube.com/watch?v=iOyQIy9q-5E&feature=related

my cmds were

/npc create Bill

/toggle guard

/guard bouncer

/guard aggro

/guard radius 50

/guard addflag 1 -m creeper

**Comment by jwebbdev** [comment]
3 things.  Try:
/guard addflag 1 creeper -m

If you do /guard help you'll see that's the format.  Maybe both work, but try the documented way.

Second thing, I've noticed that my guards only tend to attack stuff when it's aggro'd onto something, which doesn't happen if I'm in creative.  Go punch a zombie or spider and drag them back, if the guard still doesn't attack...

Third thing!  If your guards aren't attacking (especially if they're staring at the ground) they might be aggro'd onto something in a cavern underground that they can't get to.  I've thought about adding a line of sight check in my fork, but don't hold your breath, I suggest using worldedit to fill in the radius of your guards underground, I'd also reduce the radius to something like 10 while testing aggro (so you know he's not staring at a spider in a cavern 4 chunks away), just drag a zombie really close and make sure it's aggro'd onto you.

**Comment by joker11940** [comment]
:( things

Don't know if this helps but helps the npc-profiles.yml file

'1':
  guard:
    flags:
      creeper:
        priority: '1'
        safe: 'false'
        type: MOB
    radius: '50.0'
    aggressive: 'true'
    toggle: 'true'
    type: BOUNCER
  basic:
    talk: 'true'
    inventory: AIR*36,
    name: Bill
    color: f
    owner: dowen01
    location: world,-149.7106479731022,12.0,61.67586502618393,-22.842852,9.899975
    balance: '0.0'
    talk-when-close: 'false'
    items: 0:0,0:0,0:0,0:0,0:0,
    look-when-close: 'true'

**Comment by jwebbdev** [comment]
Looks right, but doesn't really tell me if you tried (or the results of) 2 and 3.

If you want you can email me your server info and I can check them out and see what's up.

**Comment by joker11940** [comment]
Sorry for the delay in the response I wanted to test everything to be sure
:( still not working

I you know I did item 1

2 turned off creative mode and even had other players around 

created a blank flat world so there was no way of there being a mob underground same issue :(

a note that i don't know if it will help but when you right click on them NPC they look at you, but don't follow (looking) when you move

What "server info" did you want?

**Comment by jwebbdev** [comment]
Make sure you have the latest version from
http://ci.citizensnpcs.net/job/Citizens/

If so, just toss me your server ip/port.  You can just email it if you'd
prefer, vapesk at gmail dot com .

On Thu, Jul 26, 2012 at 7:01 AM, dowen01 <
reply@reply.github.com

**Comment by joker11940** [comment]
:D :D :D :D

Got it

It must have been the version 
used  #65   Jul 19, 2012 12:08:30 PM

and it worked first time!!!!

Thanks for your time

**Comment by jwebbdev** [comment]
hah, awesome.  Guess that should have been my first suggestion.

On Thu, Jul 26, 2012 at 10:47 AM, dowen01 <
reply@reply.github.com
