### ISSUE TITLE
Questers repeatable quest issues

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#112]
I'm on dev build #152 and the non repeatable thing has been somewhat patched up. I had my repeats set to 0 the first time, I complete the quest once, go back to the quest giver and he says he has no more quests available. Well if I log out and log back in, he says I can take the quest again. If I set repeats to 2 for example, it just lets me take the quest n times over and over again without any log outs. I do the quest, come back, take my reward and I can do it again (I've tried it more than 5 times and it definitely goes over the set limit).

Also, kind of a weird thing but whenever I type in /quest completed, I shoot out... an arrow. I don't have a bow or any arrows in my inventory. It just shoots out an arrow from my character to where I'm looking if I use that command.

**Comment by fullwall** [comment]
Whoops, forgot to remove that debug arrow code. I will look into the allowing to repeat thing now (probably to do with not updating some values correctly).

**Comment by fullwall** [comment]
Can you try this with the latest build?

**Comment by defaultsucks** [comment]
Yes just a sec.

**Comment by defaultsucks** [comment]
I think I just figured out the problem. The problem still happens except now you have to log out and log back in in either case to repeat it. However, when I just finish the quest and do /quest completed it shows that quest as completed. If I log out and log back in and do the same command, it says I haven't completed any quests. It could be related to either saving that information or reading it from the profiles file.

**Comment by fullwall** [comment]
OK, will look into that tonight.

**Comment by defaultsucks** [comment]
This is fixed in the latest dev builds.
