### ISSUE TITLE
wired wiki, commands, permissions

### ISSUE THREAD

**Issue by DaEgo** [CitizensDev/Citizens#1128]
ok, can somebody post me what do i have to type in to change him to a guard
and what permissions i need ?
/trait guard = you dont have permission to execute that command

wiki need some "simple" example commands :-(

**Comment by jrbudda** [comment]
/trait is a command for citizens 2.0
guard is a type from citizens 1.2

That may be your problem

**Comment by DaEgo** [comment]
lol no i have cit2
do i need a extra permission or another plugin ?

**Comment by DaEgo** [comment]
i download it here
http://ci.citizensnpcs.net/job/Citizens2/
than i try to creat one here :
http://wiki.citizensnpcs.net/Sentry#Creation

**Comment by jrbudda** [comment]
/trait sentry
is the command you need. You should not need permissions to run /trait, i dont think. Check the wiki for the citizens permissions, maybe you need citizens.admin

**Comment by DaEgo** [comment]
i use
http://wiki.citizensnpcs.net/Permissions
citizens.admin
and
http://wiki.citizensnpcs.net/Sentry/Permissions
sentry.*

but Sentry/Permissions site has nothing with "trait" listed
so :
/trait sentry = you dont have permission to execute that command

this is what i do :

/npc create Wache-Schütze
/npc lookclose
/npc equip
...iron armor and bow
/npc equip

npc do not attack mobs, ok cause he dont know that he have to do^
so :
/trait guard = you dont have permission to execute that command
/trait sentry = you dont have permission to execute that command

but: /trait ,say :
Too few arguments
/trait [trait name]

so i have maybe just a "part" of full permissions ?

**Comment by jrbudda** [comment]
try citizens.npc.trait.sentry or citizens.npc.trait.*

**Comment by DaEgo** [comment]
uhm, i removed all permissions and it works now
i dont know what happend ?

**Comment by DaEgo** [comment]
lol im really confused now,
i can use this camands, no problem :

/sentry target add entity:monster
/sentry speed 0.5
/sentry attackrate 0.5
/sentry invincible
/sentry retaliate

but he say "no permissions for that command" to this :
/sentry range 20

**Comment by jrbudda** [comment]
ooh, there is a bug. Fixed in next build. That should be the only stat you cannot change without op privileges.

**Comment by DaEgo** [comment]
/sentry range 20
works now
thx
