### ISSUE TITLE
/sentry info : Critical Hits, double entry ?

### ISSUE THREAD

**Issue by DaEgo** [CitizensDev/Citizens#1135]
i dont change critical, is it double ?
and a missing space in trueRespawn

http://s7.directupload.net/images/120819/s9xu4ohm.png

when i enter /sentry criticals and /sentry info
he show that he change both entrys

**Comment by jrbudda** [comment]
oops!
Fixed.

**Comment by DaEgo** [comment]
confirmed, thx
