### ISSUE TITLE
Sentry just attack all 5 Min 1 mob ?

### ISSUE THREAD

**Issue by DaEgo** [CitizensDev/Citizens#1136]
i placed a sentry and he attack mobs, so it works.
but he just attack 1 mob, kill it, and than "nothing"
he just stay and "wait" until a timer runs out ? or something

there are xx mobs but he ignore them, just kill one and than he waits again...

**Comment by jrbudda** [comment]
If there are no mobs in range, and he does not have a path he will just stand there. Try increasing his range.

**Comment by DaEgo** [comment]
1. mob are in range, fence square of maybe 8x8
2. Bow Guard need a path ? stand still is his job
3. he has more than 8x8 range, thats enough for test

**Comment by DaEgo** [comment]
hmm something has changed, idk what but he attack now until all targets dead.
