### ISSUE TITLE
/citizens save : does not save the location of NPC

### ISSUE THREAD

**Issue by DaEgo** [CitizensDev/Citizens#1137]
when i use /npc tphere
he change location, fine

and i do /citizens save
output say : saved, fine

but after server restart, the npc is back at the location he was before i tp him

**Comment by jrbudda** [comment]
if it is a sentry you must move him using /sentry spawn

Otherwise it should work.

**Comment by DaEgo** [comment]
hmm ok, than add it as a "sugestion" ?
give /cit save the job to check what mods installed
and execute the right command to this plugins ?
just a idea

**Comment by jrbudda** [comment]
No, imagine if a Sentry was chasing after a monster when you called /citizens save.
Wherever he is when you save is where his new spawn point would be. That is why Sentry keeps its own seperate location.

**Comment by DaEgo** [comment]
ok
