### ISSUE TITLE
Download Sentry 0.8.5.zip = 1KB only - ERROR

### ISSUE THREAD

**Issue by DaEgo** [CitizensDev/Citizens#1138]
0.8.5 download is broken
size of file is <1 KB,
and console say : sentry.jar not found

i have a older version 0.7.9.2 and size is 48KB and works

http://wiki.citizensnpcs.net/Sentry
link :
https://github.com/downloads/jrbudda/Sentry/Sentry%200.8.5.zip

**Comment by jrbudda** [comment]
Also oops.
Also fixed.

**Comment by DaEgo** [comment]
thx works

btw, why not download "Sentry0.8.5.1.jar"
zip so a small file ? _g_ ;-)
