### ISSUE TITLE
Delivery quest item amount

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#114]
If you set the amount to anything above 1, the receiver npc just doesn't take the items. The quest progresses, but the items remain in my hand. I've tried using multiple types of items, dirt, food etc. I eat the food in my hand regardless but I have a stack of it and it doesn't take out the set amount of items, just one.

**Comment by fullwall** [comment]
The receiver npc isn't meant to take the items.

**Comment by defaultsucks** [comment]
Then what's the point of a delivery quest? Why not just make it so you have to reach a certain npc to progress in the quest? I'm not trying to put anything down, I'm just saying maybe there should be a few more types of quests just to expand this idea ;P
