### ISSUE TITLE
question : target enity:monster - slime , ghast , magmacube

### ISSUE THREAD

**Issue by DaEgo** [CitizensDev/Citizens#1140]
can u plz add to enity:monster this :
slime , ghast , magmacube

i test and add it manual and this is result :

he shoot slime and ghast when added
he do not shoot magmacube when added

**Comment by jrbudda** [comment]
Those mobs are not MonsterEntities according to Bukkit. So they will not be added.
You need to use magma_cube.
There is a list of vaild entity names on the wiki (but its down right now, or it would be here http://wiki.citizensnpcs.net/Types)
You can see them here tho. http://jd.bukkit.org/apidocs/org/bukkit/entity/EntityType.html

**Comment by jrbudda** [comment]
Also if you post your Sentry issues here https://github.com/jrbudda/Sentry/issues
I will see them faster.

**Comment by DaEgo** [comment]
ah ok thx
yeah i see citizensnpcs.net is complete down since yesterday :-(
