### ISSUE TITLE
Talk on Close

### ISSUE THREAD

**Issue by jeffavery** [CitizensDev/Citizens#1155]
I can't seem to find it anywhere so maybe I'm just not thinking correctly on what I"m looking for. In Citizens 1.2 they could be set to say their message when you got close. Is this possible in 2.0? If this is obvious I totally apologize and just say so I'll keep digging.

Regards,
jeff

**Comment by jrbudda** [comment]
Yes do /npc text to enter the text editor, then type 'close' to turn on talk-close.
You can also edit the saves.yml to set the talk-close range, randomness, and line-of-sight-usage

**Comment by jeffavery** [comment]
Awesome, Thank you! Love this plugin.

jeff
