### ISSUE TITLE
NPC Limit Reached, yet none made.

### ISSUE THREAD

**Issue by cpcheebs** [CitizensDev/Citizens#116]
I'm using superperms, PermissionsBukkit to be exact.  Don't know if that is what is causing it but I have every permissions for Citizens enabled for my admin group.  No, I am not using the "*".

Anyways anytime I try to make an npc with "/npc create", I get an error:  "You have reached the NPC-Creation Limit."  Yet, I have not created an NPC.

Searching through the Bukkit Forum post only yielded in one person with the same problem, to which no one answered.  Someone with a similar problem, who was able to make 10 NPC's had the same error, but the solution to it was to go into the citizens.settings file and change the "npc_max_per_player" value.

This file however, was not generated for me.  In fact the only files I have (with text in them) are citizens.yml and economy.yml.  The other files are mobs, npc-profiles, and quests.yml's, which have nothing in them.

So what's the problem here?  SuperPerms?  Am I missing a file?

I'm using the latest versions of Citizens and the latest version of PermissionsBukkit for 1060 Bukkit.

**Comment by defaultsucks** [comment]
Does the latest version of citizens mean 1.0.9d or the latest dev builds? Also, try looking at these permission nodes right here: http://pastebin.com/ecwiAjXu

I think there's a node to limit the number of npcs that one group can create etc so you may want to look at that and set it up right if it's not already set up correctly. If that doesn't work and you're running 1.0.9d, try getting one of the latest dev builds here: http://jenkins.citizensnpcs.net:81/job/Citizens/

Back up all your citizens files including the citizens.jar and the citizens folder and set up the new dev build. Try recreating the problem with it.

**Comment by cpcheebs** [comment]
Ok adding that permissions worked, thank you very much.  Yes, I am using 1.0.9d.  But where did you get this list of permissions?!  It's different from the permissions that are given on the Citizens Wiki.

**Comment by defaultsucks** [comment]
Well I've come to find out that there are actually a few versions of citizens wiki. This one I found after some googling time. Once 1.1 is released the developers should update the 1.1 wiki they're hosting on their website and all of these should be there I think.
