### ISSUE TITLE
ArrayIndexOutOfBoundsException: 54 for a converted Trader-trash bin

### ISSUE THREAD

**Issue by Scaenicus** [CitizensDev/Citizens#1165]
Yesterday I updated my server (from 1.2.5 to 1.3.2) and with that Citizens from 1 to 2.

After some problems with the converted file (colored names, just had to remove all §*) I stepped into the above mentioned error.

It didn't take me long to realize that my "trash bin npc"...
http://muppet.wikia.com/wiki/Marjory_the_Trash_Heap
...was the reason (it buys everything for one ball of slime).

When I removed the "inv:" of this npc and everything worked fine.
Here is the original converted npc:
http://pastebin.com/0VmR9sBP

If the trash bin is not possible anymore I would vote for a more talkative Exeption in the Server log.

WKR, Philipp

**Comment by DMarby** [comment]
Use the new ticket manager, http://issues.citizensnpcs.com and refer to our new wiki, http://citizensnpcs.com for help.
