### ISSUE TITLE
Name Tags can change the nameplates of NPCs

### ISSUE THREAD

**Issue by nikita-smyrnov** [CitizensDev/Citizens#1173]
http://www.twitch.tv/imboring56/c/4442737

This is a bug report that I wanted to send in concerning how the nameplates of Citizens NPCs (except for the entity/mob type PLAYER) can be changed using name tags. The video link above shows how you can replicate the bug. Note that you can use any NPC with this except for a PLAYER, so an entity such as CHICKEN would work.

This does not affect their ID or stored name in the Citizens database, only their nameplate appearance. However, it is extremely annoying how it changes their name, and it would mislead players if they are searching for a particular NPC name.

**Comment by mcmonkey4eva** [comment]
This used to be a bug in Citizens 2 ( not Citizens 1 ), and has since been fixed.
