### ISSUE TITLE
Player NPCs all Face South

### ISSUE THREAD

**Issue by SequaciousGAMES** [CitizensDev/Citizens#1175]
When I create a player NPC, no matter where I face, or where I move it, the body will be facing the correct way but for some reason the head will always face south.

Citizens Build #1220
Spigot Version 1.8.3-R0.1-SNAPSHOT

**Comment by mcmonkey4eva** [comment]
I think you're thinking of `Citizens2` which is a separate project.
The Citizens2 issue for this is at: https://github.com/CitizensDev/Citizens2/issues/271
