### ISSUE TITLE
Using - adjust skin: causes NPC death to happen twice

### ISSUE THREAD

**Issue by uledrith** [CitizensDev/Citizens#1176]
```
MSLowerCryptBoss:
  type: assignment
  debug: false
  actions:
    on assignment:
    - ^flag global mslowercrypt_npc:<npc>
    - ^flag <npc> spawnpoint:l@-1284.1,49.9,-24.1,survive
    - ^adjust <npc> skin:Giik
    - ^flag <npc> aggro:!
    - ^flag <npc> highestdamage:0
```

If I remove the adjust line, using a simple "on entity death:" and narrate will only show once.  If I add the adjust line, it fires twice.

Also, the Citizens "NPC dies" message fires twice.

**Comment by mcmonkey4eva** [comment]
@Morphan1 ?

**Comment by mcmonkey4eva** [comment]
Also, this was posted in a horrendously wrong location. please repost in Denizen.
(You posted in the Citizens 1.0 section)
