### ISSUE TITLE
Skins and NPCs vanishing

### ISSUE THREAD

**Issue by sjoerdtim** [CitizensDev/Citizens#1179]
Whenever I work with Citizens (and Denizen) it all works perfectly fine, no errors and they function perfectly. But recently the NPCs started disappearing and their skins started unloading randomly.

It's not on server startup or a reload or anything, they just randomly disappear and reappear ~5 minutes later. As for the skins unloading, sometimes the skin does return and then after a few minutes disappears again.

I'm using
Citizens 2.0.14 (alpha 1 for MC 1.8.1)
git-Spigot-13716d9-0899683 (MC: 1.8) (Implementing API version 1.8 R0.1-SNAPSHOT)
denizen-0.9.6-SNAPSHOT

Hope this can be fixed, or you already know a solution! Thanks!

**Comment by mcmonkey4eva** [comment]
It's better if you run latest versions...
