### ISSUE TITLE
Citizens Plugin (Not working) Help

### ISSUE THREAD

**Issue by tony7897** [CitizensDev/Citizens#1181]
When i put citizens in my plugin folder and launch my server and do /plugins .citizens is red how do i fix it?

**Comment by mcmonkey4eva** [comment]
Download the appropriate version of Citizens for your Spigot version here: http://wiki.citizensnpcs.co/Versions

**Comment by tony7897** [comment]
what version?

**Comment by mcmonkey4eva** [comment]
The one that matches your Spigot version.

**Comment by tony7897** [comment]
how do i check?

**Comment by mcmonkey4eva** [comment]
By knowing the basic information of your own server.

If you can't figure that out, you shouldn't be running a server.
