### ISSUE TITLE
Citizens not creating NPCS

### ISSUE THREAD

**Issue by XxMCProxX** [CitizensDev/Citizens#1183]
When I try to create NPC's it keeps saying:
Please report this error: [See console]
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
If you can, please help me!

**Comment by mcmonkey4eva** [comment]
Download a modern version for your server, Citizens original version is discontinued in favor of 2.0
https://wiki.citizensnpcs.co/Versions
