### ISSUE TITLE
Nametag Visibility Toggle Stopped Working

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#1187]
Hello
When I Type `/npc name` it writes that it toggled the nametag visibility but the nametag is still there.
Can You Tell Me Why ?

Here Is My Plugins List (Beacause I Think Some Plugin Is Blocking It)
`Plugins (42): Itemizer, GunGame, WorldEdit, AnimatedScoreboard, BuildersUtilities, PlaceholderAPI, SurvivalGames, WorldGuard, Multiverse-Core, DeathMessagesPrime, Slimefun, JoinMaster, EggWars, PowerRanks, Multiverse-Portals, MCMurder, Vault, BiteSkyWarsReloaded, Coupons, CrazyEnchantments, Coins, Essentials, BuildingGame, GadgetsMenu, AuthMe, Paintball, TNTRun, HolographicDisplays, GUIShop, Citizens, DeluxeMenus, InfoBoardReloaded, CommandNPC, BossShop, CratesPlus, MyPet, MyPet-NPC, MinigamesLib, MGSkyWars, MGDeathRun, MGMobEscape, MGSplegg`

**Comment by mcmonkey4eva** [comment]
Wrong repository mate.

**Comment by ghost** [comment]
okay..... where should i write this ?

**Comment by mcmonkey4eva** [comment]
search for related issues on https://github.com/CitizensDev/Citizens2/issues
