### ISSUE TITLE
waypoint can't be removed!

### ISSUE THREAD

**Issue by chiikakian** [CitizensDev/Citizens#1191]
I have some issue with this waypoint that visible and can't be removed. eventhough there are no npc passing that place
any idea how should i fix it?

![2018-03-22_12 25 25](https://user-images.githubusercontent.com/37650084/37754302-9abf7bc6-2dd3-11e8-88cf-eb5d0021e29b.png)

**Comment by mcmonkey4eva** [comment]
If that's a debug waypoint mark and is just not removed by glitch:
Reconnect to the server or restart the server.

**Comment by mcmonkey4eva** [comment]
That was meant to be an issue with Citizens2 https://github.com/CitizensDev/Citizens2
