### ISSUE TITLE
Using /npc remove when an npc is "sit" does not remove it

### ISSUE THREAD

**Issue by Astrareach** [CitizensDev/Citizens#1192]
Bug : Using /npc remove when an npc is "sit" with the command "/npc sit" does not remove it, it remove the npc from the "sit" mode only, and we have to reselect the npc to remove it
![image](https://user-images.githubusercontent.com/20723083/48319643-8af55800-e610-11e8-8b4a-019cb7d1b890.png)

/version : 1.12.2  git-spigot-eb3d921-2b93d83
Citizens version : Citizens v2.0.24-SNAPSHOT (build 1591)
Denizen version : 1.0.3-SNAPSHOT (build 454-DEV) core version: 1.20 (build 162)

**Comment by mcmonkey4eva** [comment]
You selected (and then removed) the invisible armor stand special NPC that the main NPC is sitting on, instead of the main NPC itself.

**Comment by mcmonkey4eva** [comment]
Also this is the wrong repo entirely
