### ISSUE TITLE
Trader Bug

### ISSUE THREAD

**Issue by Xlar** [CitizensDev/Citizens#12]
There is a bug with trader npcs where if you click the item fast enough and then press the escape key it will drop the item(s) in-front of you with out having to pay for it. You would need 2 accounts to test out the bug since it will only work for the customer, not the owner of the NPC. The bug is sometimes difficult to pull off, but I know it is possible since I have done it a few times myself. I think it may have to do with lag, the more lag on the server the easier to pull off but I am not sure.

Thanks for reading.

**Comment by fullwall** [comment]
It is indeed to do with lag, and also cannot be fixed until bukkit adds inventory events.
