### ISSUE TITLE
1.8 Generates an exception

### ISSUE THREAD

**Issue by SamuraiKal** [CitizensDev/Citizens#120]
I'm not sure if it's a bukkit issue that they haven't gotten around to yet in their mad dash to get a stable build, or if there is a function change in 1.8 that Citizens needs to account for so I'm posting it here and on the Bukkit project.  If it is something Citizens needs to account for, I hope this gives you a head start if you haven't discovered this already.  Otherwise, if it is bukkit, just tell me to stfu and gtfo :P

08:58:29 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
08:58:29 [INFO] [Citizens] PermissionsBukkit isn't loaded, some features are unavailable.
08:58:29 [INFO] [Citizens] version [devBuild-151] loaded.
08:58:29 [INFO] [Citizens] Economy plugin found (iConomy version: 5)
08:58:29 [INFO] [Factions v1.4.7] === ENABLE START ===
08:58:29 [INFO] [Factions v1.4.7] Loading conf from disk
08:58:29 [INFO] [Factions v1.4.7] Loading players from disk
08:58:29 [INFO] [Factions v1.4.7] Loading factions from disk
08:58:29 [INFO] [Factions v1.4.7] Loading board from disk
08:58:29 [INFO] [Factions v1.4.7] Found and will use Permissions v2.7.7 for permissions
08:58:29 [INFO] [Factions v1.4.7] iConomy hook available, but disabled ("econIConomyEnabled": false).
08:58:29 [INFO] [Factions v1.4.7] === ENABLE DONE (Took 147ms) ===
08:58:29 [INFO] [mcMMO] PermissionsEx found, using PermissionsEx.
08:58:29 [INFO] Loading Config File...
08:58:30 [INFO] mcMMO version 1.1.13 is enabled!
08:58:30 [INFO] Server permissions file permissions.yml is empty, ignoring it
08:58:30 [INFO] Done (0.641s)! For help, type "help" or "?"
08:58:30 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:36)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:310)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:139)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by MadcowD** [comment]
That's citizens I believe. Or rather they haven't implemented a proper use of the changes in the item manager for whatever reasons (item duping glitch?). I guess well see what happens.

**Comment by aPunch** [comment]
Upgrade to the latest developmental build.
