### ISSUE TITLE
HELP PLEASE :,(

### ISSUE THREAD

**Issue by GummybearQc** [CitizensDev/Citizens#121]
23:41:47 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldM
anager.<init>(Lnet/minecraft/server/WorldServer;)V
23:41:47 [SEVERE]       at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPC
Spawner.java:35)
23:41:47 [SEVERE]       at com.citizens.npcs.NPCManager.register(NPCManager.java
:46)
23:41:47 [SEVERE]       at com.citizens.npcs.NPCManager.register(NPCManager.java
:89)
23:41:47 [SEVERE]       at com.citizens.commands.commands.BasicCommands.create(B
asicCommands.java:235)
23:41:47 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
23:41:47 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
23:41:47 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
23:41:47 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
23:41:47 [SEVERE]       at com.citizens.resources.sk89q.CommandsManager.executeM
ethod(CommandsManager.java:518)
23:41:47 [SEVERE]       at com.citizens.resources.sk89q.CommandsManager.execute(
CommandsManager.java:404)
23:41:47 [SEVERE]       at com.citizens.Citizens.onCommand(Citizens.java:196)
23:41:47 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:39)
23:41:47 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:163)
23:41:47 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:347)
23:41:47 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(N
etServerHandler.java:756)
23:41:47 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:721)
23:41:47 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:714)
23:41:47 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:3
3)
23:41:47 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:226)
23:41:47 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:91)
23:41:47 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile
:108)
23:41:47 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServe
r.java:464)
23:41:47 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:374)
23:41:47 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:417)

Thats my bug/issue/error.

**Comment by defaultsucks** [comment]
Would you please let us know which version of citizens/craftbukkit/minecraft this is on?

**Comment by aPunch** [comment]
We aren't going to help you if you don't provide the proper information.
