### ISSUE TITLE
"No type flags specified" guard and flad issue

### ISSUE THREAD

**Issue by Djidiouf** [CitizensDev/Citizens#123]
Hi,

I have the following notification "No type flags specified" when after select an NPC, I type :
/guard addflag mob
/guard addflag creeper
/guard addflag 5 NAMEOFAPLAYER
 etc.

So when I want to add a flag, it's just don't work and my NPC is still not hostile with anyone (for a bouncer with aggro on, it's annoying.

I don't even know if I typed the right command so, if you could help me, It will be very nice.

version #165 of Citizens.jar and Guard.jar

Here my npc-profiles.yml configuration :

'0':
    basic:
        name: Vectis
        color: '15'
        look-when-close: 'true'
        items: 272:0,0:0,0:0,0:0,0:0,
        location: world,-649.78125,71.5,814.65625,168.98026,11.77623
        owner: Djidiouf
        inventory: 272/1/0,AIR*35,
        talk-when-close: 'false'
    guard:
        type: BOUNCER
        toggle: 'true'
        radius: '100.0'
        aggressive: 'true'

**Comment by RincewindSCC** [comment]
try /guard addflag 1 name -p

**Comment by Djidiouf** [comment]
Thank you a lot, it is working now, I have just a little issue when a delete a flag because after a reboot of the server, the former settings are reapplied, even when I have type /citizens save after a delete of a flag.

My workaround was to edit the configuration file and delete the flag I wouldn't anymore.

Thank you, it is ok for me !
