### ISSUE TITLE
Error on NPC creation Build 168

### ISSUE THREAD

**Issue by Coffeehedake** [CitizensDev/Citizens#125]
http://pastebin.com/2ufgCZiA

used "/npc create" can reproduce this every time.

Above is a pasted stacktrace from my server console.

Build number 168, freshly rebuilt configs (generated automatically by citizens).

Let me know if there's anything else I can provide.

git-Bukkit-0.0.0-980-g4ed23b1-b1060jnks (MC: 1.7.3)
MCMA 0.9.7.0

**Comment by Ratismal** [comment]
i'm having the same problem as you are :(

**Comment by Coffeehedake** [comment]
I've noticed this for the last couple of builds. Thought deleting all of my configs and starting from scratch might help, but alas, no dice.

**Comment by 1born2kill** [comment]
same shit... Urghh... bye bye citizens

**Comment by defaultsucks** [comment]
Newest citizens builds are for 1.8. You're using 1.7.3

**Comment by Coffeehedake** [comment]
How is that possible, 1.8 CraftBukkit isn't even out yet?

**Comment by tips48** [comment]
Its been out for 3ish days ;)

**Comment by Coffeehedake** [comment]
The bukkit version or just vanilla minecraft MP? I see no recommended build updates, only dev builds of 1.8.1 CraftBukkit. Currently at #1149

**Comment by tips48** [comment]
Its not a RB, but its out

**Comment by defaultsucks** [comment]
All the builds from 1092 are experimental 1.8 builds.
