### ISSUE TITLE
can't create a npc

### ISSUE THREAD

**Issue by st0ned** [CitizensDev/Citizens#129]
i got this ingame

please report this error: [see console]
java.lang.nullpointerexception: null

and in pail server manager(console)

02:17 PM [SEVERE] java.lang.NullPointerException 
02:17 PM [SEVERE]   at net.citizensnpcs.resources.sk89q.CommandsManager.hasCommand(CommandsManager.java:252) 
02:17 PM [SEVERE]   at net.citizensnpcs.Citizens.onCommand(Citizens.java:190) 
02:17 PM [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39) 
02:17 PM [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163) 
02:17 PM [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:347) 
02:17 PM [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:755) 
02:17 PM [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:720) 
02:17 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:713) 
02:17 PM [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33) 
02:17 PM [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
02:17 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:91) 
02:17 PM [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:108) 
02:17 PM [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464) 
02:17 PM [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374) 
02:17 PM [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:417) 

please help me!!

i downloaded it form the source(https://github.com/CitizensDev/Citizens) i think it is 1.8 and i paste al jars form libs and releases to the plugin folder and i change the citizens.yml basic: creation: 0 so i dont have to pay coin for basic npc and i still don't now how to get coins to create npc

**Comment by fullwall** [comment]
Try downloading from http://ci.citizensnpcs.net
