### ISSUE TITLE
Huge npc-profiles.yml and server lockup

### ISSUE THREAD

**Issue by Valdiralita** [CitizensDev/Citizens#130]
Bukkit: rev 1194
Citizens Version: dev build 167

After creation of 13 or 14 waypoints for an npc, saving and restarting the server the server freezes while starting with 2+GB and 100% cpu usage.
The npc-profiles.yml was about 7MB big.
Here is an upload
http://filebeam.com/9a76a1a6125910762a01a4ce0250dd58
and VirusTotal
http://www.virustotal.com/file-scan/report.html?id=b1914ef963ec3c33e3b10896573077f0eea3391230b1615807b17dfdc49d5c31-1316552527

regards

**Comment by Valdiralita** [comment]
server log https://gist.github.com/1230434

**Comment by Valdiralita** [comment]
stupid buttons ...

**Comment by defaultsucks** [comment]
This is a known bug. Supposedly it was fixed in the newest citizens build. Try it out and let us know if it works.

Also for any future reference, please use pastebin. We don't need the whole file, just a small bit of it.
