### ISSUE TITLE
Error Can Not Create NPC

### ISSUE THREAD

**Issue by punkassassin** [CitizensDev/Citizens#132]
I get this message when i try to do /npc create .... "java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init><Lnet/minecraft/server/WorldServer;>V"

And also my minecraft keeps saying Out of Memory!   This could be cause by a bug in the game or by the Java Virtual Machine not being allocated enough memory.

**Comment by aPunch** [comment]
Sorry, this is a user error that can be fixed by reading.

**Comment by punkassassin** [comment]
I don't know where to look
