### ISSUE TITLE
Wizard weird teleport issue

### ISSUE THREAD

**Issue by MikeGold** [CitizensDev/Citizens#139]
I'm using most recent bukkit for Minecraft 1.7, spout, essentials etc. my problem is that when I create the wizard, on the random basis instead of teleporting me to the given location it is teleporting me to the ceiling of the room. When I change wizard status to time, it is changing time as it should, but still each time I use it, at the same time it is teleporting me as well to the ceiling of the room. 

List of my plugins: DirectBank, DreamLand, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, iConomy, MoneyDrop, NPCQuester, Permissions, PersonalChest, Spout, uQuest, vanishNoPickup, Citizens, mcMMO, OddItem, MyWolf All in the most recent versions for Minecraft 1.7.3.

**Comment by aPunch** [comment]
What version of Citizens are you using? Could you or someone else try testing this on the latest dev build on MC Beta 1.8.1?

**Comment by MikeGold** [comment]
I've sorted the issue. I don't know which plugin was at fault but when I hit any npc with a feather, (Right Mouse Button), player jups to the ceiling. All I had to do was to change the item used to interact with npc and now it works fine.
