### ISSUE TITLE
Could not create NPC.

### ISSUE THREAD

**Issue by stelz** [CitizensDev/Citizens#140]
When i'm trying to create a NPC it's saying:

java.lang.NoSuchMethodError: net.minecraft.server.ItemInWor­ldManager.<init (Lnet/minecraft/server/worldse­rver;)V

is v1.0.9d compatible with Minecraft Bukkit 1.8?

If it isn't how could i update it? 
or when will it get updated? 
is there any ways i am supposed to use it in 1.8? :( Because i want it so bad...

Please answer, and thanks for reading.

**Comment by aPunch** [comment]
Download a developmental build at ci.citizensnpcs.net if you want 1.8-compatibility.
