### ISSUE TITLE
whenever i try to create an NPC this happens

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#144]
02:07 PM [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V 
02:07 PM [SEVERE]   at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:35) 
02:07 PM [SEVERE]   at com.citizens.npcs.NPCManager.register(NPCManager.java:46) 
02:07 PM [SEVERE]   at com.citizens.npcs.NPCManager.register(NPCManager.java:89) 
02:07 PM [SEVERE]   at com.citizens.commands.commands.BasicCommands.create(BasicCommands.java:235) 
02:07 PM [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
02:07 PM [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
02:07 PM [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
02:07 PM [SEVERE]   at java.lang.reflect.Method.invoke(Unknown Source) 
02:07 PM [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:518) 
02:07 PM [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.execute(CommandsManager.java:404) 
02:07 PM [SEVERE]   at com.citizens.Citizens.onCommand(Citizens.java:196) 
02:07 PM [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39) 
02:07 PM [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163) 
02:07 PM [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714) 
02:07 PM [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33) 
02:07 PM [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92) 
02:07 PM [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:108) 
02:07 PM [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464) 
02:07 PM [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374) 
02:07 PM [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:417) 
02:07 PM [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V 
02:07 PM [SEVERE]   at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:35) 
02:07 PM [SEVERE]   at com.citizens.npcs.NPCManager.register(NPCManager.java:46) 
02:07 PM [SEVERE]   at com.citizens.npcs.NPCManager.register(NPCManager.java:89) 
02:07 PM [SEVERE]   at com.citizens.commands.commands.BasicCommands.create(BasicCommands.java:235) 
02:07 PM [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
02:07 PM [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
02:07 PM [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
02:07 PM [SEVERE]   at java.lang.reflect.Method.invoke(Unknown Source) 
02:07 PM [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:518) 
02:07 PM [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.execute(CommandsManager.java:404) 
02:07 PM [SEVERE]   at com.citizens.Citizens.onCommand(Citizens.java:196) 
02:07 PM [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39) 
02:07 PM [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163) 
02:07 PM [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714) 
02:07 PM [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33) 
02:07 PM [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
02:07 PM [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92) 
02:07 PM [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:108) 
02:07 PM [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464) 
02:07 PM [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374) 
02:07 PM [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by defaultsucks** [comment]
1.0.9d does not work with any craftbukkit builds for 1.8. Try the newest dev builds of citizens:
http://jenkins.citizensnpcs.net:81/job/Citizens/

**Comment by ghost** [comment]
thanks
