### ISSUE TITLE
Used tools are repaired by Trader on server reboot !

### ISSUE THREAD

**Issue by Shereis** [CitizensDev/Citizens#15]
v1.0.9d on bukkit 1060.

I have searched on the forum and didn't see anyone saying anything about it so i report it here ;)

I have a Npc based trader economy system for players on my serveur... and it seems that the daily reboot of the server "repair" any used tools the npc Sell !
Its not very good for economy ! ; )

**Comment by fullwall** [comment]
Should be fixed in 1.1
