### ISSUE TITLE
Waypoint modifier permission nodes missing '.'

### ISSUE THREAD

**Issue by ugoff** [CitizensDev/Citizens#151]
https://github.com/CitizensDev/Citizens/blob/master/src/core/net/citizensnpcs/commands/WaypointCommands.java#L43

if (!PermissionManager.hasPermission(player, "citizens.waypoints.modifier"

According to the wiki, it should be citizens.waypoints.modifier.(type), but the above line is missing the '.' after modifier. Enabling citizens.waypoints.modifierdelay currently allows the '/waypoints modifier delay' command to work, but citizens.waypoints.modifier.delay does not.

**Comment by fullwall** [comment]
Duplicate issue.
