### ISSUE TITLE
Waypoint modifier chat editors not accepting input

### ISSUE THREAD

**Issue by ugoff** [CitizensDev/Citizens#153]
After entering '/waypoint mod delay', instructions are given to type in the delay in seconds. Typing the number in as a standard chat message does not result in any confirmation that the input was taken or wrong. No messages follow this initial instruction. Upon re-entering the command, the warning is given that no more than one chat editor can be open at a time. No commands can stop the input. The server has to be restarted to stop the chat editor.

The other modifiers have the same problem.

**Comment by fullwall** [comment]
Thanks, will fix in next commit.

**Comment by Legolas75893** [comment]
Still not fixed
