### ISSUE TITLE
Creating Quests

### ISSUE THREAD

**Issue by lawdac** [CitizensDev/Citizens#154]
I used the exemplar.qst file to create a quest, copied and pasted the text into the quest.yml file, and I am unable to make a quest.

When I go in-game, I go to the NPC where I want to make the quest and I type /quest create MCRPG.Cadwal.generic.ReadingMaterial and it returns that this is not a quest.  Where do I put the name for the quest in the .yml file?

**Comment by lawdac** [comment]
Correction: it's /quest assign [name], but it's still not adding for me.

**Comment by defaultsucks** [comment]
Make your quest in the quests.yml file, go on minecraft and right click on an npc. Make sure you toggle the quester type on it to enabled. Use the /quester assign name when you have the npc selected to make that npc give that quest.

**Comment by lawdac** [comment]
Temp closing this issue, I think I had the wrong quest file and that's where the problem was coming in.
