### ISSUE TITLE
Can't see any NPCs

### ISSUE THREAD

**Issue by sizilium** [CitizensDev/Citizens#157]
"/npc create Test" creates and selects "Test" but is not visible!
There is no exception in the console, in general it seems to work. Just can't see npcs. 
/reload and /restart does not help.

Reproduce:
- Deleted old citizens config files
- Downoaded Citizens 1.1
- Restarted Server to create new config files automatically
- Translated some strings in "citizens.yml"
- Changed prices according the old config (no copy&paste)
- Started Server again
  -> does not work :-(

Minecraft Version 1.8.1 
Bukkit Version 1185

Installed Plugins:
ChestShop 3.2 - Acrobot > Enabled
Citizens 1.1 - fullwall, aPunch > Enabled
Elevators 1.4.3 > Enabled
iConomy 5.01 - Nijikokun > Enabled
LWC-Economy 1.30 - Hidendra > Enabled
LWC 3.52 - Hidendra > Enabled
BukkitCompat r15A - PhonicUK > Enabled
NoSnow 1.2 - Unknown Author > Enabled
NPCQuester 2.2.5 - Unknown Author > Disabled
PermissionsBukkit 1.1 - The Bukkit Team > Enabled
Residence 2.4.1 - bekvon > Enabled
SearchIds 2.3 - Unknown Author > Enabled
Stargate 0.6.9 - Drakia > Enabled
Permissions 2.7.7 (Bridge) - SpaceManiac, t3hk0d3, TheYeti, Nijiko > Enabled
ToughMelt 1.5 - Kevin Forte > Enabled 
uQuest 1.50 - Hawox > Disabled
PayDay 0.3.1 - TZer0 > Disabled

**Comment by sizilium** [comment]
Console output:

Citizens: NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
Citizens: Permissions system found (PermissionsBukkit v1.1)
Citizens: version [1.1] loaded.
Citizens: Economy plugin found (iConomy v5)
CONSOLE: Server permissions file permissions.yml is empty, ignoring it
CONSOLE: Reload complete.
CONSOLE: Reached end of stream
Citizens: Loaded 1 NPCs.
Citizens: Loaded 0 quests.

**Comment by sizilium** [comment]
npc-profiles.yml  :

<pre>
'0':
    basic:
        name: Test
        color: '15'
        look-when-close: 'true'
        items: 0:0,0:0,0:0,0:0,0:0,
        location: world,721.3000000119209,72.0,96.69999998807907,0.0,0.0
        owner: sizilium
        inventory: AIR*36,
        talk-when-close: 'false'
</pre>

**Comment by ecsos** [comment]
i have this problem too. i successfully created a citizen of myself, but not others.

**Comment by fullwall** [comment]
Can you try moving around a little? Sometimes the client doesn't always update straight away. Also, try looking above you for floating npcs (near spawn usually) - these indicate a plugin that is blocking npcs from teleporting. A partial fix is included for this in newer dev builds.

**Comment by sizilium** [comment]
Thank you fullwall, if i moving around the NPC appears.

However, i'm confused a little bit because yesterday i saw nothing...
