### ISSUE TITLE
Citizens nullpointer-exception at creating a NPC

### ISSUE THREAD

**Issue by A-B-C-D-E** [CitizensDev/Citizens#158]
Hello Citizens-Team,
I have a big problem with the Citizens-Plugin and Spout! At creating a NPC a nullpointer-exception at org.getspout.spout.player.SpoutCraftPlayer occures.
It seems that the versions of SpoutCraft and Citizens are incompatible, but I do not know how to disable the spoutcraft support. I tried to delete Spout, to see wheater it works without spoutcraft, and it did! But the real problem is, that I can't delete Spoutcraft, without crashing some other plugins.
I also tried to use the newest developer-preview of Spout, but it also crashed.
As a consequence of these errors, many other exeptions (for example a classCast-exception) occured.
I would be really pleased of your help, because the citizens-plugin is a good plugin, but it's even better if it works ;D
Following is the full server-log (since the first exception occured)
PS: Please excuse me, if my english is not very good, because I am german ;-)

19:04:19 [SEVERE] java.lang.NullPointerException
19:04:19 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
19:04:19 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
19:04:19 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
19:04:19 [SEVERE]       at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
19:04:19 [SEVERE]       at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
19:04:19 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
19:04:19 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
19:04:19 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
19:04:19 [SEVERE]       at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
19:04:19 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
19:04:19 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
19:04:19 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
19:04:19 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
19:04:19 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:04:19 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
19:04:19 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
19:04:19 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
19:04:19 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
19:04:19 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
19:04:19 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
19:04:20 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
19:04:19 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
19:04:20 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
19:04:20 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
19:04:20 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
19:04:20 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
19:04:20 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
19:04:20 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
19:04:20 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
19:04:20 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
19:04:20 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
19:04:20 [SEVERE]       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
19:04:20 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
19:04:20 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
19:04:20 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
19:04:20 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
19:04:20 [SEVERE] java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
19:04:20 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1013)
19:04:20 [SEVERE]       at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
19:04:20 [SEVERE]       at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
19:04:20 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
19:04:20 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
19:04:20 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
19:04:20 [SEVERE]       at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
19:04:20 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
19:04:20 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
19:04:20 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
19:04:20 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
19:04:20 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:04:20 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
19:04:20 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
19:04:20 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
19:04:20 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
19:04:20 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
19:04:20 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
19:04:21 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
19:04:20 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
19:04:21 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
19:04:21 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
19:04:21 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
19:04:21 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
19:04:21 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
19:04:21 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
19:04:21 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
19:04:21 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
19:04:21 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
19:04:21 [SEVERE]       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
19:04:21 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
19:04:21 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
19:04:21 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
19:04:21 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
19:04:21 [SEVERE] java.lang.NullPointerException
19:04:21 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
19:04:21 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
19:04:21 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
19:04:21 [SEVERE]       at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
19:04:21 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
19:04:21 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
19:04:21 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
19:04:21 [SEVERE]       at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
19:04:21 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
19:04:21 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
19:04:21 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
19:04:21 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
19:04:21 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:04:21 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
19:04:21 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
19:04:21 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
19:04:21 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
19:04:21 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
19:04:21 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
19:04:22 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
19:04:21 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
19:04:22 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
19:04:22 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
19:04:22 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
19:04:22 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
19:04:22 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
19:04:22 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
19:04:22 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
19:04:22 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
19:04:22 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
19:04:22 [SEVERE]       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
19:04:22 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
19:04:22 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
19:04:22 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
19:04:22 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
19:04:22 [SEVERE] Could not pass event PLAYER_TELEPORT to Spout
java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
        at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1013)
        at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
        at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
        at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
        at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
        at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
19:04:22 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?

Thank you, and I hope, that the error is not as big ;D

**Comment by fullwall** [comment]
Please download a newer dev version of Citizens to fix this.
