### ISSUE TITLE
Problem with 1.1 and PermEX

### ISSUE THREAD

**Issue by MikeGold** [CitizensDev/Citizens#159]
Ok. I'm about to give up. I've tried PermissionsEX, and everything is
ok, but when I try to use my old NPC profiles, I'm flooded with so
many errors that after a few minutes I gave up. Now, if I try to start
from scratch, and created my first npc and toggled him to trader it
worked ok, but when I try to click hom (either right or left) nothing
happens in game but on server I get some errors.

Here is the log of my server starting, then I'm running a client and
trying to click npc and here comes the bug.

D:\instalki.craftbukkit>"C:\Program Files (x86)\Java\jre6\bin\java.exe" -Xincgc
 -Xmx1G -jar -jar D:\instalki.craftbukkit\craftbukkit-0.0.1-SNAPSHOT.jar
161 recipes
17 achievements
19:28:44 [INFO] Starting minecraft server version Beta 1.8.1
19:28:44 [INFO] Loading properties
19:28:44 [INFO] Starting Minecraft server on *:25565
19:28:45 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1067
-g6301507-b1185jnks (MC: 1.8.1)
19:28:45 [INFO] [PermissionsEx] sql backend registered!
19:28:45 [INFO] [PermissionsEx] file backend registered!
19:28:45 [INFO] [PermissionsEx] PermissionEx plugin initialized.
19:28:45 [INFO] MLog clients using java 1.4+ standard logging.
19:28:45 [INFO] [PermissionsEx] Initializing file backend
19:28:45 [INFO] Spout 1.0.6.382 has been initialized
19:28:45 [INFO] Preparing level "Mikania"
19:28:45 [INFO] Default game type: 0
19:28:46 [INFO] Preparing start region for level 0 (Seed: 6443500349175639597)
19:28:47 [INFO] Preparing spawn area: 57%
19:28:47 [INFO] Preparing start region for level 1 (Seed: 6443500349175639597)
19:28:48 [INFO] Preparing spawn area: 60%
19:28:48 [INFO] [*] DirectBank enabled.
19:28:48 [INFO] Preparing start region for level 2 (Seed: 6443500349175639597)
19:28:49 [INFO] Preparing spawn area for Mikania_nightmare, 85%
19:28:49 [INFO] Preparing start region for level 3 (Seed: -6399648701760404980)
19:28:50 [INFO] Preparing spawn area for Mikania_skylands, 97%
19:28:50 [INFO] DreamLand version 2.4 is enabled!
19:28:50 [WARNING] Version mismatch! Please update EssentialsGeoIP to the same v
ersion.
19:28:50 [INFO] Loaded Essentials build 2.6.1 by: Zenexer, ementalo, Aelux, Bret
tflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits
19:28:50 [INFO] Essentials: Using superperms based permissions.
19:28:50 [INFO] [Essentials] Payment method found (iConomy version: 5)
19:28:50 [INFO] Loaded EssentialsChat build 2.6.1 by: essentials team
19:28:50 [WARNING] Version mismatch! Please update all Essentials jars to the sa
me version.
19:28:50 [INFO] Loaded EssentialsGeoIP build 2.5.7 by: essentials team
19:28:50 [INFO] This product includes GeoLite data created by MaxMind, available
 from http://www.maxmind.com/.
19:28:51 [INFO] Initializing c3p0-0.9.1.2 [built 21-May-2007 15:04:56; debug? tr
ue; trace: 10]
19:28:51 [INFO] Loaded EssentialsProtect build 2.6.1 by: essentials team
19:28:51 [INFO] Loaded EssentialsSpawn build 2.6.1 by: essentials team
19:28:53 [INFO] [iConomy] Logging is currently disabled.
19:28:53 [INFO] [iConomy] v5.0 (Eruanna) loaded.
19:28:53 [INFO] [iConomy] Developed by: [Nijikokun]
19:28:53 [INFO] MoneyDrop is up and running!
19:28:53 [INFO] [MoneyDrop] Economy found. Money pickup enabled.
19:28:53 [INFO] [NPC-Quester]: Setting up config files
19:28:53 [INFO] [NPC-Quester]: Config file found!
19:28:53 [INFO] [NPC-Quester]: Players file found!
19:28:53 [INFO] [NPC-Quester]: Permissions not detected
19:28:53 [INFO] [NPC-Quester]: Random branch is empty, ignoring.
19:28:53 [INFO] [NPC-Quester]: Players branch is empty, ignoring.
19:28:53 [INFO] [NPC-Quester]: Players completed branch is empty, ignoring.
19:28:53 [INFO] [NPC-Quester]: enabled
19:28:53 [INFO] [PermissionsEx] Superperms support enabled.
19:28:53 [INFO] [PermissionsEx] v1.14 enabled
19:28:53 [INFO] Essentials: Using PermissionsEx based permissions.
19:28:53 [INFO] [PersonalChest] version 1.0.1 loading...
19:28:53 [INFO] [PersonalChest] version 1.0.1 is enabled without permissions!
19:28:53 [INFO] [uQuest] Loaded with Flatfile!
19:28:53 [INFO] [uQuest] v1.5 enabled! With 53 quests loaded!
19:28:53 [INFO] [VanishNoPickup] Permissions not detected.
19:28:53 [INFO] [VanishNoPickup] 1.9.12 enabled.
19:28:53 [INFO] [mcMMO] PermissionsEx found, using PermissionsEx.
19:28:53 [INFO] Loading Config File...
19:28:55 [INFO] mcMMO version 1.1.11 is enabled!
19:28:55 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester,
 trader, wizard
19:28:55 [INFO] [Citizens] Permissions system found (PermissionsEx v1.14)
19:28:55 [INFO] [Citizens] version [devBuild-205] loaded.
19:28:55 [INFO] [Citizens] Economy plugin found (iConomy v5)
19:28:55 [INFO] [MyWolf] PermissionsEX integration enabled!
19:28:55 [INFO] [MyWolf] 1 wolf/wolves loaded
19:28:55 [INFO] [MyWolf] version 0.5.0 ENABLED
19:28:55 [INFO] [OddItem] 0.7.3.1 enabled
19:28:55 [INFO] [OddItem] Using RefinedSoundEx for suggestions.
19:28:55 [INFO] [OddItem] Group samplegroup added: [greenwool, ironblock:2, diod
e]
19:28:55 [INFO] [OddItem] 851 aliases loaded.
19:28:55 [INFO] Done (0.979s)! For help, type "help" or "?"
19:28:55 [INFO] [Citizens] Loaded 1 NPCs.
19:28:55 [INFO] [Citizens] Loaded 0 quests.
19:28:55 [INFO] New max size: 484
19:28:55 [INFO] New max size: 784
19:28:58 [INFO] [uQuest] Successfully linked with iConomy.
19:28:58 [INFO] [uQuest] Successfully linked with Essentials.
19:28:58 [SEVERE] [uQuest] Permissions is not loaded. Turning Permissions suppor
t off.
19:29:01 [INFO] mikandesu [/192.168.1.2:60400] logged in with entity id 395 at (
[Mikania] 95.9115627147039, 28.5, -69.35114815649155)
19:29:02 [INFO] Reading data
19:29:02 [INFO] [Spout] Successfully authenticated mikandesu's Spoutcraft client
. Running client version: 1.0.6.449
19:29:02 [INFO] [NPC-Quester] Total quests: 53
19:29:15 [SEVERE] Could not pass event PLAYER_INTERACT_ENTITY to NPCQuester
java.lang.NoClassDefFoundError: com/citizens/npcs/NPCManager
       at randy.npcq.npcqEntityListener.onPlayerInteractEntity(npcqEntityListen
er.java:55)
       at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.j
ava:321)
       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:58)
       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:338)
       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:902)
       at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java
:500)
       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.ClassNotFoundException: com.citizens.npcs.NPCManager
       at java.net.URLClassLoader$1.run(Unknown Source)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(Unknown Source)
       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:36)
       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:24)
       at java.lang.ClassLoader.loadClass(Unknown Source)
       at java.lang.ClassLoader.loadClass(Unknown Source)
       ... 13 more

**Comment by MikeGold** [comment]
I've discovered by removing plugins one by one, that citizens works fine on my server when I remove spout. Though some of the important plugins I have depend on the spout, I cannot get rid of it.

**Comment by fullwall** [comment]
Can you please download a newer dev build of Citizens and retest? http://ci.citizensnpcs.net

**Comment by MikeGold** [comment]
I've checked the most recent dev build. It still gives some minor
errors, like a few end of streams (about 5) and some other rubish
while using it, but it's nothing gamebreaking. Good work! All my npcs
are back. Thanks :).

2011/9/26 fullwall
reply@reply.github.com:

> Can you please download a newer dev build of Citizens and retest? http://ci.citizensnpcs.net
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/CitizensDev/Citizens/issues/159#issuecomment-2196050

## 

---

Never argue with an idiot. First he will bring you down to his level
then he will beat you with experience.
