### ISSUE TITLE
1.1 - Could not pass event CHUNK_UNLOAD to Citizens

### ISSUE THREAD

**Issue by Coffeehedake** [CitizensDev/Citizens#16]
2011-08-25 23:14:21 [SEVERE] Could not pass event CHUNK_UNLOAD to Citizens
Error:  Minecraft server error. Server will be restarted.
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
2011-08-25 23:14:21 [INFO] coffeehedake lost connection: user was kicked.
2011-08-25 23:14:21 [SEVERE] Could not pass event PLAYER_QUIT to PermissionsBukkit
java.lang.IllegalArgumentException: Attachment cannot be null
2011-08-25 23:14:21 [INFO] <_Console_>: Server is restarting. World is being saved.

Version 1.1 Build #49 (Current build of Citizens.jar posted on http://ci.citizensnpcs.net/)
CraftBukkit 1060: git-Bukkit-0.0.0-980-g4ed23b1-b1060jnks (MC: 1.7.3)
Running PermissionsBukkit + SuperPerms Bridge

Following the above message, server restarts. Anything I can upload to help you guys is all yours... configs... whatever you want. Good luck!

Complete PasteBin of event (new event, but is reproducible every time, note the time stamps)
http://pastebin.com/igA9ugEh

**Comment by aPunch** [comment]
Is that the complete stack trace?

**Comment by Coffeehedake** [comment]
No, but most of the rest was the other plugins shutting down. I can get that for you, I didn't include it here only because that was the last error related to citizens.

**Comment by Coffeehedake** [comment]
Here you go guys:
http://pastebin.com/igA9ugEh

**Comment by Coffeehedake** [comment]
An update on this:
I noticed there is a new variable in the citizens.yml for bukkit permissions. This was set to FALSE in my config. I have changed it to use the new bukkit permissions, and so far (it has only been a few minutes) the server has not crashed. Will continue to test. Could it have been an issue relating to the bridge plugin?

**Comment by aPunch** [comment]
I removed the code that was causing this issue. It has to do with the 'general.debug-mode' setting not loading before chunks are unloaded. Could you test the latest build to see if this error is still present? Thanks :D
