### ISSUE TITLE
Citizens 1.1 dev 205 wierd spawn and overloading server

### ISSUE THREAD

**Issue by hiro24** [CitizensDev/Citizens#161]
First, great job fixing the spout issues. :)  You guys are amazing.

Second, couple oddities to report w/ your dev 205 build. I made an NPC of one of the characters who plays on our server.  And lo and behold!  When he logged off and back on, he replaced the actual location of his NPC with himself!  His NPC was then gone.  Maybe this was due to me doing a /npc move on the NPC... dunno. To my knowledge, no errors reported in console.

Third, at times, NPCs show up in our player list.. like... /who.  it can show our NPCs for some reason.  This is very odd and annoying.  If it could be looked into, that'd be great.

Forth, almost as soon as we load up citizens and make an NPC, our console starts getting hit w/ server cannot keep up spam.  It only happens when we're using citizens.  Resource-wise, at the height of the problem we were using about 6 of 20 gb ram, and 35% CPU, so we were anything but overloaded.

We'd really appreciate it if you could look into these issues.  As I stated above, we noticed these problems w/ citizens 1.1 dev 205 (were using it to see if it fixed the spout errors) and bukkit RB 1185.

**Comment by fullwall** [comment]
OK, I'll look into the performance issues. Also yes, I think in 1.8 it seems that something has made NPCs more recognised as 'players', causing a number of issues -- very strange :S.

**Comment by hiro24** [comment]
Thanks a ton fullwall :)

**Comment by fullwall** [comment]
Could you post a list of your plugins please? It could be a plugin conflict....

**Comment by hiro24** [comment]
This is what we currently have loaded... sry, don't really have versions of everything readily available

PermissionsBukkit-1.2.jar
AncientGates.jar
BlockCantKeepUpSpam.jar
BookWorm.jar
ChestShop.jar
Citizens.jar
CommandSigns.jar
dynmap.jar
ecoCreature.jar
Essentials.jar
FalseBookBlock.jar
FalseBookCore.jar
FalseBookExtra.jar
FalseBookIC.jar
Heroes.jar
iConomy.jar
Jail.jar
LogBlock.jar
LogBlockQuestioner.jar
LWC.jar
MagicCarpet.jar
mChatEssentials.jar
mChat.jar
MobDisguise.jar
Multiverse-Core.jar
Multiverse-Portals.jar
NoCheat.jar
obuJustShutTheHellUp.jar
Questioner.jar
RageMute.jar
rawcritics_ore_obfuscation_plugin_spout.jar
RealCompass.jar
Register.jar
spoutEssentials.jar
Spout.jar
SpoutWallet.jar
Towny.jar
VanishNoPacket.jar
Vault.jar
VoxelSniper.jar
WorldBorder.jar
WorldEdit.jar
WorldGuard.jar
