### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by jaseaman** [CitizensDev/Citizens#166]
Does Citizens have any compatibility with multi-world?

I am currently using multi-verse and everytime i go to reload the server one of them crash and i am not able to use the multiverse commands. I dont know what side this is on but  it seems there is a major incompatibility with these two plugins, to the point where we have to take out all the plugins and install them one by one, sort of a pain when you are restarting the server many times a day.

I love this plugin, just to make it clear, but if this compatibility was well.....Compatable it would be better.

Any Ideas or help?

**Comment by fullwall** [comment]
Can you please pastebin the error?

**Comment by jaseaman** [comment]
Ok don't worry, we sorted it out via removing permissions, might have been interfering with the multiverse commands
