### ISSUE TITLE
Suggestion for Questers: Link into Heroes API

### ISSUE THREAD

**Issue by hiro24** [CitizensDev/Citizens#169]
An optional quest reward that would be amazing would be to link into the Heroes API and offer experience.  

http://forums.bukkit.org/threads/rpg-heroes-v1-2-3-classes-skills-experience-damage-system-1060.27358/

We use Heroes extensively, and being able to reward players who quest w/ experience towards leveling their hero would be a perfect fit.  They seem to have an API for linking in and giving experience, so I would imagine adding this in would be a quick and easy task.  What are the chances this could happen in the future?

**Comment by fullwall** [comment]
We have quite a few dependencies already, however, this might be an option in the future post-1.1.
