### ISSUE TITLE
Alchemist Error on Toggle

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#17]
What steps will reproduce the problem?

Try and toggle an NPC to be an alchemist!

What is the expected output? What do you see instead?

http://dev.bukkit.org/paste/3769/

**Comment by aPunch** [comment]
This is not a priority for 1.1. Please repost in Issue Tracker and I will move it into the next release's milestone.

**Comment by mbsuperstar1** [comment]
Fullwall has fixed this regardless. Kudos.
