### ISSUE TITLE
NPC's not appearing.

### ISSUE THREAD

**Issue by Teddeh-zz** [CitizensDev/Citizens#171]
When I spawn an NPC it says it has spawned for a 100 Dollars but it doesn't appear?
It just vanishes? Help please! D:

**Comment by Embolex** [comment]
I have not the same but a problem like this .....

If i start my server, the console says 3 npc loaded .... 
when i go to the npcs thy are there ... if i left the world or die and come ´back to the npcs they are all gone ..... seems to be ... i testet the npcs with a neutral "default" account ... without any special permissions but these i have to give .. (trade.use.trade ... ect) ..... I made with my op account the npcs Guardian1 and 2 ... thy are both guards and have the flag -a to attack mobs and groups as well .... 

so ... if i go with default account online .... and go to the npcs ... they are there ... if i die and go back to them ... they are away ... but NO .. they re still there but i dont see them ... i only see that they are there is, that i loose my life if i come to near to them ....... 

I have no error message in console

i´m using citizens 1.1  ... last update i´ve made is yesterday

greetz, me
