### ISSUE TITLE
Cannot Delete/Replace File (quests.yml)

### ISSUE THREAD

**Issue by lawdac** [CitizensDev/Citizens#172]
I'm trying to upload a new quests.yml file to my server to test out some quests; however, I keep getting the error that the file is in use.  I have already stopped my server and have even deleted all Citizens files from my server with exception of this one because I cannot delete it since it's "still in use."

**Comment by Embolex** [comment]
Do you have checked there is a Editor (or anything else) open within the open file ? ... then u cant delete the file too.

**Comment by lawdac** [comment]
I don't believe the file is open in an editor.  I don't know how to open files straight from the website, particularly YML files.  I know that I use an FTP client for most file transfers, but I can't do anything with that file from there either.

**Comment by fullwall** [comment]
Hmmm... what OS is the server running?

**Comment by lawdac** [comment]
Problem fixed itself.
