### ISSUE TITLE
Traders aren't working

### ISSUE THREAD

**Issue by BodyshotzVG** [CitizensDev/Citizens#175]
SOLVED! Was tired of avoiding the fact that I had to re-write all the citizens permissions, just 7-zipped the .jar file, and look in plugin.yml to see all the permission nodes.

So I just re-wrote everything, and it works smoothly.

**Comment by fullwall** [comment]
What permissions plugin are you using?

**Comment by Bloodlex** [comment]
I use PermissionsEx and have the same issue with traders, please do something about it.

**Comment by Embolex** [comment]
Update your citizens.jar and Types : http://citizensnpcs.net/

**Comment by fullwall** [comment]
The permission should be 'citizens.trader.use.trade'

**Comment by Realexa** [comment]
Doesn't work for my users either. I got citizens.trader.use.trade: true in PermissionsBukkit set up and i'm using devBuild-218.
I tried one that was slighly newer (there are a few builds which are 4hours newer) but i had some errors in my console with those.

Is build 218 the cause or am i mission something else?
