### ISSUE TITLE
Evil NPCs not spawning?

### ISSUE THREAD

**Issue by nmerchant** [CitizensDev/Citizens#177]
Set spawn to true, max to 50, and chance to 200 (not sure what this is supposed to be, tried 100 the first time).  Flew around for about 10 minutes and no evil NPCs in sight :[

**Comment by jaseaman** [comment]
I think the chance is more likely when it is lower try 5

**Comment by fullwall** [comment]
@myhijim is right, this has been changed in the latest build however.
