### ISSUE TITLE
Chat Makes the Say Everything

### ISSUE THREAD

**Issue by lawdac** [CitizensDev/Citizens#179]
When my players right click on an NPC with a book, they speak 8 times.  I don't even know where to begin troubleshooting this since there are no error messages.

**Comment by jaseaman** [comment]
I had this issue while walking near them, but a server restart fixed it

**Comment by fullwall** [comment]
Can't reproduce :S.

**Comment by lawdac** [comment]
Problem fixed itself following server restart.
