### ISSUE TITLE
Quester Error on right click!

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#18]
What steps will reproduce the problem?

I was just being friendly and thought I'd start a quest...and BAM!

What is the expected output? What do you see instead?

http://dev.bukkit.org/paste/3770/

**Comment by fullwall** [comment]
Can't trace this issue as it seems to be older. Can you try and reproduce it again?

**Comment by mbsuperstar1** [comment]
Seems to be fixed, nice job.
