### ISSUE TITLE
Suggestion: BANKERS

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#185]
The Name Says it all...

**Comment by jaseaman** [comment]
Good idea, can you give me a brief discription, i would love to share ideas.

I wish i got to this first :P

**Comment by ghost** [comment]
Like you can set up an npc that will bank your items and everyone will have a different bank (you should be able to set it so you CAN set a pin or somthing) and the only hard thing about this i think would be having a different storage per person
nothing else to say rely

**Comment by ghost** [comment]
soz keep clicking comment and close =(

**Comment by jaseaman** [comment]
Ahh that's a really smart idea, I was thinking you were talking about like essentials money, in fact your idea would help my server greatly as we use about 12 different worlds. Hope they can implement it.

**Comment by ghost** [comment]
like runescape (if you havent played it. world of warcraft) so when u access the bank you will only see the items you put in not what other players put in i would like those kinda bankers...

Glad u like my idea

Another idea could be maids You can like set them a task to do EG: collect wood but you have to pay them but id say bankers r more important

**Comment by jaseaman** [comment]
Yeah, ahh brings me back to the runescape days (I hate to say it) :P
