### ISSUE TITLE
Citizens and Groupmanger d'ont use trader exxept with the OP

### ISSUE THREAD

**Issue by hiyuu** [CitizensDev/Citizens#186]
Hello , I can not use the trader with groupmanger except with the OP.

My Config : 

"groups:
  Habitant:
    default: false
    permissions:
    - citizens.trader.use.trade
    - essentials.afk
    - essentials.back
    - essentials.back.ondeath
    - essentials.balance
    - essentials.chat.shout
    - essentials.compass
    - essentials.depth
    - essentials.home
    - essentials.kit
    - essentials.kit.tools
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.msg
    - essentials.pay
    - essentials.portal
    - essentials.protect
    - essentials.sethome
    - essentials.signs.break.disposal
    - essentials.signs.break.mail
    - essentials.signs.break.protection
    - essentials.signs.break.trade
    - essentials.signs.create.disposal
    - essentials.signs.create.mail
    - essentials.signs.create.protection
    - essentials.signs.create.trade
    - essentials.signs.use.*
    - essentials.suicide
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.worth
    - mobarena.arenas.*
    - mobarena.arenas.default
    - mobarena.classes.Archer
    - mobarena.classes.Chef
    - mobarena.classes.Knight
    - mobarena.classes.Oddjob
    - mobarena.classes.Tank
    - mobarena.use.join
    - mobarena.use.leave
    - mobarena.use.spectate
    inheritance:
    - visiteur
    info:
      prefix: '&2'
      build: true
      suffix: ''
  DemiDieu:
    default: false
    permissions:
    - '_'
    inheritance:
    - hero
    info:
      prefix: '&c'
      build: true
      suffix: ''
  Hero:
    default: false
    permissions:
    - essentials.ban
    - essentials.banip
    - essentials.broadcast
    - essentials.delwarp
    - essentials.eco
    - essentials.ext
    - essentials.getpos
    - essentials.jump
    - essentials.kick
    - essentials.kill
    - essentials.setwarp
    - essentials.signs.break._
    - essentials.signs.create.*
    - essentials.spawner
    - essentials.thunder
    - essentials.time
    - essentials.time.world
    - essentials.togglejail
    - essentials.top
    - essentials.tp
    - essentials.tphere
    - essentials.tpo
    - essentials.tpohere
    - essentials.tppos
    - essentials.tptoggle
    - essentials.unban
    - essentials.unbanip
    - essentials.weather
    - essentials.whois
    - essentials.world
    - groupmanager.listgroups
    - groupmanager.mandemote
    - groupmanager.manload
    - groupmanager.manpromote
    - groupmanager.mansave
    - groupmanager.manselect
    - groupmanager.manuadd
    - groupmanager.manudel
    inheritance:
    - vip
    info:
      prefix: '&5'
      build: true
      suffix: ''
  Vip:
    default: false
    permissions:
    - essentials.fireball
    - essentials.item
    - essentials.time
    - essentials.time.world
    - essentials.tp
    - essentials.tphere
    - essentials.tpo
    - essentials.tpohere
    inheritance:
    - habitant
    info:
      prefix: §9
      build: true
      suffix: ''
  Visiteur:
    default: true
    permissions:
    - essentials.help
    - essentials.helpop
    - essentials.list
    - essentials.motd
    - essentials.rules
    - essentials.spawn
    inheritance: []
    info:
      prefix: '&e'
      build: false
      suffix: ''
  Dieu:
    default: false
    permissions:
    - '*'
    inheritance:
    - demidieu
    info:
      prefix: '&4'
      build: true
      suffix: ''
"

**Comment by fullwall** [comment]
Acknowledged, still waiting on API stuff.
