### ISSUE TITLE
GUI for Quests with Spout

### ISSUE THREAD

**Issue by wassilij** [CitizensDev/Citizens#188]
```
Request
Could you make something with Spout?
Like a GUI for the Quests?

THAT WOULD BE AWESOME! :D
```

**Comment by jaseaman** [comment]
Spout Is Client Side, Unless Everybody on your server has spout then i doubt it would work.

**Comment by wassilij** [comment]
I know that its clientside oO I just ask if Citizienz could make the Quests with a GUI by using Spout.

**Comment by jaseaman** [comment]
I think i read somewhere on this issues page that they werent supporting it, can never be too sure though

**Comment by jaseaman** [comment]
No wait just read the devs and they are adding spout support, looks like its gonna be awesome for you :P
