### ISSUE TITLE
Gaurds AddFlag -g Doesn't work with PermissionsEX

### ISSUE THREAD

**Issue by kramcomposer** [CitizensDev/Citizens#189]
Gaurds AddFlag -g Doesn't work with PermissionsEX
Says I need to use permissionsBukkit for it to work. but your wiki says it should work with PermissionsEX
Also
When you download from citizensnpcs.net
The Citizens.jar is empty for both experimental and non experimental :(
Actualy.. all jars are null :(

**Comment by fullwall** [comment]
What this is saying is that it can't detect the Permissions plugin (assuming you're using a recent dev build). Try http://ci.citizensnpcs.net for the latest if the official site isn't working.

**Comment by kramcomposer** [comment]
Thanks for the quick reply
oddly im getting a timeout when I try to access http://ci.citizensnpcs.net
Tried multiple computers and IP's

**Comment by kramcomposer** [comment]
Also this is my server log when starting up concernign Citiziens

2011-09-28 01:13:28 [INFO] [Citizens] NPC types loaded: blacksmith, guard, trader, quester, wizard, healer
2011-09-28 01:13:28 [INFO] [Citizens] Permissions system found (PermissionsEx v1.14)
2011-09-28 01:13:28 [INFO] [Citizens] version [1.1] loaded.
2011-09-28 01:13:28 [INFO] [Citizens] Economy plugin found (iConomy v5)
2011-09-28 01:13:28 [INFO] Server permissions file permissions.yml is empty, ignoring it
2011-09-28 01:13:28 [INFO] Done (0.414s)! For help, type "help" or "?"
2011-09-28 01:13:28 [INFO] [Citizens] Loaded 0 NPCs.
2011-09-28 01:13:28 [INFO] [Citizens] Loaded 0 quests.
2011-09-28 01:13:28 [INFO] ControllerBlock: Loaded v4 d

**Comment by jaseaman** [comment]
Those are just info server messages, wont affect anything..

**Comment by quickclay** [comment]
I can confirm 404 errors at citizensnpcs.net when clicking download or changelog.

**Comment by quickclay** [comment]
I also have PEX though my guards will not attack anything with proper flags set and aggro mode confirmed.

**Comment by jaseaman** [comment]
http://ci.citizensnpcs.net/

I have the same problem, there is the website to download the devs

**Comment by kramcomposer** [comment]
need to stop closing the issues :P

I tried the latest dev build #216 and still getting the same issue with guards

**Comment by kramcomposer** [comment]
Okay, realized I did something wrong. Didn't copy the right file
So I can add the group flag now. But the Guard isn't attacking the group
Also
When a person attacks him, he takes damage, then becomes unresponsive to damage, and also won't follow me anymore (if set to body guard afterwards)

**Comment by jaseaman** [comment]
The guards at the momen seem to have a major issue, they will not attack if you have some sort of multi-world plugin installed as we figured out, I say test it without the other plugins also.

**Comment by fullwall** [comment]
Will be fixing the not targeting groups issue in a bit...
