### ISSUE TITLE
No NPC's working for others than OPs

### ISSUE THREAD

**Issue by warptwist** [CitizensDev/Citizens#198]
On CB#1185, with PEX 1.14 no user except OPs can trade/repair.

It has been working before, and I haven't installed/removed plugins.

Unfortunately there are no errors shown in the log.

This is all I have from the log concerning Citizens:

15:40:19 [INFO] [Citizens] NPC types loaded: trader, healer, wizard, guard, quester, blacksmith
15:40:21 [INFO] [Citizens] Permissions system found (PermissionsEx v1.14)
15:40:21 [INFO] [Citizens] version [1.1] loaded.
15:40:21 [INFO] [Citizens] Economy plugin found (Essentials v2.2)

**Comment by AssHater** [comment]
i got the repair blacksmith work for the user... using bukkit perm 1.2 with MC 1.8.1 and CB#1185 (tried with 1140something too)
but the trader are OPs only...

only used the following command for the blacksmith
            citizens.blacksmith.use.*: true

**Comment by fullwall** [comment]
Download newest dev build.
