### ISSUE TITLE
Citizens overides any text blocking on console.

### ISSUE THREAD

**Issue by quickclay** [CitizensDev/Citizens#199]
I had a plugin (IgnoreLogger) that blocked several repetitive console messages "Can't keep up", etc.  After installing Citizens, all those messages reappear and IgnoreLogger has stopped working.  Confirmed by uninstalling Citizens and all messages disapepared from Console. (I have about 10 different blocked console spam messages)
Citizens (dev build), PEX, CB 1185, IgnoreLogger 1.0

**Comment by fullwall** [comment]
Should be fixed in newest dev builds.
