### ISSUE TITLE
Citizens don't load my quests!

### ISSUE THREAD

**Issue by Dimbulas** [CitizensDev/Citizens#200]
I am using Citizens 1.1 (dev: #223) and Bukkit #1185:

When I start the server with this quests.yml:
http://pastebin.com/rtLicWcu
I get the following Error in Console:
http://pastebin.com/KrEzK3ru

Then if I join my server and create a Quester, I cannot assign a quest to him.
With blanc Quest file, I am getting no error.

**Comment by kris76** [comment]
Save your quests.yml in UTF-8 format
Perhaps you should enquote "" your messages
repeatable has been replaced by repeats
Look at this example :
http://www.megaupload.com/?d=OZD7073I

**Comment by fullwall** [comment]
Incorrect YAML, as kris stated.
