### ISSUE TITLE
Issue with OP only traders and illegal i have tried all of your options

### ISSUE THREAD

**Issue by honorbound** [CitizensDev/Citizens#204]
21:34:47 [WARNING] Task of 'Citizens' generated an exception
java.lang.IllegalArgumentException: n must be positive
        at java.util.Random.nextInt(Unknown Source)
        at net.citizensnpcs.resources.npclib.creatures.DefaultSpawner.getRandomI
nt(DefaultSpawner.java:84)
        at net.citizensnpcs.resources.npclib.creatures.DefaultSpawner.spawn(Defa
ultSpawner.java:37)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask.spawnCreatur
e(CreatureTask.java:48)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask.run(Creature
Task.java:40)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

its really starting to piss me off and i dont know what to do i tried all of your build and it keeps on happening.. I literally tried them all. Everytime i switch to not op i can not buy anything it just selects there ID.  

I use permissionsex and this is how it is set up i even gave member the citizens.admin node

groups:
    Default:
        default: true
        info:
            prefix: ''
            suffix: ''
            build: false
        inheritance:
    Member:
        default: false
        info:
            prefix: ''
            suffix: ''
            build: true
        inheritance:
            - Default
        permissions:
            - 'warpplugin.warp'
            - 'econplugin.basic._'
            - 'general.spawn._'
            - 'citizens.use.npctype'
            - 'citizens.blacksmith.use.repair'
            - 'citizens.use.trader'
            - 'essentials.warp'
            - 'essentials.warp.list'
            - 'essentials.warp'
            - 'essentials.balance'
            - 'essentials.home'
            - 'essentials.sethome'
            - 'essentials.signs.use.warp'
            - 'essentials.signs.use.free'
            - 'essentials.balancetop'
            - 'citizens.admin'
            - 'citizens.trader.use.trade'
    Moderator:
        default: false
        info:
            prefix: ''
            suffix: ''
            build: true
        inheritance:
            - Member
        permissions:
            - 'modplugin.ban'
            - 'modplugin.kick'
            - 'modplugin.unban'
    Admins:
        default: false
        info:
            prefix: ''
            suffix: ''
            build: true
        inheritance:
        permissions:
            - '*'

**Comment by fullwall** [comment]
Newest version fixes this.

**Comment by honorbound** [comment]
fullwall please check it out its still not working for some reason...
