### ISSUE TITLE
Suggestion for Quest creation

### ISSUE THREAD

**Issue by MikeGold** [CitizensDev/Citizens#206]
Could you please release on your wiki a sample of working quests.yml ? In the past I've used npcquester with uquest and old citizens which worked fine for me, but since citizens 1.1 it doesn't seem to work together at all. I've tried to use my old quests.yml with your plugin which ended up in a bunch of errors (most likely different way of scripting). So anyway, there is plenty of people like me which find out your wiki quest creation explanation a bit confusing. If you'd give us a simple code, like this: 

0:
  Name: Tutaj sie osiedle.
  Start_Info: Zmachalem sie szukajac dobrej gory. Pomoz mi nazbierac kamienia...
  Finish_Info: To powinno wystarczyc na poczatek!
  Rewards: 
    Money: 5000
  Objectives:
    0:
      Type: Block_Damage
      Display_Name: Przekopany kamien
      Objective_ID: 1
      Amount: 30
    1:
      Type: Gather
      Item:
        Item_ID: 4
        Display_Name: Kamienne bloki
        Amount: 30
        Durability: 0
1:
  Name: Mam mieszkac jak dzikus?
  Start_Info: Wiesz, ten kamien jest dobry, ale na dom, to trzebaby go wypalic...
  Finish_Info: Niech ci bozia w klockach wynagrodzi!
  Rewards:
    Money: 10000
  Objectives:
    0:
      Type: Gather
      Item:
        Item_ID: 1
        Display_Name: Wypalony kamien
        Amount: 30
        Durability: 0
2:
  Name: Rozjasnij moj swiat
  Start_Info: Moze i mam juz materialy na dom, ale nie mam pochodni...
  Finish_Info: Teraz bede bezpieczny!
  Rewards:
    Money: 10000
  Objectives:
    0:
      Type: Gather
      Item:
        Item_ID: 50
        Display_Name: Pochodnie
        Amount: 10
        Durability: 0

that would make our lifes much easier.

**Comment by ghost** [comment]
Jeah, nice idea! I need this too.

**Comment by Mrxxz0** [comment]
I'd really love this!

**Comment by kris76** [comment]
Try this
http://dl.dropbox.com/u/6701575/Citizens-test.zip

**Comment by kris76** [comment]
I use this one on my server, nearly all types are used :
http://www.megaupload.com/?d=OZD7073I

**Comment by ghost** [comment]
Thank you kris!
