### ISSUE TITLE
Location quest not working.

### ISSUE THREAD

**Issue by torolix** [CitizensDev/Citizens#208]
Hello, love your plugin so far, but i am having trouble making the location quest work, below is the code for the location: 

 objectives:
        '0':
            '0':
                type: move location
                location:
                    x: -293
                    y: 71
                    z: 43
                    world: world
                amount: 10
                message: <g> You have found the trial, complete it to earn the kings respect!

The quest and its npc loads without problems and i can also accept the quest, but i cannot complete it!
Why? Because for some reason the /quest status tells me im supposed to go to x:o y:o z:O (worldnull) How come it loads those locations instead of the ones i inputed? :)

**Comment by gjdawson** [comment]
I've just experienced this as well. Tried restarting the server to load everything fresh, but the problem persists.

**Comment by torolix** [comment]
Hmm, i have tried the same as you, both restarting, reloading and re-installing. Nothing seems to work. Can some dev try to shed some light on this please? :)

**Comment by kris76** [comment]
Which build do you use ? This is solved since b206.

**Comment by gjdawson** [comment]
I don't rightly know, but I assume it's the latest. I downloaded it from your bukkitdev page - and incidentally, the download from citizenspcs.net is completely non-functional. Inside the zip, what I assume is meant to be the Citizens subdirectory is a 0 byte file and the citizens.jar itself won't load.

**Comment by gjdawson** [comment]
Latest build fixed this, though it does seem to fail if you don't specify a world. Might just have been my configuration thouugh so, yeah, great job guys!
