### ISSUE TITLE
bPermissions 1.7.3 update broke traders (and possibly more NPC's)

### ISSUE THREAD

**Issue by remypas** [CitizensDev/Citizens#210]
Hi there, I'm back with the same issue again, I had it before. 
I use bPermission and gave all my players the citizens.trader.use.trade permission. but they were not able to use them.
You did an update back then and it started working. YAY
A nice economy was starting to grow on my survival world but then bPermissions did an update to 1.7.3 it broke for all my players again, except the OP's.

**Comment by fullwall** [comment]
Will update to newest version now.
