### ISSUE TITLE
You do not have permissions to do that error

### ISSUE THREAD

**Issue by soferal** [CitizensDev/Citizens#211]
Whenever i try to create a npc or do anything to do with npc the error you do not have permissions to do that pops up in red. I'm not sure what it is but when i op myself and try using the command it works! Plz tell me how to fix this cause i really want citizens on my server

**Comment by saiek** [comment]
im having the same problem

**Comment by saiek** [comment]
fixed with the new build http://ci.citizensnpcs.net/
