### ISSUE TITLE
Creating 2 NPCs with the same name makes them teleport into eachother

### ISSUE THREAD

**Issue by THDigi** [CitizensDev/Citizens#213]
It's like it says, if I create a "Innkeeper" npc somewhere then I create another "Innkeeper" npc in another inn, the other innkeeper teleports into the other one, but I can't really select it... if I delete the last created NPC (the only one I can select), the other one remains there unselectable.

The bug persists on server restart, if I load the chunk where the other NPC is at, it teleports to the latest created just visually, because if I select it using /npc select and then /npc tp, it teleports me to it's normal location, only that he's not there =)

Craftbukkit #1231
Citizens #229

**Comment by AssHater** [comment]
weird, i got 6 town guard with the same name, this bug isn't happening

have you tried the "/npc move" after selecting the guy?

**Comment by THDigi** [comment]
Yes, if I move either one of them, they both move... it's like they're glued together.

EDIT: ops @ closing =)

**Comment by fullwall** [comment]
Looks like a plugin conflict... Can you list your plugins?

**Comment by THDigi** [comment]
No need, I tested with only Citizens in the plugins folder and the bug persists, I created 2 npcs with the same name and they just glue eachother... maybe it's not a plugin conflict but a plugin lacking bug.

Oh, I also have all NPC types installed.

EDIT: pff, that comment & close button is really confusing and annoying...

**Comment by fullwall** [comment]
Really odd, I've never experienced this issue. Is it in a separate world?

**Comment by THDigi** [comment]
Nope, the only world on the server.

I even tried without spout client, maybe it was a visual effect, but no, the same thing with vanilla client.

**Comment by Jogeta** [comment]
i have had this exact problem since upgrading from 1.1

**Comment by Jogeta** [comment]
all npcs with the same name merge into one and cant be separated, also if you have a player with the same name as an npc this will happen.

**Comment by fullwall** [comment]
Looks like craftbukkit has changed something.

**Comment by fullwall** [comment]
Newest dev build fixes.
