### ISSUE TITLE
NPC Randomly Dissapearing

### ISSUE THREAD

**Issue by Mrxxz0** [CitizensDev/Citizens#215]
For some reason, the npcs just randomly dissapears. There is no error logs of it or anything, they just go unvisible or despawn.

Help would be greatly appreciated.
Regards, Mrxxz0

**Comment by Mrxxz0** [comment]
I can't confirm why, but I believe its because they are spawned at the spawn region.
The only npcs that despawns are those who are in the spawning region, so I believe thats why.

**Comment by fullwall** [comment]
Please download the newest dev build.
