### ISSUE TITLE
Groupmanager Permissions does not work?

### ISSUE THREAD

**Issue by Mrxxz0** [CitizensDev/Citizens#216]
Well, none of my npcs allows normal builders to do anything, except for the questers.
They can quest,accept and receive rewards without problems, but interacting with an npc does not work at all. (Wizard -> TIME)
Normal players can not even do /quest status or /quest abort even if I've given them the permission to do so.

(The NPCS also randomly despawns, but respawn after sertan ammount of time for some reason)
- Citizenz v1.1
- GroupManager (Yes, for 1185)
- CB 1185

Groups.yml
http://pastebin.com/SVFfSTn2

**Comment by Mrxxz0** [comment]
When I come to think about it, does the new update include Groupmanager as an economy system-option?

**Comment by fullwall** [comment]
Download the newest dev build to fix this.
