### ISSUE TITLE
Trader doesn't work. PermissionsEX. Op can use them, but not normal Users.

### ISSUE THREAD

**Issue by Kalerion** [CitizensDev/Citizens#217]
Hey, im using Bukkit CB 1185 with Citizens 1.1 and PermissionsEX 
Here are the Permissions i set:
        - citizens.use.trader
        - citizens.trader.use
        - citizens.use.trader.*
        - citizens.trader.use.*
        - citizens.basic.use.*
        - citizens.basic.use
        - citizens.trader.use.trade
How can i fix it? (I tried all variations of the permissions=

**Comment by AssHater** [comment]
you're not the only one with this issue.... this one is kinda pain in the arse...
i need to op everyone each and everytime someone want to use the traders.... and deop them afterward....
i got kids playing on my server, just waiting to be able to use the op commands to fuck everything up...
can we get a quick fix b4 my server get fucked by 10 years olds fags plz???

**Comment by fullwall** [comment]
Please download the newest dev builds to fix this issue.
