### ISSUE TITLE
Trader bugs Op only + a few requests

### ISSUE THREAD

**Issue by AssHater** [CitizensDev/Citizens#219]
First, I must say thanks for the pluggin, it's a fucking great one! We all love it over here, they do complain bout the blacksmith that cost too much but i don't mind much lol. I must say i tried Npcx first and the coding was so horrible that i stopped after 2 npc... Still, your guards could learn a thing or 2 from them... they seems... how can i say lacking agressiveness... in their pluggin, if you attack them, they rush at you like crasy and try to kill you with such a crasy bloodlust that they can win vs you with hand combat with no armor vs you in full plate with a diamond sword if you're not carefull. They also rush at the ennemy when they see it/them. All the npc in npcx can get attacked and attack back, i sadly find that lacking in citizens... (unless they are set to guard while being trader blacksmith or something else...) I mostly see the guards run around, going around a house 5 times in a row, trying to get to a spider b4 just giving up and going back to their spawn..... but enough about guards. 

Let's talk about Traders!!! I seriously love the system, it's crasy great. If you could just repair that OP needed to trade with them they would be almost perfect. A suggestion for a future update maybe, right clicking on the Trader, then right clicking on the item you want to set up for trade then just write the price you want to sell and/or the buying price instead of writing the command+sell/buy+code:number+sell/buy price each and everytime. Talking to the npc, saying something like b:30 200 after right clicking on the item would be much quicker... Just a though, don't know if you can actually do it without a database like SQL and i suck at coding....

Great job guys and keep up the good work, we all love your pluggin and we're all hoping you're gonna fix it soon ^^ (even if the update just came out)
Thanks again!

btw, i'm using CB 1185, superperm (permbukkit 1.2), iconomy6, npcx(not for much longer) Citizens 1.1, towny, lockette 1.4.4, wormholeXtreme 1.011... tried with only iconomy6 and citizens 1.1 to see if the OP bug was a conflict between other pluggins but we still had the problem so i turn the rest back on...
the only sad part is that i got kids playing on my server and i'm stuck with OPing them to let them use shop and DeOPing them right afterward.... (10 years old kiddos could scrap a server with OP command if left unwatched....
Any hope of a quick fix? (or a line that we could edit between now and your next release)
forgot to say, i tried having everyone have all the perms for the citizens pluggin and i was still unsuccessfull

**Comment by MadcowD** [comment]
Yeah I have that problem with permissions. The OP only problem. Also I can't even modify others NPCs even with the override owner permissions in Permissions Ex.
