### ISSUE TITLE
Trader suggestion: buying/selling full stacks

### ISSUE THREAD

**Issue by chomoli** [CitizensDev/Citizens#220]
Hi,

It would be nice if you could configure a trader to buy and sell full stacks of items. Trading raw materials like wood one block at a time takes way too long.

**Comment by AssHater** [comment]
actually you didn't read the wiki on it.... nor the /trader help...

/trader [buy or sell] [itemID:AMOUNT:data] [price]
let's say you want to sell item # 5 with trader you do this:
/trader sell 5:64 50
so he's now selling wood plank in pack of 64 only at 50$ the full 64 pack
now, you need to give him 64 plank so he can sell them and ether stack a lot on him or enable the unlimited by doing / trader unlimited
now if you can edit back those thing you did earlier with /trader [buy/sell] edit [itemID:AMOUNT:data] [price]

the only sucky thing with the traders right now are the OP status needed to trade with them....
didn't try but maybe it the pluggin can accept a higher number than 64 so you could sell 300 of them
i need to try this

**Comment by chomoli** [comment]
_FACEPALM_ I've read the wiki, article on traders (http://wiki.citizensnpcs.net/index.php?title=Trader) lists only the 
/trader buy/sell [item] [price] 
command. I didn't think there would be more options listed in /trader help. Thanks, that's great news for me - both the ability to set the amount and item data.
