### ISSUE TITLE
keep getting an error message with the trader in the console

### ISSUE THREAD

**Issue by tonyt387** [CitizensDev/Citizens#221]
i keep getting this weird error message when we try to set up a trader

02:06:38 [SEVERE] java.lang.NullPointerException
02:06:38 [SEVERE]   at net.citizensnpcs.economy.EconomyManager.format(EconomyManager.java:62)
02:06:38 [SEVERE]   at net.citizensnpcs.traders.TraderMessageUtils.getPriceMessage(TraderMessageUtils.java:13)
02:06:38 [SEVERE]   at net.citizensnpcs.traders.TraderMessageUtils.getStockableMessage(TraderMessageUtils.java:19)
02:06:38 [SEVERE]   at net.citizensnpcs.traders.TraderCommands.stock(TraderCommands.java:298)
02:06:38 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:06:38 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
02:06:38 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
02:06:38 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:597)
02:06:38 [SEVERE]   at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
02:06:38 [SEVERE]   at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
02:06:38 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
02:06:39 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
02:06:38 [SEVERE]   at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
02:06:39 [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
02:06:39 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
02:06:39 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
02:06:39 [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
02:06:39 [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
02:06:39 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
02:06:39 [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
02:06:39 [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
02:06:39 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
02:06:39 [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
02:06:39 [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
02:06:39 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
02:06:39 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
That means that no economy plugin is installed on the server or that Citizens couldn't detect one...

**Comment by tonyt387** [comment]
So do I need to setup an economy plugin for them to work

----- Reply message -----
From: "fullwall" reply@reply.github.com
To: "tonyt387" djtonyt387@yahoo.com
Subject: [Citizens] keep getting an error message with the trader in the console (#221)
Date: Mon, Oct 3, 2011 07:41

That means that no economy plugin is installed on the server or that Citizens couldn't detect one...

##

**Comment by tonyt387** [comment]
so do i need to setup an economy plugin for them to work

**Comment by tonyt387** [comment]
So does that mean that I need to setup an economy plugin for that to work

----- Reply message -----
From: "fullwall" reply@reply.github.com
To: "tonyt387" djtonyt387@yahoo.com
Subject: [Citizens] keep getting an error message with the trader in the console (#221)
Date: Mon, Oct 3, 2011 07:41

That means that no economy plugin is installed on the server or that Citizens couldn't detect one...

##

**Comment by fullwall** [comment]
Yes
