### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/collect/Iterables

### ISSUE THREAD

**Issue by Deathlysteve** [CitizensDev/Citizens#229]
I updated to 1.1, and it was working fine. now I updated to 1.1.1, and i try to make an NPC and it comes up with...
"Please report this error: [See console]
java.lang.NoClassDefFoundError: com/google/common/collect/Iterables"

It says report what is in console so here is what comes up in the console:

22:22:20 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
22:22:21 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
22:22:20 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
22:22:21 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
22:22:21 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
22:22:21 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
22:22:21 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
22:22:21 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
22:22:21 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
22:22:21 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
22:22:21 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)

> 22:22:21 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
> 22:22:21 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
> 22:22:21 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
> 22:22:21 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374
> 22:22:21 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
> 22:22:21 [SEVERE] Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Iterables
> 22:22:21 [SEVERE]       at java.net.URLClassLoader$1.run(Unknown Source)
> 22:22:21 [SEVERE]       at java.net.URLClassLoader$1.run(Unknown Source)
> 22:22:21 [SEVERE]       at java.security.AccessController.doPrivileged(Native Method)
> 22:22:21 [SEVERE]       at java.net.URLClassLoader.findClass(Unknown Source)
> 22:22:21 [SEVERE]       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
> 22:22:21 [SEVERE]       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
> 22:22:21 [SEVERE]       at java.lang.ClassLoader.loadClass(Unknown Source)
> 22:22:21 [SEVERE]       at java.lang.ClassLoader.loadClass(Unknown Source)
> 22:22:21 [SEVERE]       ... 17 more

After i saw this error with 1.1.1, I tried downgrading to 1.1 again, and now the Error wont go away -.- (the console error above is for when i did it in 1.1 after it came up in 1.1.1)

thanks

*EDIT: I forgot to add, my CB Build is 1240... maybe thats it. I will try to bring it back to 1185 and see if I get he error.

**Comment by Deathlysteve** [comment]
ok its the Craftbukkit update. I went back to 1185 and it works fine...

**Comment by fullwall** [comment]
Looks like the google guava update broke things... need to update.

**Comment by fullwall** [comment]
Should be fixed now.
