### ISSUE TITLE
Blacksmith permissions

### ISSUE THREAD

**Issue by phatchico** [CitizensDev/Citizens#230]
Just updated to 1.1.1 today and now have users complaining that they can't repair at the blacksmith anymore.  My permissions file has not changed and does not error out.  I am using permissions bukkit, the latest RB for Bukkit.  Here is what the permission line looks like:

```
        citizens.blacksmith.use.repair: true
```

Any help would be appreciated.  Thanks.

**Comment by fullwall** [comment]
Any errors in the server log?

**Comment by phatchico** [comment]
Not that I am seeing

**Comment by phatchico** [comment]
Ok just to be clear I am using RB 1185 not 1240 as I did not realize 1240 was out yet.  Does this make a difference?

**Comment by fullwall** [comment]
Shouldn't do.
