### ISSUE TITLE
End of Stream in Console

### ISSUE THREAD

**Issue by adambratt** [CitizensDev/Citizens#235]
I constantly get an "[INFO] Reached end of stream" since installing the Citizens plugin. After about 5 minutes of starting it shows up every 30 seconds or so. Sometimes 15 times in a row in less then a second.

I'm using v1.1.1 and my bukkit version is: Craftbukkit version git-Bukkit-0.0.0-1067-g6301507-b1185jnks (MC: 1.8.1)

**Comment by Fbkappa** [comment]
Same for me in version: Craftbukkit version git-Bukkit-0.0.0-1112-g54a13b2-b1240jnks (MC: 1.8.1)

I have this messages in console at the server start-up:
08:23:26 [INFO] Reached end of stream
08:23:26 [INFO] Reached end of stream
08:23:26 [INFO] Reached end of stream
08:23:26 [INFO] Reached end of stream
08:23:26 [INFO] Reached end of stream
08:23:26 [INFO] Reached end of stream
08:23:26 [INFO] Reached end of stream
08:23:26 [INFO] Reached end of stream

**Comment by jmschonfeld** [comment]
Same here. Please look at this link for info: https://github.com/CitizensDev/Citizens/issues/135
aPuch and fullwall have marked it as a bug there and are reviewing it there.

**Comment by fullwall** [comment]
Fixed in newest builds.

**Comment by jmschonfeld** [comment]
Fixed in RB #1240, or cit v1.1.2?
