### ISSUE TITLE
Trader's won't trade?

### ISSUE THREAD

**Issue by Duplex-xx** [CitizensDev/Citizens#236]
Using 1185 build of citizens.
I've stocked the trader with cooked_beef aka steak (/trader sell 364 2)

I'm not entirely sure i did this right, but anyhow, I can't get the trader to sell me steaks?
I've also set it up to buy diamond from me, he doesn't buy either.

i right click him and "stocking of Trader started" appears along with an inventory of the trader.
I've tried dragging and clicking steak/diamond back and forth but nothing happens. No msg, no withdrawal of cash, not anything.

Using iConomy 5.

**Comment by fullwall** [comment]
Because you're the owner, you can't trade with your trader. Instead, you are in stocking mode, which allows you to place items into his inventory. Try using /npc setowner to someone else and you'll be able to trade with him.

**Comment by Duplex-xx** [comment]
Aha, I guess i missed that part :-P Thanks alot for the reply!

fullwall reply@reply.github.com:
