### ISSUE TITLE
Unable to create NPC - build 237

### ISSUE THREAD

**Issue by toolbum** [CitizensDev/Citizens#237]
21:54:57 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
21:54:57 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
21:54:57 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
21:54:57 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)
21:54:57 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
21:54:57 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:54:57 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
21:54:57 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:54:57 [SEVERE]       at java.lang.reflect.Method.invoke(Method.java:601)
21:54:57 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
21:54:57 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
21:54:57 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
21:54:57 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
21:54:57 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
21:54:57 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
21:54:57 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
21:54:57 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
21:54:57 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
21:54:57 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
21:54:57 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
21:54:57 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
21:54:57 [SEVERE]       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
21:54:57 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
21:54:57 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
21:54:57 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
21:54:57 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Download a newer dev build.
