### ISSUE TITLE
I can't assign a quest to the rewards

### ISSUE THREAD

**Issue by laztheripper** [CitizensDev/Citizens#239]
it is written that you can create a quest and as a reward you could have another quest. I don't want my npc to give the player the 2nd quest when he first clicks on it and I like the way you said it would work. With the reward being the next level quest.

my quests go like this :

Tutorial:
    texts:
        description: Hi there! Would you go get me a compass at the shops?
        completion: Take these, they will be of great use.
        acceptance: <g>Challenge <y>accepted<g>.
    repeats: -1
    objectives:
        '0':
            '0':
                type: delivery
                materialid: 345
                npcdestination: 1
                amount: 1
                message: Thank you for giving me my compass !
    rewards:
        '0':
            type: item
            id: 364
            amount: 3
        '1':
            type: item
            id: 272
            amount: 1
        '3':
            type: item
            id: 274
            amount: 1
        '4':
            type: command
            command: tp <player> 478,116,-529
        '5':
            type: quest
            quest: Tutorial2
Tutorial2:
    texts:
        description: Hi there! Would you go get some logs?
        completion: Take these, they will be of great use.
        acceptance: <g>Challenge <y>accepted<g>.
    repeats: -1
    objectives:
        '0':
            '0':
                type: delivery
                materialid: 17
                npcdestination: 1
                amount: 10
                message: Thank you for giving me my logs !
    rewards:
        '0':
            type: item
            id: 364
            amount: 3

So, the way I have it now, the player first clicks npc 1 and receives "tutorial".. He then has to bring a compass to npc 1 and the npc will reward him with 3porkchops, a stone pick, a stone sword. Also, the player gets teleported to a nearby mountain and gets "tutorial2" quest as another reward. He then cuts a few logs and brings them to npc 1 to receive some more meat.

My problem here, is that when the player receives his "tutorial2" quest, it says "challenge accepted" but when I type /quest status it says I have no quest. I had a quick look and found that the quest had never been assigned to the player. This isn't such a big problem but I would like to at least have a heads up on how to set "tutorial" as a requirement for "tutorial2"

Aside from that, I have found the npc's absolutely charming and fully functionnal. Another detail that could help out : when trading with the trader, you can only sell (and buy) 1 by 1 (no bulk selling) and it's quite slow when I have a few hundred blocks to sell. I thoroughly enjoy this plugin, keep at it :) good job. 

EDIT \* Hello fullwall and thanks for telling me how to make a command get issued by the console but that "server: true" goes where? the lign after the command? I am trying to make a player get teleported somewhere after the quest without them ever having to have permission for it. I can make the console issue a give command to the player but not /tp player x,y,z . After an hour of playing with this, i found out that I can't make the console issue commands that need to be issued by players like "tp" and "npc tp" so, maybe you could add a teleport reward with x,y,z coordinates? that would be   awesome!

-LAZ

**Comment by HornikHonza** [comment]
Hello, i have the same problem. But the day before yesterday it worked fine, I made it the same way u described and chain of 3 quests worked fine. But it doesnt anymore, saying challenge accpeted, but no quests under quest status. I supose its some sort of bug in new version.

Otherwise its really awesomestable plugin.. works superbly and options to make quests ale very rich. Much better than citizens - npcquester - uquest plugins set we had to use months ago.. that really was a fragile construction :)

**Comment by fullwall** [comment]
Quest rewards are fixed in newer builds. server: true goes anywhere as long as it is under the same number as the commands reward. Teleport reward sounds like a good idea.

**Comment by laztheripper** [comment]
Thanks for the feedback :)
I got the node down, thanks for clarifying it though. Happy you like the suggestion.
also, If you want, I would love for you to see your npc's used for the best in my server, we have made a nice storyline with many quests and hunts to go along with it. If you don't have time, it's okay.
