### ISSUE TITLE
Trader's won't sell Piston and Sticky Piston

### ISSUE THREAD

**Issue by Fbkappa** [CitizensDev/Citizens#240]
I have set up a trader to sell:
Redstone, Redstone Torch, Redstone Repeater, Piston, Sticky Piston, Levers and Buttons

if i use the command:
/trader list sell
all seems to be ok.
I can buy everithing except Piston and Stiky Piston.

This is the config for the npc:

'2':
    basic:
        look-when-close: 'true'
        location: world,-790.1875,69.0,553.5,264.99887,0.0
        items: 0:0,0:0,0:0,0:0,0:0,
        color: '15'
        inventory: 76/32/0,AIR_1,331/64/0,AIR_1,356/8/0,356/8/0,AIR_1,33/10/7,29/5/7,76/32/0,AIR_1,331/64/0,AIR_1,356/8/0,356/8/0,AIR_1,33/10/7,29/5/7,AIR_4,356/8/0,356/8/0,AIR_1,33/10/7,29/5/7,77/10/0,AIR_1,69/10/0,AIR_1,356/8/0,356/8/0,AIR*1,33/10/7,29/5/7,
        name: Test/Trader
        owner: asd
        talk-when-close: 'false'
    trader:
        balance: '30920.0'
        toggle: 'true'
        stock: 76/32/0/,640.0,false,;69/10/0/,60.0,false,;33/10/0/,900.0,false,;77/10/0/,200.0,false,;29/5/0/,1850.0,false,;331/64/0/,960.0,false,;356/8/0/,720.0,false,
        unlimited: 'true'

Any suggestion?

**Comment by fullwall** [comment]
What happens when you try to buy sticky pistons?

**Comment by Fbkappa** [comment]
Return this chat message:

Piston Sticky Base isn't being sold here.

**Comment by Fbkappa** [comment]
Any news?
Is anyone have the same issue?

**Comment by fullwall** [comment]
Piston Sticky Base probably means that the ID you've added is likely not the correct one. Piston Sticky Base is ID 29.

**Comment by Fbkappa** [comment]
On my previous post i have added the base config of my npc:

stock: 76/32/0/,640.0,false,;69/10/0/,60.0,false,;33/10/0/,900.0,false,;77/10/0/,200.0,false,;29/5/0/,1850.0,false,;331/64/0/,960.0,false,;356/8/0/,720.0,false,

..and is easy to see the ID 29:
29/5/0/,1850.0,false,

so i don't think that your solution can solve my problem.
Anyway thanks.

**Comment by sizilium** [comment]
I have exactly the same issue.
"/trader sell 29 40" does not help.
Trader is not able to buy or sell Piston and/or Sticky Piston !
