### ISSUE TITLE
Error when creating NPC in 1.1.2

### ISSUE THREAD

**Issue by rustybullets** [CitizensDev/Citizens#242]
When creating an NPC I get the following error in the console:

08:41:58 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
08:41:58 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
08:41:58 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
08:41:58 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)
08:41:58 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
08:41:58 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:41:58 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
08:41:58 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:41:58 [SEVERE]       at java.lang.reflect.Method.invoke(Method.java:616)
08:41:58 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
08:41:58 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
08:41:58 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
08:41:58 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
08:41:58 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
08:41:58 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
08:41:58 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
08:41:58 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
08:41:58 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
08:41:58 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
08:41:58 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
08:41:58 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
08:41:58 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
08:41:58 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
08:41:58 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
08:41:58 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

The screen does say "Paid 100 dollars for xxxxx", but no NPC is created, obviously.

**Comment by MacGruber** [comment]
Same with me :/

**Comment by snitride** [comment]
Hello everyone get same error here, 

first, here a list of plugins i am running on my Minecraft 1.8 Beta Server: Permissions 3.1.6 (Yeti) iConomy 6.0.7 ChestShop 3.22 Citizen 1.1.2

Server starts up with no Errors, but if i try to create a npc in Game i get following Errors. http://pastebin.com/N60bEWxz I guess it's a plugin conflicting with citizen, any information or guesses, would help a lot. 

Thanks in advance...

Update:
Unloaded ChestShop and Permissions, still same error... so it only can be iConomy 6.0.7 ?

**Comment by mrgiggles211** [comment]
I had the same error, once i updated my bukkit build every thing worked fine. so i recommend trying that

**Comment by rustybullets** [comment]
I am running CB #1185.  Do I need to go up to build #1240?

**Comment by mrgiggles211** [comment]
yup, i went to 1240 and every thing worked perfectly

**Comment by fullwall** [comment]
Update to #1240 if using 1.1.2
