### ISSUE TITLE
NPC Location Management issue

### ISSUE THREAD

**Issue by SamuraiKal** [CitizensDev/Citizens#245]
It seems like the NPC location management has changed from unique ID's to the name of the NPC.  Now I can't make NPC's with duplicate names as they try to occupy the same space, and any NPC's named after a player follow that player around.  Can you please change the location management back to using unique ID's?

I'm using Bukkit 1240 and Citizens 1.1.2.

**Comment by ghost** [comment]
Hello !

I have the exact same issue !

Bukkit #1240, Citizens 1.1.2 #242, and my own NPC is trying to take my place (bad NPC, bad !) :P

**Comment by SamuraiKal** [comment]
Just updated to the most recent dev build (247) and problem seems to be resolved.  From the changes, it looks like this was resolved with the 246 build (NPCSpawner.java)

**Comment by SamuraiKal** [comment]
p.s. Thanks for the quick resolution, you guys rock!
