### ISSUE TITLE
Lapis Lazuri is Ink Sack?

### ISSUE THREAD

**Issue by Deathlysteve** [CitizensDev/Citizens#248]
When I make a trader and make him sell Lapis Lazuri, any other type of dye, Coloured wool or basically annything that has a... I think its Hex value? im sorry i forgot what its called but basically every item with subscript numbers in this picture http://www.minecraftwiki.net/images/3/33/ItemslistV110.png

(sorry i just forgot what its called)

anyway, Its really annoying because im trying to sell Lapis lazuri and it keeps saying its an Ink Sack, which always confuses the player buying...
if its possible please fix this soon... thanks

**Comment by fullwall** [comment]
Using the syntax id:amount:data should fix this, reopen if not.

**Comment by Deathlysteve** [comment]
1. Ive always done that, and it still calls Lapis Lazuri an Ink Sack (even try it for yourself)
2. It says i dont have permission to Reopen the issue

yeah even try it for yourself...

**Comment by fullwall** [comment]
Oh I see... this is tough to fix, since Bukkit itself does not support lapis lazuli naming...

**Comment by Deathlysteve** [comment]
fair enough, but it would be heaps awesome if u like got it working.... even in like the 2.0 version itd be awesome :)
