### ISSUE TITLE
Quest Help.

### ISSUE THREAD

**Issue by PopeXIII** [CitizensDev/Citizens#249]
I've looked the internet over, Im no .YML creater, I do mod them I can pretty much understand that. But If Anyone could create a .yml file that explains like how a Quest is formated or a small example of like a pvp, gather or delievery or somthing 1 or 2 examples please!!!! Any assistnace or website or somthing! Thank You! The Wiki explains a little bit, but not in depth due to no "example" or "example2" any where to be found :(

**Comment by Duplex-xx** [comment]
http://pastebin.com/0W5hTjUV

**Comment by PopeXIII** [comment]
This was really helpful... And with a soultion comes more problems... I edited the file a little bit, saved it as quests.yml, put the file in the plugins/citizens folder, go in game and zilch..... Cant load the file still says no quests avaliable.

**Comment by PopeXIII** [comment]
Okay.. I was trying to simply reload citizens and I have plugman so I was trying to just reload it.... ERRTTT Wrong, you must restart server completely!!!! I now have 3 test quests!!!!

Anyone having problems creating quests follow the link above, save the file as "quests.yml" after editing, then place it in, plugins/citizens and reboot server... Worked for me :D

**Comment by Duplex-xx** [comment]
did you target npc and: /quester assign [questname] ?
