### ISSUE TITLE
Finish Wiki Pages

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#25]
http://www.citizensnpcs.net/
Complete wiki that is linked from here; Individual type pages are not finished and API page.

**Comment by aPunch** [comment]
Can't forget to finish the Configuration page as well, aPunch!!!

**Comment by aPunch** [comment]
Still need some docs on questers/traders and then we are done! :D

**Comment by nexitem** [comment]
also waypoints.... cause im confused by them right now.
