### ISSUE TITLE
Quest rewards

### ISSUE THREAD

**Issue by Duplex-xx** [CitizensDev/Citizens#251]
Running Citizens 1.1.2 on Bukkit build 1240.
I can't seem to recieve any rewards (money or items) when turning in quests.
Did I do something wrong here? 

Quest1:
     texts:
          description: A mob quest - kill any 5 of Zombie, Skeleton or Creeper.
          completion: <g>Quest complete!
          acceptance: <g>Challenge <y>accepted<g>.
     repeats: 5
     objectives:
          '0':
              '0':
                  type: hunt
                  string: 'zombie, skeleton, creeper'
                  amount: 5
                  message: \o/ Monsters slain, return to questgiver \o/.
     rewards:
          '0':
             type: money
             amount: 100
             take: false

Quest2:
     texts:
          description: A fetch quest - Gather 15 Leaves.
          completion: <g>Quest complete! Thank you!
          acceptance: <g>Challange <y>accepted<g>.
     repeats: 3
     objectives:
         '0':
             '0':
                 type: collect
                 materialid: 18
                 amount: 15
                 message: A voice echoes... "I want those leaves now!"
     rewards:
          '0':
             type: item
             id: 89
             amount: 20
             take: true

**Comment by hiro24** [comment]
Change amount: 100 to money: 100 to fix money reward.. for the item rewards, take must be false, otherwise it tries to "take" those items from you.  You use take: true if the quest is to turn in that item.

(had the same problem) :)

**Comment by Duplex-xx** [comment]
Aha, thanks for the tip! :-) 

hiro24 reply@reply.github.com:
