### ISSUE TITLE
Help Error

### ISSUE THREAD

**Issue by entelieb** [CitizensDev/Citizens#255]
Hello all,
sry for my bad english i am german=)
i have deownloaded citizens from the main site its the version 1.1.2 and every time i will create a npc i got this problem:

] 4.670412174795498, 69.0, 362.59611040051186)
23:00:44 [INFO] New max size: 484
23:00:44 [INFO] New max size: 784
23:00:54 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldM
anager.<init>(Lnet/minecraft/server/WorldServer;)V
23:00:54 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC
(NPCSpawner.java:31)
23:00:54 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register
(NPCManager.java:164)
23:00:54 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register
(NPCManager.java:193)
23:00:54 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicC
ommands.java:226)
23:00:54 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
23:00:54 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
23:00:54 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
23:00:54 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
23:00:54 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
uteMethod(CommandsManager.java:522)
23:00:54 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
ute(CommandsManager.java:406)
23:00:54 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:202
)
23:00:54 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:39)
23:00:54 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:163)
23:00:54 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:353)
23:00:54 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(N
etServerHandler.java:756)
23:00:54 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:721)
23:00:54 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:714)
23:00:54 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:3
3)
23:00:54 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:226)
23:00:54 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:92)
23:00:54 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile
:108)
23:00:54 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServe
r.java:464)
23:00:54 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:374)
23:00:54 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:417)

Please when someone can help me do this thx=)

**Comment by fullwall** [comment]
Download RB #1240
