### ISSUE TITLE
An NPC with your name auto follows you

### ISSUE THREAD

**Issue by ElgarL** [CitizensDev/Citizens#259]
As the title says. I haev a bunch of NPC. All names the same as the server admins.
They are setup as traders, blacksmith and a wizard.

As soon as the player of that name logs in the NPC teleports to them and starts following them.

I even changed enable-following: false in the citizens.yml, but nothign stops them following the player.

Citizens 1.1.2 with CB 1240

**Comment by fullwall** [comment]
Fixed in newer builds, sorry, CraftBukkit workaround wasn't complete.
