### ISSUE TITLE
NPCs have unselectable duplicates on reload. (Fixed on logout)

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#26]
Vital Points of information:

Happens ONLY on reload.
It creates ONE new NPC at the position of the real one, EVERY reload.
The unselectable duplicates are effected by the NPCSpawnEvent, however the real one is NOT.
The duplicate does NOT look at the player, however the real NPC DOES.
If you alter the real NPC in any way, the duplicates remain in their created state!
NPC Remove All command only removes the real NPCs, these are removed on citizens clean and logout, or restarting the server.
Creature NPCs could NOT possibly cause this issue, I removed them all completely to test.

Citizens clean then logout, fixes this issue, until another reload creates a whole bunch more of them.
Citizens reload does NOT cause this issue, which narrows down the search.

^ This is quite annoying and might be difficult to trace.

**Comment by fullwall** [comment]
Probably caused by not properly despawning on disables.

**Comment by aPunch** [comment]
Could you test if this still happens with the latest build?

**Comment by mbsuperstar1** [comment]
This still happens...without fail...every single reload.

This makes it really difficult to test while updating builds...as when you reload there are 2 NPCs, one which makes the real one hard to select. (I always have to use the command)

**Comment by mbsuperstar1** [comment]
ITS SPOUT!! SPOUT PLUGIN DAMNIT!! ARGH

**Comment by efstajas** [comment]
Happens to me without Spout.

**Comment by mbsuperstar1** [comment]
This is the spout plugin, the client mod doesn't affect it, this is the latest builds of both.

**Comment by efstajas** [comment]
Why does it happen to me without Spout then...

**Comment by aPunch** [comment]
efstajas: Provide a detailed list of steps to how you get duplicated NPCs. Detailed.

**Comment by mbsuperstar1** [comment]
It appears EITHER the plugin OR the client mod affect it.
