### ISSUE TITLE
Can't create NPC (full error message)

### ISSUE THREAD

**Issue by pabloalbrecht** [CitizensDev/Citizens#270]
When I try to create an NPC on a fresh installation with enough money and all the permissions, I get the following message from console :

15:58:58 [INFO] [bPermissions] Setup world:EditWorld_0
15:58:58 [INFO] [bPermissions] Setup world:EditWorld_1
15:58:58 [INFO] Permissions reloaded.
15:59:04 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
15:59:04 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
15:59:04 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
15:59:04 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)
15:59:04 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
15:59:04 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:59:04 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
15:59:04 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:59:04 [SEVERE]       at java.lang.reflect.Method.invoke(Method.java:616)
15:59:04 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
15:59:04 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
15:59:04 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
15:59:04 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
15:59:04 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
15:59:04 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
15:59:04 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
15:59:04 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
15:59:04 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
15:59:04 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
15:59:04 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
15:59:04 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
15:59:04 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
15:59:04 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
15:59:04 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
15:59:04 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
15:59:12 [INFO] [iConomy] hooked into Permissions.

and something way shorter in game that says I have to read the console.

Please help. I've tried installing the plugin two time and I have only a few plugins such as iConomy and bPermissions, nothing fancy that would have interacted with Citizens.

**Comment by fullwall** [comment]
Incorrect CraftBukkit RB for the Citizens version you're using.
