### ISSUE TITLE
Can't Create NPC (Error Code)

### ISSUE THREAD

**Issue by MinecraftBaseHD** [CitizensDev/Citizens#273]
161 recipes
17 achievements
21:10:26 [INFORMATION] Starting minecraft server version Beta 1.8.1
21:10:26 [INFORMATION] Loading properties
21:10:26 [INFORMATION] Starting Minecraft server on 5.54.229.59:25565
21:10:26 [INFORMATION] This server is running Craftbukkit version git-Bukkit-0.0
.0-1067-g6301507-b1185jnks (MC: 1.8.1)
21:10:27 [INFORMATION] Preparing level "world"
21:10:27 [INFORMATION] Default game type: 0
21:10:27 [INFORMATION] Preparing start region for level 0 (Seed: 551619430692791
6356)
21:10:27 [INFORMATION] Preparing start region for level 1 (Seed: 551619430692791
6356)
21:10:28 [INFORMATION] Preparing spawn area: 81%
21:10:28 [INFORMATION] CommandBook 1.6-customized enabled.
21:10:28 [SCHWERWIEGEND] CommandBook: Unable to read default configuration: conf
ig.yml
21:10:28 [SCHWERWIEGEND] CommandBook: Unable to read default configuration: kits
.txt
21:10:28 [WARNUNG] CommandBook: 0 Warps(s) loaded
21:10:28 [WARNUNG] CommandBook: 0 Homes(s) loaded
21:10:28 [INFORMATION] CommandBook: Maximum wrapper compatibility is enabled. So
me features have been disabled to be compatible with poorly written server wrapp
ers.
21:10:28 [INFORMATION] CommandBook: 3 banned name(s) loaded.
21:10:28 [INFORMATION] CommandBook: Using the Bukkit Permissions API.
21:10:28 [INFORMATION] [CookieMonster]  v1.6.5 loaded successfully.
21:10:28 [INFORMATION] [CookieMonster]  Developed by: [jascotty2, Coelho]
21:10:28 [INFORMATION] [CookieMonster] Using iConomy v6 for economy
21:10:28 [INFORMATION] GroupManager - INFO - Superperms support enabled.
21:10:28 [INFORMATION] GroupManager - INFO - Scheduled Data Saving is set for ev
ery 10 minutes!
21:10:28 [INFORMATION] GroupManager version 1.2 (Phoenix) is enabled!
21:10:28 [INFORMATION] [FalseBook Block] 3100 Books loaded!
21:10:28 [INFORMATION] FalseBookBlock v0.88alpha by GeMo enabled
21:10:28 [INFORMATION] [FalseBook Block] 2 Cauldrons successfully loaded.
21:10:28 [INFORMATION] FalseBookCart v0.88alpha by GeMo enabled
21:10:28 [INFORMATION] [FalseBook Chat] 0 ChatRooms loaded.
21:10:28 [INFORMATION] FalseBookChat v0.88alpha by GeMo enabled
21:10:28 [INFORMATION] [FalseBook Core] FalseBookCore v0.88alpha by GeMo enabled
!
21:10:28 [INFORMATION] FalseBookExtra v0.88alpha by GeMo enabled
21:10:28 [INFORMATION] FalseBookIC v0.88alpha by GeMo enabled
21:10:28 [INFO] [iConomy - Celty] Enabled (46 ms)
21:10:28 [SEVERE] Exception in thread "Thread-7"
21:10:28 [SEVERE] java.lang.ClassCastException: java.util.LinkedHashMap cannot b
e cast to java.lang.Long
21:10:28 [SEVERE]       at com.iCo6.Constants$Nodes.getLong(Constants.java:111)
21:10:28 [SEVERE]       at com.iCo6.iConomy$1.run(iConomy.java:233)
21:10:28 [INFO] SimpleSignEdit v1.8 enabled.
21:10:28 [SEVERE]       at com.iCo6.util.Thrun.run(Thrun.java:12)
21:10:28 [INFO] [SimpleSignEdit] Checking for table...
21:10:28 [INFO] [SimpleSignEdit] Table found! (Error code was SQL:2003 SQLState:
 null; feel free to post this line on the forum as it may help me improve the pl
ugin; however, this is not a bug)
21:10:28 [INFO] WorldEdit 4.7 enabled.
21:10:28 [SEVERE] WorldEdit: Unable to read default configuration: config.yml
21:10:28 [INFO] WorldEdit: Using the Bukkit Permissions API.
21:10:28 [INFO] WorldGuard: Using the Bukkit Permissions API.
21:10:28 [SEVERE] WorldGuard: Unable to read default configuration: blacklist.tx
t
21:10:29 [WARNING] WorldGuard blacklist does not exist.
21:10:29 [INFO] WorldGuard: (world) Single session is enforced.
21:10:29 [INFO] WorldGuard: (world) TNT ignition is PERMITTED.
21:10:29 [INFO] WorldGuard: (world) Lighters are PERMITTED.
21:10:29 [INFO] WorldGuard: (world) Lava fire is blocked.
21:10:29 [INFO] WorldGuard: (world) All fire spread is disabled.
21:10:29 [INFO] WorldGuard: Loaded configuration for world 'world"
21:10:29 [SEVERE] WorldGuard: Unable to read default configuration: blacklist.tx
t
21:10:29 [WARNING] WorldGuard blacklist does not exist.
21:10:29 [INFO] WorldGuard: (world_nether) Single session is enforced.
21:10:29 [INFO] WorldGuard: (world_nether) TNT ignition is PERMITTED.
21:10:29 [INFO] WorldGuard: (world_nether) Lighters are PERMITTED.
21:10:29 [INFO] WorldGuard: (world_nether) Lava fire is blocked.
21:10:29 [INFO] WorldGuard: (world_nether) All fire spread is disabled.
21:10:29 [INFO] WorldGuard: Loaded configuration for world 'world_nether"
21:10:29 [INFO] WorldGuard: 0 regions loaded for 'world'
21:10:29 [INFO] WorldGuard: 0 regions loaded for 'world_nether'
21:10:29 [INFO] WorldGuard 5.3 enabled.
21:10:29 [INFO] [Citizens] No NPC types loaded.
21:10:29 [INFO] [Citizens] Permissions system found (GroupManager v1.2 (Phoenix)
)
21:10:29 [INFO] [Citizens] version [1.1.2] loaded.
21:10:29 [INFO] [Citizens] Economy plugin found (iConomy v6)
21:10:29 [INFO] [Factions v1.5.1] === ENABLE START ===
21:10:29 [INFO] [Factions v1.5.1] Loading conf from disk
21:10:29 [INFO] [Factions v1.5.1] Loading players from disk
21:10:29 [INFO] [Factions v1.5.1] Loading factions from disk
21:10:29 [INFO] [Factions v1.5.1] Loading board from disk
21:10:29 [INFO] [Factions v1.5.1] Permissions plugin not detected, defaulting to
 Bukkit superperms system
21:10:29 [INFO] [Factions v1.5.1] === ENABLE DONE (Took 99ms) ===
21:10:29 [INFO] Server permissions file permissions.yml is empty, ignoring it
21:10:29 [INFO] Done (0.222s)! For help, type "help" or "?"
21:10:29 [INFO] [FalseBook Block] 0 Bridges successfully loaded.
21:10:29 [INFO] [FalseBook Block] 0 Doors successfully loaded.
21:10:29 [INFO] [FalseBook Block] 68 protected gateblocks successfully loaded.
21:10:29 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet
/minecraft/server/WorldServer;)V
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java
:31)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java
:164)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
21:10:29 [INFO] GroupManager - INFO - Bukkit Permissions Updated!
21:10:32 [INFO] [FalseBook IC] Loaded selftriggered ICs: 0 done
21:10:32 [INFO] [FalseBook IC] Loaded selftriggered ICs: 0 failed
21:10:40 [INFO] Halfdream [/5.54.229.59:49808] logged in with entity id 177 at (
[world] -261.2118524888295, 66.0, -156.5438356802073)
21:10:41 [INFO] New max size: 484
21:10:41 [INFO] New max size: 784
21:11:00 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldM
anager.<init>(Lnet/minecraft/server/WorldServer;)V
21:11:00 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC
(NPCSpawner.java:31)
21:11:00 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register
(NPCManager.java:164)
21:11:00 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register
(NPCManager.java:193)
21:11:00 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicC
ommands.java:226)
21:11:00 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
21:11:00 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
21:11:00 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
21:11:00 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
21:11:00 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
uteMethod(CommandsManager.java:522)
21:11:00 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
ute(CommandsManager.java:406)
21:11:00 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:202
)
21:11:00 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:39)
21:11:00 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:163)
21:11:00 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:353)
21:11:00 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(N
etServerHandler.java:756)
21:11:00 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:721)
21:11:00 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:714)
21:11:00 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:3
3)
21:11:00 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:226)
21:11:00 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:92)
21:11:00 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile
:108)
21:11:00 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServe
r.java:464)
21:11:00 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:374)
21:11:00 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:417)

**Comment by MinecraftBaseHD** [comment]
need answer pls

**Comment by fullwall** [comment]
Incorrect craftbukkit RB for your Citizens version.
