### ISSUE TITLE
Configuration Changes Discarded

### ISSUE THREAD

**Issue by mjhasbach** [CitizensDev/Citizens#281]
Citizens configuration changes made outside of Minecraft (e.g. editing npc-profiles.yml in a text editor) are discarded upon /citizens save and /citizens reload.

Steps to reproduce:

1a. Open npc-profiles.yml in a text editor, make changes, and save.
1b. Perform /citizens save
1c. Open npc-profiles.yml in a text editor and realize that your new changes have been discarded.

2a. Open npc-profiles.yml in a text editor, make changes, and save.
2b. Perform /citizens reload
2c. Open npc-profiles.yml in a text editor and realize that your new changes have been discarded.

**Comment by Xaladon** [comment]
I had this issue as well, made a ticket about it and shortly after managed to 'fix' it. Stop your server, edit the file and then start the server again.

**Comment by mjhasbach** [comment]
Xaladon, that is how I managed to manually edit my file. Unfortunately, this is not much of a solution for a production server. I'm trying to reduce the number of times I have to reboot/stop my server...

**Comment by mbsuperstar1** [comment]
It'd be nice if there was a /citizen disable and /citizen enable. It can't destroy changes if it's not on xD
