### ISSUE TITLE
I dont know whats happening

### ISSUE THREAD

**Issue by 09090ness** [CitizensDev/Citizens#282]
I have 2 servers, one creative and one survival. On my survival one, this plugin works great. But on my creative one, whenever i try to create one i get this:  

18:24:10 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
18:24:24 [INFO] 09090ness [/192.168.1.154:56753] logged in with entity id 127 at ([world] -263.03125, 74.9375, 935.0)
18:24:25 [INFO] New max size: 484
18:24:25 [INFO] New max size: 784
18:24:29 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
18:24:29 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
18:24:29 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
18:24:29 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)
18:24:29 [SEVERE]   at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
18:24:29 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:24:29 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
18:24:29 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
18:24:29 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:597)
18:24:29 [SEVERE]   at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
18:24:29 [SEVERE]   at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
18:24:29 [SEVERE]   at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
18:24:29 [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
18:24:29 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
18:24:29 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
18:24:29 [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
18:24:29 [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
18:24:29 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
18:24:29 [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
18:24:29 [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
18:24:29 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
18:24:29 [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
18:24:29 [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
18:24:29 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
18:24:29 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

What does that mean? And also, everything else works fine. When i do /npc help it works fine, the thing shows up and everything. Its just creating an npc. So please help!

**Comment by fullwall** [comment]
You're using an incorrect RB for your Citizens version. 1.1.2 only works with #1240, and 1.1.1 does not work with #1240
