### ISSUE TITLE
Citizens wont load at all!

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#285]
when i start the server (of course, the .jar and folder are place in /plugins) it loads all the plugins, and when i check in Pail Server Manager is shows all the plugins i have, but Citizens isnt there..
its as if it doesnt exist in the /plugins folder..
any ideas?

**Comment by Hellant** [comment]
I am a bit further...

so far the same:
just downloaded citizens fresh from website (http://citizensnpcs.net/) with NPCs and doesn't load at all.
also just put jar file in plugin folder and nothing happens. Doesn't create default files.

BUT....

when i download the Jar file from this page from Code section... 
(https://github.com/CitizensDev/Citizens/blob/master/releases/Citizens.jar)
... then it creates the default settings files and all looks good...

10:39 PM [INFO] [Citizens] No NPC types loaded. 
10:39 PM [INFO] [Citizens] Creating new config file at plugins/Citizens/npc-profiles.yml. 
10:39 PM [INFO] [Citizens] Creating new config file at plugins/Citizens/citizens.yml. 
10:39 PM [INFO] [Citizens] Creating new config file at plugins/Citizens/mobs.yml. 
10:39 PM [INFO] [Citizens] Writing default setting ticks.pathing.max-stationary. 
10:39 PM [INFO] [Citizens] Writing default setting ticks.pathing.max-pathing. 
10:39 PM [INFO] [Citizens] Writing default setting ticks.saving.delay. 
10:39 PM [INFO] [Citizens] Writing default setting ticks.waypoints.right-click-pause. 
10:39 PM [INFO] [Citizens] Writing default setting range.look. 
10:39 PM [INFO] [Citizens] Writing default setting general.chat.format. 
10:39 PM [INFO] [Citizens] Writing default setting general.chat.default-text. 
10:39 PM [INFO] [Citizens] Writing default setting general.colors.npc-colour. 
10:39 PM [INFO] [Citizens] Writing default setting items.talk-items. 
10:39 PM [INFO] [Citizens] Writing default setting items.select-items. 
10:39 PM [INFO] [Citizens] Writing default setting general.chat.selection-message. 
10:39 PM [INFO] [Citizens] Writing default setting general.chat.creation-message. 
10:39 PM [INFO] [Citizens] Writing default setting general.chat.space-char. 
10:39 PM [INFO] [Citizens] Writing default setting general.defaults.enable-following. 
10:39 PM [INFO] [Citizens] Writing default setting ticks.saving.save-often. 
10:39 PM [INFO] [Citizens] Writing default setting general.colors.use-npc-colours. 
10:39 PM [INFO] [Citizens] Writing default setting ticks.saving.use-task. 
10:39 PM [INFO] [Citizens] Writing default setting general.quick-select. 
10:39 PM [INFO] [Citizens] Writing default setting debug.debug-mode. 
10:39 PM [INFO] [Citizens] Writing default setting general.notify-updates. 
10:39 PM [INFO] CButD: CraftBukkit is up to Date 
10:39 PM [INFO] [Citizens] Writing default setting general.defaults.talk-when-close. 
10:39 PM [INFO] [Citizens] Writing default setting general.pvp.deny.attack-disabled-pvp-players. 
10:39 PM [INFO] [Citizens] Writing default setting range.pathfinding. 
10:39 PM [INFO] [Citizens] Writing default setting economy.use-economy. 
10:39 PM [INFO] [Citizens] Writing default setting economy.prices.basic.creation. 
10:39 PM [INFO] [Citizens] Writing default setting debug.enable-error-reporting. 
10:39 PM [INFO] [Citizens] Writing default setting debug.error-reporting-ident. 
10:39 PM [INFO] [Citizens] Writing default setting general.spawn.delay. 
10:39 PM [INFO] [Citizens] Writing default setting evil.items.tame-item. 
10:39 PM [INFO] [Citizens] Writing default setting evil.misc.tame-chance. 
10:39 PM [INFO] [Citizens] Writing default setting evil.spawn.max. 
10:39 PM [INFO] [Citizens] Writing default setting evil.spawn.chance. 
10:39 PM [INFO] [Citizens] Writing default setting evil.misc.names. 
10:39 PM [INFO] [Citizens] Writing default setting evil.items.drops. 
10:39 PM [INFO] [Citizens] Writing default setting evil.spawn.spawn. 
10:39 PM [INFO] [Citizens] Writing default setting evil.misc.failed-tame-messages. 
10:39 PM [INFO] [Citizens] version [1.1.2] loaded. 

now i copy a NPC file from the downloaded package in the types folder and start server again... now comes error:

10:36 PM [SEVERE] java.util.zip.ZipException: error in opening zip file 
10:36 PM [SEVERE] at java.util.zip.ZipFile.open(Native Method) 
10:36 PM [SEVERE] at java.util.zip.ZipFile.<init>(Unknown Source) 
10:36 PM [SEVERE] at java.util.jar.JarFile.<init>(Unknown Source) 
10:36 PM [SEVERE] at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:19) 
10:36 PM [SEVERE] at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:311) 
10:36 PM [SEVERE] at net.citizensnpcs.Citizens.onEnable(Citizens.java:78) 
10:36 PM [SEVERE] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:174) 
10:36 PM [SEVERE] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957) 
10:36 PM [SEVERE] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280) 
10:36 PM [SEVERE] at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:171) 
10:36 PM [SEVERE] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:154) 
10:36 PM [SEVERE] at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297) 
10:36 PM [SEVERE] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284) 
10:36 PM [SEVERE] at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152) 
10:36 PM [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348) 
10:36 PM [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:417) 
10:36 PM [INFO] [Citizens] No NPC types loaded. 

maybe this helps to narrow problem down.
