### ISSUE TITLE
ItemInWorldManager, Cannot create NPC's

### ISSUE THREAD

**Issue by JordD04** [CitizensDev/Citizens#288]
Hi, Whenver I try to create a NPC it comes up with: 
"java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<intit>(Lnet/minecraft/server/WorldServer;)V"

Im really confused and dont know what to do, ive looked everywhere for a solution but Im completely stuck, can anyone help me please?

**Comment by scandragon** [comment]
bukkit build #?
citizens build #?

**Comment by JordD04** [comment]
im sorry but I don't know what you mean, I installed bukkit and then pasted the citizens file into the plug-ins folder, and when I type "/npc create test" it comes up with that.
Sorry I cant give much more detail but im new to running servers.

**Comment by Overthelake** [comment]
I've got the same problem.

RB 1185
CB 1.1.2

I also have an immense amount of plugins installed.

**Comment by scandragon** [comment]
Overthelake, you need to downgrade to citizens 1.1.1 or update bukkit.
JordD04, you need to found out which versions you have. Try /version

**Comment by JordD04** [comment]
cheers thx m8, I down graded and it works fine now!
