### ISSUE TITLE
command rewards and commandhelper

### ISSUE THREAD

**Issue by scandragon** [CitizensDev/Citizens#290]
It seems citizens is unable to execute CH aliases through quest rewards.
I have confirmed all the tested commands are working in concole, but no matter what, citizens always says the same "Unknown command"

**Comment by scandragon** [comment]
Fixed

**Comment by temp6532** [comment]
If I may ask, how did you fix it? None of my aliases are working. They work in-game, but through quest rewards they won't. Tested with both server:true and false.
