### ISSUE TITLE
The command was not recognized.

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#294]
I can't use Citizens! I guess it loads correctly, but if I try to use it, for example if I type "/npc help" or "/npc create Gnarf" It always says "The command was not recognized. See /npc help for a list of commands." 
I don't know what to do. I am not using economy and I also disabled it in the config. On my public server, I am OP and Admin. 

Thanks for any help

**Comment by mrvertigo27** [comment]
I too am having this trouble. I have all relevant permissions and all commands tell me to do /npc help  ..... even when i do /npc help. I am using the most recent stable citizens as of todays date as well as craftbukkit #1337 (also tried on previous builds with the same result. I have an extensive list of plugins and can provide a list if needed.

**Comment by Nuts973** [comment]
The same ...
