### ISSUE TITLE
Idea / Feature Request

### ISSUE THREAD

**Issue by Urahara72** [CitizensDev/Citizens#30]
Would it be possible to log a false player id with the server that allows the custom skinning of the npc's via names? I don't
 know if anyone has tried this or not. Just an idea I had because we want to make secret service guards to protect the white house on my server but they just aren't quite as intimidating as they should be without their signature black suits and earpieces.

**Comment by aPunch** [comment]
This kind of thing requires a client mod, something we are not interested in doing.
