### ISSUE TITLE
Checked and Double Checked Permission Nodes... No Luck

### ISSUE THREAD

**Issue by Orago100** [CitizensDev/Citizens#302]
Hello. I am using CraftBukkit 1323, and the latest version of Citizens.

My problem is: I absolutely can't get permission to do anything.

I have checked the parsing of my YMLpermission files with parsing testers. I have tried using the permission managers "Permissions 3.1.2" and the latest version of PermissionsBukkit. No success.

Here is the contents of my YML file:

groups:
    Default:
        default: true
        info:
            prefix: ''
            suffix: ''
            build: true
        permissions:
            - 'iConomy.holdings'
            - 'Iconomy.help'
            - 'iConomy.payment'
            - 'lc.level'
            - 'uQuest._'
            - 'towny.town._'
            - 'towny.nation._'
            - 'towny.wild._'
            - 'citizens.use._'
            - 'citizens.create._'
            - 'citizens.modify._'
            - 'ChestShop.shop._'
    Admins:
        default: false
        info:
            prefix: ''
            suffix: ''
            build: true
        permissions:
            - '*'

As you can see, I have tried the old Citizens permission nodes. I have also tried the new ones found at: http://wiki.citizensnpcs.net/index.php?title=Commands_and_Permissions

I have tried both "citizens.*" and typing out all of the nodes individual in full. No luck.

Even when I set my permission group to admin (which only has the permission '*') I still get a no access message.

Am I missing a dependency? The server starts up with no errors. Am I have mod conflict problems? Do I need to downgrade bukkit version?

My server output looks like this:

11:32 PM [INFO] [Pail] Setting up window... 
11:32 PM [INFO] [Pail] Pail 0.7.5 Enabled 
11:32 PM [INFO] Preparing level "world" 
11:32 PM [INFO] Default game type: 0 
11:32 PM [INFO] Preparing start region for level 0 (Seed: 4294005539086093441) 
11:32 PM [INFO] Preparing start region for level 1 (Seed: 4294005539086093441) 
11:32 PM [INFO] [Announcer] Loaded 1 message files! 
11:32 PM [INFO] Announcer (v1.1.0) enabled 
11:32 PM [INFO] AntiCreeper v2.0 - by Rothens 
11:32 PM [INFO] Anticreeper v2.0 - STARTED 
11:32 PM [INFO] CraftBukkitUpToDate version 2.7.0 is enabled! 
11:32 PM [INFO] HelpPages 1.3 enabled 
11:32 PM [INFO] Help Pages reloaded. 
11:32 PM [INFO] HelpPages: Permissions detected 
11:32 PM [INFO] [LC] Level Combat Loaded 
11:32 PM [INFO] [LC] Level Dexterity Loaded. 
11:32 PM [INFO] [LC] Level Excavation Loaded 
11:32 PM [INFO] [LC] Level Explosives 0.1 Loaded 
11:32 PM [INFO] [LC] Level Mining Loaded 
11:32 PM [INFO] [LC] Level Range Loaded. 
11:32 PM [INFO] [LC] Level Scavenger 0.1 Loaded 
11:32 PM [INFO] [LC] Level WoodCutting Loaded 
11:32 PM [INFO] [LC] Using Permissions. 
11:32 PM [INFO] [LC] Using FlatFile To Store Data. 
11:32 PM [INFO] [LC] LevelCraftCore 0.1.7.1 Loaded 
11:32 PM [INFO] [LC] Loaded levels:[Mining, Combat, Explosives, Excavation, WoodCutting, Range, Dexterity, Scavenger] 
11:32 PM [INFO] PailPlus v0.2 beta enabled 
11:32 PM [INFO] PermissionsBukkit v1.2 is now enabled 
11:32 PM [INFO] [Questioner] v0.4 - Enabled 
11:32 PM [INFO] [SuperpermBridge] Superperm/Permissions bridge enabled 
11:32 PM [INFO] [iConomy] hooked into Permissions. 
11:32 PM [INFO] [uQuest] Loaded with Flatfile! 
11:32 PM [INFO] [uQuest] v1.5 enabled! With 53 quests loaded! 
11:32 PM [INFO] [ChestShop] Permissions version 2.7.7 loaded. 
11:32 PM [INFO] [ChestShop] Towny version 0.76.3.0 loaded. 
11:32 PM [INFO] [ChestShop] version 3.24 initialized! 
11:32 PM [INFO] [ChestShop] iConomy 5 loaded. 
11:32 PM [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard 
11:32 PM [INFO] CButD: CraftBukkit is Outdate, try to download new version 
11:32 PM [INFO] [Citizens] Permissions system found (PermissionsBukkit v1.2) 
11:32 PM [INFO] [Citizens] version [1.1.2] loaded. 
11:32 PM [INFO] [Citizens] Economy plugin found (iConomy v5) 
11:32 PM [INFO] [Register] Payment method found (iConomy version: 5) 
11:32 PM [INFO] Saving Commented Config... 
11:32 PM [INFO] [Towny] Database: [Load] flatfile [Save] flatfile 
11:32 PM [INFO] [Towny] Time until a New Day: 7 hours, 27 minutes, 17 second 
11:32 PM [INFO] [Towny] Version: 0.76.3.0 - Mod Enabled 
11:32 PM [INFO] Server permissions file permissions.yml is empty, ignoring it 
11:32 PM [INFO] Done (0.214s)! For help, type "help" or "?" 
11:32 PM [INFO] [Citizens] Loaded 0 NPCs. 
11:32 PM [INFO] [Citizens] Loaded 0 quests. 
11:32 PM [INFO] [uQuest] Successfully linked with iConomy. 
11:32 PM [INFO] [uQuest] Successfully linked with Permissions. 
11:32 PM [INFO] The automatic update-Check only work every 6 hours, the last check was 82 minutes ago.

 Thank you for any help.

**\* Don't know how to post code properply on github, sorry.

**Comment by scandragon** [comment]
The old style Permissions is no longer supported
As for permissionsbukkit, could you post your config file for that aswell?

**Comment by Orago100** [comment]
groups:
    default:
        permissions:
            permissions.build: true
            iConomy.holdings: true
            Iconomy.help: true
            iConomy.payment: true
            lc.level: true
            uQuest._: true
            towny.town._: true
            towny.nation._: true
            towny.wild._: true
            citizens.toggle._: true
            citizens.waypoints._: true
            citizens.basic._: true
            ChestShop.shop._: true

```
admin:
    permissions:
        permissions.*: true
```

messages:
    build: '&cYou do not have permission to build here.'

I figured out part of my problem. I didn't fully understand the new permission system and ended up just copying my old permissions into the PermissionBukkit config. It worked for my other plugins.

The above permissions still don't work for Citizens though. Do I have to individually list every permission?

**Comment by scandragon** [comment]
citizens.basic._: true
citizens.toggle._: true
citizens.waypoints.*: true
