### ISSUE TITLE
PermissionEx creating NPC problem

### ISSUE THREAD

**Issue by Drehverschluss** [CitizensDev/Citizens#304]
Hi dev Team...first of all great plugin...i still have one issue
My server is runnig Craftbukkit #1240
                                   PermissionEx 1.15
                                   Citizens 1.1.2
so for the admins all works fine when i have the permission.alloweOP

but for my different goups it wont let you create a NPC

i think i made it correct with permission like this

Permission for my group "Citizen"

citizens.use.create
citizens.npccount.unlimited
and much more to set it up with name and and and

but this 2 permissons will be the important for creating a amount of NPCs right?
but everytime when someone try to create one the chat says "Allready reach limit" or somthing like that
but thats strange i can make it as admin
so what i do wrong?

**Comment by Drehverschluss** [comment]
i think i make all corrently

**Comment by Drehverschluss** [comment]
ups wrong button sry

**Comment by Drehverschluss** [comment]
ni ideas?

**Comment by Drehverschluss** [comment]
plz help...i downloadet the latest devbuild now too
but it still not working!

**Comment by Drehverschluss** [comment]
how long i need to whait for a answer?

**Comment by Drehverschluss** [comment]
problem is still present even with the Devbuild 267!

and still no answer/idea :/

**Comment by Drehverschluss** [comment]
thx (not) for you awesome help here!

**Comment by Akhawais** [comment]
I Fell sorry for u but i have no knowledge

**Comment by Drehverschluss** [comment]
i so bad that i have to whait 5 days for a answer (or no answer :( )

**Comment by VADemon** [comment]
FIXED WITH PERMISSIONSEX 1.16 VERSION!
(Sorry for Caps!)

**Comment by Drehverschluss** [comment]
sweeeeet thx 4 commend
