### ISSUE TITLE
It seems like citizens thinks i'm an npc....

### ISSUE THREAD

**Issue by AMW10** [CitizensDev/Citizens#306]
Hey developers.

Me and my friends were building a huge RPG Server and weve put ourselves as NPC's in it.
Now, if we log in to it, there are these npc and follow us.
I cant write nor place blocks.
pls i need your help (:

ps: we cant get rid of them even if we delete it in the npcprofiles.yml <.<

**Comment by scandragon** [comment]
Update to the latest build from http://ci.citizensnpcs.net
