### ISSUE TITLE
Unable to Create NPC. 

### ISSUE THREAD

**Issue by sanvira** [CitizensDev/Citizens#308]
Hi, when I start up my server and attempt to create an NPC i get the message that two previous people were getting. I've updated my craftbukkit to the version listed on Dev and still I am unable to create. is there a reason for this?

**Comment by Akhawais** [comment]
Me Have same problem too i have 1185 and still

**Comment by Drehverschluss** [comment]
for the CB #1185 you need citizens #1.1.1

#1.1.2 wont work with the old Craftbukkit!

**Comment by Tristan7** [comment]
Yeah im haveing a problem like that but it says this "java.lang.NoSuchMethodError:net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer:)V" 

Please help me ASAP

**Comment by Drehverschluss** [comment]
When you become this error massage then u are useing CB#1317 right?

Citizens only work with #1240 atm i think

**Comment by Akhawais** [comment]
Yeah Figured That Out Dreh thanks a lot anyway

**Comment by Akhawais** [comment]
Tristan Try Updating To CB 1240 or Use Citizens 1.1.1
