### ISSUE TITLE
NPC Move Glitch

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#31]
I was high up in the air and used the NPC move command.

The NPC was sent to my location, and gravity was applied upon reload!

I then tried to use /npc tp to get to my NPC, but it saved the NPCs location before gravity had been applied.

Reloading or Restarting the data was still saved high up in the air and the NPC would repeat the same fall every load.

**Comment by fullwall** [comment]
Gravity is always applied?

**Comment by mbsuperstar1** [comment]
Gravity is only applied on NPC creation or reload.

If you /npc move, an NPC into the air, it will stay there.

**Comment by mbsuperstar1** [comment]
Also if you remove the blocks beneath an NPC it won't fall, so either gravity needs to be added...or removed from these particular circumstances.

**Comment by fullwall** [comment]
Needs to be added then. The code to do it is... slightly funny :P.

**Comment by MadcowD** [comment]
Can we have an option? I want to have flying NPC's :3
