### ISSUE TITLE
npcs of same name stacking

### ISSUE THREAD

**Issue by Safetybrick** [CitizensDev/Citizens#310]
when i walk close to one of npc's with similar name to another in town, they seem to move on top of each other. running 1.1.2 of citizens.

**Comment by Safetybrick** [comment]
i noticed it seem to only happen with one of the guards that has the lookat set to true. the other guard, when i walk close (is not set to lookat) does not cause the second guard to move.

**Comment by scandragon** [comment]
Update to the latest build from http://ci.citizensnpcs.net
