### ISSUE TITLE
Quest reward issue

### ISSUE THREAD

**Issue by rulorn** [CitizensDev/Citizens#314]
I do not need to give away the cactus (itemid 81). I just need to collect. If the item is in my inventory the npc take it and if i drop it before i can finish the quest nevertheless. I have tested it on my server with no other plugins. 

Bukkit 1240
Citizen 1.1.2

quests.yml
http://pastebin.com/BGPAM8gT

**Comment by rulorn** [comment]
The quests.yml was not readable. I changed to pastebin.

**Comment by fullwall** [comment]
You have take: true in the rewards section, so it's taking away the cactus.

**Comment by rulorn** [comment]
Yes, but it is not necessary. I can drop the items before and finish the quest anyway. Sorry for my google translator english.
