### ISSUE TITLE
Citizens Not Using Economy System

### ISSUE THREAD

**Issue by JakeHeintz** [CitizensDev/Citizens#315]
For some reason, my NPCs no longer take or give money to players.  Players can buy items from the NPCs, and it gives them the item, but it doesn't remove the money from their balance.  They also are not rewarded their money after completing quests.  However, other plugins on the server that rely on the economy plugin still work properly.  I am using EssentialsEco.

**Comment by Drehverschluss** [comment]
did you run the latest register.jar too?
