### ISSUE TITLE
Serious bugs !! Cheat NPC Trade [HACK] !!

### ISSUE THREAD

**Issue by phurinath** [CitizensDev/Citizens#317]
This is serious bugs !!

all player can buy any items no use money !!!

watch this video.

Citizens Trader bug = http://www.youtube.com/watch?v=qhLRb79X19U

0:10 i try to check my money
0:20 i try to buy items with no money
0:30 i try to HACK !! items for free
1:10 all item i try to hack Fall on the floor.

Citizens Trader bug Image with Admin View

http://uppic.skunkz.net/image-C711_4E9F97E0.jpg

this is photo i use admin go into shop and see all item on the floor !!!

this bugs will be when server is lag just try it !! and Please fix it. thank you :)

**Comment by fullwall** [comment]
Need Bukkit inventory events to prevent hacks like these.
