### ISSUE TITLE
Quester: Delivery /quest status Issue

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#32]
Since build#61/62 you get an error when you type /quest status in, when you have a delivery quest.
Error log: http://pastebin.com/51PHv4rb

**Comment by fullwall** [comment]
This is caused by the destination NPC ID being removed while the quest is active. What should happen in this kind of situation?

**Comment by aPunch** [comment]
The quest should be cancelled with a message "Sorry, but the quest is cancelled as (npcname) has died in a tragic /npc remove accident."

**Comment by fullwall** [comment]
Should be cancelled in newest build.
