### ISSUE TITLE
Why doesnt work this Quest?

### ISSUE THREAD

**Issue by kickrazz** [CitizensDev/Citizens#321]
hello i have been trying to make a new quest, but when i want to give a npc a quest it says: there is no quest by that name.
i alse reloaded the plugin.
and this is how my quest looks like:

Honger: {
 texts: {
  description: "He jij daar! Jaaa jij, zou jij wat Mushroom stew voor me willen halen ik heb toch zoveel honger! ow ja ik betaal je ook nog terug.",
  acceptance: "Ahh dat is aardig van je, maar schiet wel op!",
  completion: "zo he! dat was lekker!",
 },
  repeats: 0,
  coin_reward: &COIN { type: money, money: 50, take: false },
  objectives: {
   '0': { # Geef hem te eten
    '0': { type: delivery, amount: 3, materialid: 282, npcdestination: 7, rewards: { '1': *COIN }, message: "Bedankt, maar ik heb nog meer honger, ik heb zin iets zoets, en dat best lang meegaat..." },
    '1': { type: delivery, amount: 1, materialid: 354, npcdestination: 7, rewards: { '1': *COIN }, message: "Ahh dat is lekker maar ik heb zin in een tussendoortje." },
    '2': { type: delivery, amount: 16, materialid: 357, npcdestination: 7, rewards: { '1': *COIN }, message: "Hmm lekker koekjes, als laatste wil ik nog iets uit het water." },
   },
  },
  rewards:  { 
  '1': *COIN },
 }
}

**Comment by scandragon** [comment]
First.. repeats: 0 means they can't take it.. Make it 1 (means it can be done once)
And it's pretty hard to read without any indentation.. I don't know if it's indented correctly

**Comment by fullwall** [comment]
Remove the { } - YAML works based on indentation.
