### ISSUE TITLE
#1185 Can't Create NPC

### ISSUE THREAD

**Issue by Akhawais** [CitizensDev/Citizens#322]
Whenever i type /npc create [nameof my npc]: it shows this on minecraft
http://pocketmcwebsite.dyndns.org/debugkb/citizens/minecraft.jpg

and this on the console
http://pocketmcwebsite.dyndns.org/debugkb/citizens/console.jpg

Please Fix and Possibly Tell me where i have gone wrong

The rest of the mod works like when i do /npc help it tell me options and when i do /npc it say i have to select a npc

:(((  All The Players on the server want a npc and i cant provide one to them :((((

NEED QUICK FIX

Check Out Yourself:
Server IP: pocketmcserver.dyndns.org

**Comment by fullwall** [comment]
Use 1.1.1

**Comment by Akhawais** [comment]
Thanks Anyway I Udated to CB #1240
