### ISSUE TITLE
Quests.yml Is empty

### ISSUE THREAD

**Issue by MankyGit** [CitizensDev/Citizens#324]
I decided I wanted to try and add quests but when i read the wiki it told me there were examples in the quests.yml. SO I went into it and there is noting there. it just has {}. I decided to delete the the citizens plugin then put it back but im still getting noting.
Im using Craft Bukkit build 1337
And the Citizens version 1.1.2

Every thing else works perfectly so far but this. I hope I can at least get a proper quests.yml so I can figure out how to do this.

**Comment by scandragon** [comment]
Yes, there will be examples available on the wiki soon®

But there are plenty of examples to be found on the forums at this time

**Comment by MankyGit** [comment]
Thanks though most of the ones Iv found are ones people are having problems with.

**Comment by scandragon** [comment]
Here are a few examples: http://dl.dropbox.com/u/5160387/refugee/quests.yml

**Comment by MankyGit** [comment]
Thank you so much. Most of the ones I found were not in that format.
