### ISSUE TITLE
Bug critical with hunt quest

### ISSUE THREAD

**Issue by guenael44** [CitizensDev/Citizens#326]
Hello

when i do that for mob giant  :

1giant:
    texts:
        description: (elite)Quete de chasse - /C'est géant!/ Les géants zombie trainent parfois par ici.Trouvez moi un géant et tuer le!
        completion: <g>Wow bravo c'était pas simple! Vous recevez 100 Adelias.
        acceptance: <g>Quete <y>acceptée<g>.
    repeats: -1
    objectives:
        '0':
            '0':
                type: hunt
                string: 'giant'
                amount: 1
                message: Géant tué; 1/1. Retournez voir Dynamyss.
    rewards:
         '0':
            type: money
            money: 100

That count giant AND player , if somebody kill a player the quest is accomplish....

**Comment by fullwall** [comment]
Fixed.

**Comment by guenael44** [comment]
hi , thank you but with the new version 1.1.2 i still have "quest finish" when i kill a player instead giant:)

**Comment by fullwall** [comment]
By fixed, I meant fixed in the dev builds :P. http://ci.citizensnpcs.net

**Comment by guenael44** [comment]
working thx
