### ISSUE TITLE
Issue with same name Citizens

### ISSUE THREAD

**Issue by Streamliner97** [CitizensDev/Citizens#327]
I have a server and I name my citizens by their roles, for example the blacksmiths name is [Blacksmith]. I had an issue when I tried to create multiple guards for a city, all of them named [Guard]. When ever I would create a new guard it would create him and move all the other npcs named [Guard] to him (putting the npc's into each other). If you know a way to create multiple npc's with same names then please don't hold back.

**Comment by scandragon** [comment]
Update to the latest build: ci.citizensnpcs.net

**Comment by Streamliner97** [comment]
it didnt work
