### ISSUE TITLE
Bouncer Aggro

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#33]
If you stop a guard from being aggressive while it is attacking something it will continue to attack until it is out of range or the guard dies.

It would make a lot more sense if it returned to its set location.

**Comment by fullwall** [comment]
Will be fixed in my next commit.

**Comment by mbsuperstar1** [comment]
This still fails to teleport the bouncer during combat or at least stop them attacking, also it would be nice if there was an option of the guard to walk back instead of teleporting. As the teleport may leave gaps in a buildings defense.

**Comment by aPunch** [comment]
reopened, mb reported it is still an issue

**Comment by fullwall** [comment]
mbsuperstar1 - it only teleports if the way back home is outside its radius.

**Comment by mbsuperstar1** [comment]
Even then it still continues to attack, it should walk away when the aggressiveness is turned off...
