### ISSUE TITLE
Quest requirements don't work

### ISSUE THREAD

**Issue by guenael44** [CitizensDev/Citizens#334]
In build #270, quest requirements are broken.
Requiring groups is fine, but requiring a quest doesn't work..

**Comment by guenael44** [comment]
to be more clear:

for combat quest : always ask quest requierement (stuck on first quest line)
for others quest like collect : always never ask requierement (can do the next quest without check the first one)

For now i have dodge the prob by put un reward the next quest and remove this "next quest" from quester list (left click on npc)

**Comment by fullwall** [comment]
Put times: 1
