### ISSUE TITLE
Master Pricelist

### ISSUE THREAD

**Issue by manicer** [CitizensDev/Citizens#338]
If we had the option of a master pricelist  it would take the labor out of making NPCs.  It could wok as simply as loading a pricelist.yml into the plugin, set something like usepricelist=true and you could fill it out.

Item_id=buy,sell

04=1,2
278=1000,2000
etc...

With usepricelist set to true you could set it up so that what ever you stock an npc's inventory with is what they can buy and sell based on the prices in the list.  You could also set an npc to have a value such as willbuy=false or willsell=true, in case you do not want them to buy from players and only sell to them.  This will also help set up a fair and balanced market on your server.

**Comment by Drehverschluss** [comment]
Thats a awesome idea. Nice when fullwall can code this!

**Comment by fullwall** [comment]
It's already done, but I still need to add an opt-out option per-trader npc. Example:

``` ruby
traders:
    global-prices:
        something-anything-nomatter:
            id: 1
            amount: 10
            data: 0 #if necessary
            price: 9000
            selling: false
```

**Comment by Jogeta** [comment]
and this goes in the config file? how do we go about adding items to the traders once we have added them to the config file?
