### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hughes010** [CitizensDev/Citizens#339]
Help!
Whenever i try and create a NPC this comes up:

java.lang.NoSuchMethodError: net.minecraft .server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)v

**Comment by fullwall** [comment]
You're using the wrong version of CraftBukkit for your Citizens version.

**Comment by hughes010** [comment]
Okay thanks. 
But i have the latest CraftBukkit? 
So should i just wait till a new version of 'Citizens' come out?
and thanks alot for replying quickly!

**Comment by fullwall** [comment]
Try using 1.1.2

**Comment by nid5** [comment]
Thanks this helps alot

**Comment by hughes010** [comment]
Thank yaou
