### ISSUE TITLE
Quest requirements help

### ISSUE THREAD

**Issue by Jogeta** [CitizensDev/Citizens#340]
I'm having an issue with quest requirements, i want the players to have to do each quest in sequential order by using the quest type as a requirement, however the 3rd and 4th quests don't require the player to have completed the previous quests and the second quest will not let you start even if you have completed the first quest.

Magic Tricks:
    texts:
        description: 'Want to see a magic trick?'
        acceptance: 'Nobody believes me but it is true, I can turn wood into stone!<br> Bring me&a 1 wooden sword&f and i will prove it!'
        completion: '&5 POOF&f See! Its magic I told you so! Now people will have to believe me.<br> Here you can have it anyway I dont need a sword.<br> &a  You have received a stone sword'
    repeats: 1
    objectives:
        '0':
            '0':
                type: delivery
                materialid: 268
                amount: 1
                npcdestination: 55
    rewards:
        '0':
            type: item
            amount: 1
            id: 272
            take: false
Magic Tricks II:
    texts:
        description: 'This ones even better!'
        acceptance: Bring me &a2 logs&f and watch what i can do.
        completion: '&5 POOF&f Wow, did you see that! Here you take them.<br> &a  You have received a crafting table'
    repeats: 1
    requirements:
        '0':
            type: quest
            quest: Magic Tricks
    objectives:
        '0':
            '0':
                type: delivery
                materialid: 17
                amount: 2
                npcdestination: 55
    rewards:
        '0':
            type: item
            amount: 1
            id: 58
            take: false
Magic Tricks III:
    texts:
        description: Hey, if you want to see another one you are going to have to bring me some wool.
        acceptance: Get to it then, use that shiny new sword i made you and fetch <br> me&a 1 wool
        completion: &5 POOF&f Even I didn't know i could do that.<br> &a  You have received a bed
    repeats: 1
    requirements:
        '0':
            type: quest
            quest: Magic Tricks II
    objectives:
        '0':
            '0':
                type: delivery
                materialid: 35
                amount: 1
                npcdestination: 55
    rewards:
        '0':
            type: item
            amount: 1
            id: 355
            take: false
Magic Tricks IV:
    texts:
        description: Alright, I have one last trick to show you, check it out
        acceptance: This ones tough, youre going to have to bring me one of those<br>&a ender pearls&f if you want to see this one.
        completion: '&5 POOF&f Holy! well you earned it, now get out of here Im tired.<br>&a  $100 has been added to your account'
    repeats: 1
    requirements:
        '0':
            type: quest
            quest: Magic Tricks III
    objectives:
        '0':
            '0':
                type: delivery
                materialid: 368
                amount: 1
                npcdestination: 55
    rewards:
        '0':
            type: money
            money: 100
            take: false

**Comment by hiro24** [comment]
I noticed this too.. it used to work actually.  Not sure what happened, but requirements currently that used to work won't work now.. even if the quest is complete, it says it's not, so can't accept the next quest.

**Comment by scandragon** [comment]
Add times: 1 in the requirement

**Comment by Jogeta** [comment]
ok ill try that thanks
