### ISSUE TITLE
Citizens with the Same Name

### ISSUE THREAD

**Issue by Lycanite** [CitizensDev/Citizens#342]
Citizens with the same name (but different IDs) sort of fuse together where they all seem to say the same thing chosen randomly from one of their speech lines. Any changes done affects only the NPC they're all copying.
To workaround this I've been adding numbers on the end of my NPCs like Guard001 but I would be better to not ahve this as I have to keep track of what number I'm up to, etc.

**Comment by fullwall** [comment]
Can you try http://ci.citizensnpcs.net?

**Comment by Lycanite** [comment]
I've gave it a try and it seems to work however the npc-profiles.yml file looks a bit messed up:

'1':
  basic:
    look-when-close: 'true'
'2':
  basic:
    color: '15'
    inventory: AIR_36,
    balance: '0.0'
    items: 0:0,0:0,0:0,0:0,0:0,
    location: world,32.19267590501271,62.5,-558.5436326944415,83.088776,-9.114958
    text: c
    talk-when-close: 'false'
    talk: 'true'
    look-when-close: 'true'
    owner: ChupaDrahkir
'0':
  basic:
    name: ben
    color: '15'
    look-when-close: 'true'
    items: 0:0,0:0,0:0,0:0,0:0,
    location: world,28.096698633591604,63.0,-556.067133964885,205.5297,0.0
    owner: ChupaDrahkir
    inventory: AIR_36,
    balance: '0.0'
    text: a
    talk: 'true'
    talk-when-close: 'false'
