### ISSUE TITLE
1.9 NPC Villagers and Mob Disguise

### ISSUE THREAD

**Issue by Lycanite** [CitizensDev/Citizens#344]
There is a plugin called mob disguise that lets players literally turn into mobs, could the same technique be used to create NPC mobs? Also could a similar thing be used to set Citizen NPCs and 1.9 NPC Villagers, I know this patch isn't even out yet but just something to consider?

**Comment by aPunch** [comment]
This isn't within the scope of Citizens at the moment. We use human entities for our NPCs, not any other mob type.
