### ISSUE TITLE
problem with npcprofiles

### ISSUE THREAD

**Issue by philipmetting** [CitizensDev/Citizens#354]
## things have been going fine up until a few days ago.  the questers available quests keep duplicating and the quester is rendered useless in game. this also happens with wizards. here is a sample of the part of the profiles that are messing up.

'13':
  basic:
    owner: philipmetting
    talk-when-close: 'false'
    location: world,-986.2753915048696,63.0,692.2561063609955,51.094193,0.0
    look-when-close: 'true'
    name: Guard/Nathan
    inventory: AIR*36,
    balance: '0.0'
    color: '15'
    items: 0:0,0:0,0:0,0:0,0:0,
    talk: 'true'
  quester:
    quests: CreeperKillWaterforNathanCreeperKillWaterforNathan
##     toggle: 'true'

the quests: keep repeating and make the file larger and larger. the only way to fix it is to remove this npc and create a new one, then give it quests.
thank you for you help in this matter

**Comment by philipmetting** [comment]
forgot to put the citizens build.
i am using devbuild 300 right now. i updated from 291 (i think). the problem started with 291 the updated didnt fix
i am using the latest recommended build of craftbukkit

**Comment by fullwall** [comment]
Try updating to a newer version.

**Comment by philipmetting** [comment]
thank you build 304 seems to have fixed it. i did have the problem appear directly after the update. but i removed and created a new quester and havnt had the problem since. 
Thank you

**Comment by philipmetting** [comment]
## never mind the issue is still going on. here is a paste of one of my npc's from the profiles.  hopefully this issue is easy to fix

'19':
  basic:
    inventory: AIR_36,
    talk: 'true'
    balance: '0.0'
    items: 0:0,0:0,0:0,0:0,0:0,
    look-when-close: 'true'
    owner: philipmetting
    color: '15'
    talk-when-close: 'true'
    name: Notch
    location: world,-935.3000000119209,67.0,693.3902006592201,87.297325,34.94992
    text: Welcome to my Kingdom!;Start the Fighters guild quest line here!
  quester:
    toggle: 'true'
    quests: SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell;SwordtoDrydellSwordtoDrydellSwordtoDrydellSwordtoDrydell;SwordtoDrydell;SwordtoDrydell
'4':
  basic:
    name: Guard/Nathan
    balance: '0.0'
    talk-when-close: 'false'
    location: world,-986.2568565744953,63.0,693.6676647231485,-32.833847,-13.235668
    owner: philipmetting
    items: 0:0,0:0,0:0,0:0,0:0,
    talk: 'true'
    color: '15'
    inventory: AIR_36,
    look-when-close: 'true'
  quester:
    quests: CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan;CreeperKill;WaterforNathan

##     toggle: 'true'

**Comment by fullwall** [comment]
Is this issue happening on reload?

**Comment by philipmetting** [comment]
I haven't checked on a full server reload. I am assuming it is adding the entries when I reload the plugin after I make changes to the npc's through configuration files. My server does restart every day at noon and midnight.

After looking more at the profiles.yml the same thing is happening to the locations on my wizards. I will do some more testing with it and let you know ifi can figure out exactly when it is happening.

I am doing an educated guest and say that the plugin might be reloading those node typed that are saved in memory, then doubling them up on instead of releasing used memory. But I'm not sure exactly how your plugin interfaces. So I apologize in advance if I am completely off the wall.

**Comment by philipmetting** [comment]
i have isolated the issue to this: when i make manually make a change in a file i do a /citizens reload. everything is fine until there is a server restart or reload. that is when it duplicates entries.
i tested this by removing citizens and redoing all npc's on the server. so i know its not a configuration issue. what i dont understand is why i am the only person having this issue. 
thank you for all of your help in this issue

and i did update to devbuild 305 before doing this test

**Comment by fullwall** [comment]
OK, fixing now. Thanks for your help.

**Comment by philipmetting** [comment]
Thank you so much I'll get the update applied when I get back on the
server and test it out

Sent from my Windows Phone

**Comment by philipmetting** [comment]
Thanks that seems to have done the trick. I really appreciate your help
in the matter. I'll close the ticket tomorrow when I get to work.

Sent from my Windows Phone
