### ISSUE TITLE
"Reached NPC-creation limit!" Permissions problem

### ISSUE THREAD

**Issue by VADemon** [CitizensDev/Citizens#367]
Users can't create NPCs and they get a message about that they reached NPC-creation limit. Doesn't matter whether they have citizens.npccount.unlimited or citizens.npccount.\* or citizens.npccount.100 . They get this message although they didn't create any NPCs yet.
Using PermissionsEx 1.15
http://forums.bukkit.org/threads/admn-dev-permissionsex-pex-v1-15-tomorrow-is-today-1337.18140/

Thanks.

VADemon

**Comment by Dimitrias** [comment]
Same problem, fix please!

**Comment by VADemon** [comment]
FIXED SINCE PERMISSIONSEX v. 1.16
Sorry for caps!
