### ISSUE TITLE
Quester Rewards... Help me!

### ISSUE THREAD

**Issue by dezemand** [CitizensDev/Citizens#369]
Hey there!
I've a lil problem:

How do the rewards works? Like:

   '0':
            type: permissions
            ???: 'a.nice.node.*'

And does the permission type also works with Permissions 3.16? The evil plugin!
Hope somebody is answering this question soon!

Cya!

**Comment by fullwall** [comment]
type: permission
permission: 'a.nice.node'

Sorry, Citizens doesn't work with non-superperms permissions plugins.
