### ISSUE TITLE
Inventory Events.

### ISSUE THREAD

**Issue by Xlar** [CitizensDev/Citizens#38]
A few days ago I posted this https://github.com/CitizensDev/Citizens/issues/12 
## Apparently Spout Sever side features (Players do not need the Spoutcraft client mod installed.) has Inventory events, so If I were to install the sever side Spout would this fix the issue (in the link posted above)? Or would I have to wait for you guys to do a fix on the citizens plugin?

Issue: https://github.com/CitizensDev/Citizens/issues/12

Spout: http://dev.bukkit.org/server-mods/spout/

(Sorry if it looks like I am trying to promote them, just posting the link their in case you guys haven't heard about it.)

**Comment by Xlar** [comment]
Sorry for the half huge and half small text, don't know why it came out like this :S

**Comment by fullwall** [comment]
We have heard about Spout's inventory events, however, don't want to make Spout mandatory for every server wanting to use Citizens.

**Comment by Xlar** [comment]
But Spout improves server performance? Alot of servers use Spout already, don't really see whats wrong with it. https://bitly.com/spoutserverrunonce+ Apparently over 55k servers use Spout already. Would be greatly appreciated by alot of people if you guys did this :(
