### ISSUE TITLE
1.1 (Build 68) Error Copying Guard

### ISSUE THREAD

**Issue by Coffeehedake** [CitizensDev/Citizens#39]
http://pastebin.com/jmLznPze

Re-configured an NPC (from an NPC that was created with 1.0.9c, just a regular NPC with waypoints)
Removed (reset) the waypoints for that NPC
Toggled him as a guard
Added some mob flags (Spider, Creeper, Skeleton, Zombie)
Added some Player flags (evil_fullwall, evil_apunch)
Copied the NPC using /npc copy

an error occured, (asking me to report this error)
I have pastebinned my server log above.

**Comment by Coffeehedake** [comment]
Also of note, my guards don't actually attack anything. But I suppose that's a different issue, or I don't have it configured properly. Any further documentation on commands and usage for the guards?

**Comment by fullwall** [comment]
Probably /guard aggro /guard bouncer.

**Comment by Coffeehedake** [comment]
Tried both of those before, no luck

**Comment by mbsuperstar1** [comment]
Did you make sure to give it a radius in which to attack?

**Comment by Coffeehedake** [comment]
Yup
