### ISSUE TITLE
Worst mod ever

### ISSUE THREAD

**Issue by Sergeant1337** [CitizensDev/Citizens#390]
There is bugs EVERYWHERE.

I made a npc named Sergeant1337, just as my name.
Then, I couldn't do anything with him. I deleted him, after that, I couldn't open the /Npc list. Then I create a NPC named Guard.
Then I logged out and then joined the server. Then, Guard, was where Sergeant1337 where before I deleted him.
Then I created a guard named Smith, he wasn't even in the /Npc list. So Icoulnd't delete him. Now I have a fucked up server. THANKS ALOT! <3

**Comment by fullwall** [comment]
First, calm down. Then, realise that most of these 'bugs', such as creating NPCs with your own name breaking things, are caused by Bukkit. Then, download a new build from http://ci.citizensnpcs.net.
