### ISSUE TITLE
A way to remove armor

### ISSUE THREAD

**Issue by tiagoad** [CitizensDev/Citizens#40]
A way to remove armor from NPC's is needed, right now the only way is by re-creating the NPC.
I propose setting armor to "0" to remove it.

**Comment by aPunch** [comment]
Added completely new npc equipping system. You can now type '/npc equip' which will put you in equipment-edit mode. From there you can add/remove items and armor to your heart's content. Type '/npc equip' again to exit equipment-edit mode.
