### ISSUE TITLE
Server crash when setting waypoints. :(

### ISSUE THREAD

**Issue by MrRamziaB** [CitizensDev/Citizens#406]
using build 323 server crashes after creation of the NPC, setting it's class (healer/guard etc.) server crashes when setting waypoints.

Server console log:

23.11 02:11:25 [Server] INFO [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
23.11 02:11:25 [Server] INFO [Citizens] 
23.11 02:11:24 [Multicraft] Stopping Minecraft!
23.11 02:11:24 [Multicraft] Ping timeout! Restarting Minecraft...
23.11 02:11:19 [Server] INFO [Citizens] An error has occurred, please wait while it is sent to the developers...
23.11 02:11:19 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.Packet14BlockDig.a(SourceFile:43)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:497)
23.11 02:11:19 [Server] INFO    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:92)
23.11 02:11:19 [Server] INFO    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:171)
23.11 02:11:19 [Server] INFO    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
23.11 02:11:19 [Server] INFO    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
23.11 02:11:19 [Server] INFO    at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:330)
23.11 02:11:19 [Server] INFO    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteract(PlayerListen.java:66)
23.11 02:11:19 [Server] INFO    at net.citizensnpcs.npcdata.NPCDataManager.handlePathEditor(NPCDataManager.java:188)
23.11 02:11:19 [Server] INFO    at net.citizensnpcs.npcdata.PathEditingSession.insert(PathEditingSession.java:26)
23.11 02:11:19 [Server] INFO    at net.citizensnpcs.waypoints.WaypointPath.insert(WaypointPath.java:62)
23.11 02:11:19 [Server] INFO    at java.util.ArrayList.add(Unknown Source)
23.11 02:11:19 [Server] INFO    at java.util.ArrayList.rangeCheckForAdd(Unknown Source)
23.11 02:11:19 [Server] INFO java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
23.11 02:11:19 [Server] SEVERE Could not pass event PLAYER_INTERACT to Citizens

**Comment by fullwall** [comment]
Can you try with the new build?

**Comment by MrRamziaB** [comment]
unless i am mistaken, this IS  the latest build...

**Comment by fullwall** [comment]
Just committed a new build...?

**Comment by MrRamziaB** [comment]
link pls?

**Comment by fullwall** [comment]
http://ci.citizensnpcs.net

**Comment by MrRamziaB** [comment]
yeah... build 323 as it states in the original post, I am on the latest build.

**Comment by MrRamziaB** [comment]
bump

**Comment by fullwall** [comment]
Can you try the latest build?

**Comment by MrRamziaB** [comment]
I would if your gorran server was working.

**Comment by MrRamziaB** [comment]
Please post the latest build somewhere that we can download it.

**Comment by fullwall** [comment]
http://dl.dropbox.com/u/6701575/new%20Citizens.zip

**Comment by MrRamziaB** [comment]
Thank you very much!
