### ISSUE TITLE
Not up to date?

### ISSUE THREAD

**Issue by Urahara72** [CitizensDev/Citizens#407]
It was running fine then when I tried to set up a quest for and RPG world on my server i started getting console errors saying citizens 1.1.1 wasn't initiated properly (is it up to date?) But I know that I have updated to 1.1.2 3 times to try and fix it. It doesn't work at all now. I can't even create NPC's. Help?

**Comment by IDragonfire** [comment]
Can you post the console error?
Where did you download the jar?

**Comment by Urahara72** [comment]
I downloaded from the dev page here. 

http://pastebin.com/j0UUX5tQ
^ console log

**Comment by IDragonfire** [comment]
These is a devlopment build (unstable) ...
If you want a stable build use:

http://dev.bukkit.org/server-mods/citizens/files/7-1-1-2/
(press Download)

An overview:
http://dev.bukkit.org/server-mods/citizens/files/

**Comment by Urahara72** [comment]
thats the build i am using and it doesnt work

**Comment by IDragonfire** [comment]
Hmm,
did you delete your config files already?
(make a backup before)
What is your bukkit version?

**Comment by Urahara72** [comment]
I deleted the configs and now i can make npc's but it won't let me change their types

**Comment by Urahara72** [comment]
oh nvm
type files are missing
