### ISSUE TITLE
Error on waypoint modifier

### ISSUE THREAD

**Issue by Urahara72** [CitizensDev/Citizens#41]
12:28:39 [SEVERE] java.lang.ArrayIndexOutOfBoundsException: 3
12:28:39 [SEVERE]   at com.citizens.resources.sk89q.CommandContext.getString(CommandContext.java:64)
12:28:39 [SEVERE]   at com.citizens.commands.commands.WaypointCommands.modifier(WaypointCommands.java:34)
12:28:39 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:28:39 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
12:28:39 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
12:28:39 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:597)
12:28:39 [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:518)
12:28:39 [SEVERE]   at com.citizens.resources.sk89q.CommandsManager.execute(CommandsManager.java:404)
12:28:39 [SEVERE]   at com.citizens.Citizens.onCommand(Citizens.java:196)
12:28:39 [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
12:28:39 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)
12:28:39 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:320)
12:28:39 [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:713)
12:28:39 [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:677)
12:28:39 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:670)
12:28:39 [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
12:28:39 [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
12:28:39 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:85)
12:28:39 [SEVERE]   at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:436)
12:28:39 [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
12:28:39 [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:451)
12:28:39 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:361)
12:28:39 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

was told to report the error. Happened when i tried to add the waypoint modifier "onclick".

**Comment by fullwall** [comment]
Fixed in next version.
