### ISSUE TITLE
1.0.0 All Npc's stop talking and moving 

### ISSUE THREAD

**Issue by Ichigokurosaki** [CitizensDev/Citizens#412]
Since i have updated my server for 1.0.0 All Npc Have stopped Moving and talking and i have then to talk when close to players and I reset all waypoints for the Npc's that walk But nothing happens

**Comment by Volkster** [comment]
Upgrade to 1.1.2

**Comment by Ichigokurosaki** [comment]
I do have Citizens 1.1.2

**Comment by Volkster** [comment]
Ah I see your problem it just happened it me too.

**Comment by aPunch** [comment]
Citizens 1.1.2 does not work with MC 1.0.0.

**Comment by Mykekeul35** [comment]
Citizens Build 322 is working fine with minecraft 1.0.0 and craftbukkit build 1532 !
