### ISSUE TITLE
Errors, Errors and more Errors

### ISSUE THREAD

**Issue by mattdholloway** [CitizensDev/Citizens#414]
26.11 09:11:46 [Server] INFO Downloading: http://griefcraft.com/bukkit/shared/lib/native/Linux/amd64/libsqlitejdbc.so
26.11 09:11:45 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
26.11 09:11:45 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
26.11 09:11:45 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
26.11 09:11:45 [Server] INFO    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
26.11 09:11:45 [Server] INFO    at net.citizensnpcs.TickTask.run(TickTask.java:32)
26.11 09:11:45 [Server] INFO    at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:101)
26.11 09:11:45 [Server] INFO    at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:62)
26.11 09:11:45 [Server] INFO    at net.citizensnpcs.resources.npclib.PathNPC.handleMove(PathNPC.java:79)
26.11 09:11:45 [Server] INFO    at net.citizensnpcs.resources.npclib.PathNPC.getYawDifference(PathNPC.java:159)
26.11 09:11:45 [Server] INFO java.lang.IllegalAccessError: tried to access field net.minecraft.server.EntityLiving.aQ from class net.citizensnpcs.resources.npclib.PathNPC
26.11 09:11:45 [Server] WARNING Task of 'Citizens' generated an exception
26.11 09:11:45 [Server] INFO [Citizens] Loaded 0 quests.
26.11 09:11:45 [Server] INFO [Citizens] Loaded 13 NPCs.

**Comment by fullwall** [comment]
You're using 1.0 with an old version of Citizens or a new version of Citizens with an old version of craftbukkit.
