### ISSUE TITLE
Trader NPCs loose their configuration after reloading

### ISSUE THREAD

**Issue by AMW10** [CitizensDev/Citizens#44]
After ive reloaded the plugin Citizens the Trader npcs ive made lost every configuration.
when i type /npc and have it selected it says types: - trader
So im very sure ive configurated these npcs right that the /trader list buy (e.g.) says the stuff i typed in there.

But if i reload citizens and type /trader list buy with the trader selected it says its empty e.e

I hope there is a solucion for it soon o.o

**Comment by philman401** [comment]
I have the same problem too :C  Sometimes even after I set it up, and play with it for a while, later after I restart the server, the npc I setup as trader is for some reason no longer a trader either.

**Comment by AMW10** [comment]
I got it philman :3 just type /citizens save before restarting

**Comment by philman401** [comment]
yaay grats on the find!  And thanks C:

**Comment by fullwall** [comment]
If you type 'stop' into the server to stop it, this would also fix the issue @philman401.
