### ISSUE TITLE
Give Quest Reward not working

### ISSUE THREAD

**Issue by davejones1997** [CitizensDev/Citizens#442]
I was doing this yesterday and it worked fine, no idea what I am doing wrong now, for some reason I get back to the person who sets the first quest and get the golden apple reward but it doesn't start my next one :( from that person. Here is my setup for that section. btw When I set them both to give items instead of 1 quest and 1 item it worked fine. Not sure if  have got any of the quest thing wrong.
    rewards:
         '0':
            type: quest
            quest: BeachTrouble
         '1':
            type: item
            id: 322
            amount: 1
            take: false
BeachTrouble:
    texts:
        description: Sort out the mob investation at the beach.

**Comment by m0nkm0nk** [comment]
I had the same issue here while I was running 1.8.1 with the latest "official / stable" citizens..
Just upgraded my server to the newest dev bukkit and upgraded all citizens files to the latest dev build.

Now its working.

My test script is below here :

stone:
    texts:
        description: "&7Tutorial Quest! &fRank: None"
        completion: <g>You win!.
        acceptance: <g>Challenge <y>accepted<g>.
    repeats: -1
    objectives:
        '0':
            '0':
                type: build
                materialid: 1
                amount: 3
                message: Built. Now come back here!
    rewards:
        '0':
            type: item
            id: 260
            amount: 1
            take: false
        '1':
            type: quest
            quest: apple
            take: false

apple:
    texts:
        description: "&7Delivery quest!"
        completion: "Thanks my friend!"
        acceptance: "Thanks for helping me out! Can you bring this apple to my friend. He's workin as a <g>Gatekeeper"
    repeats: -1
    objectives:
        '0':
            '0':
                type: delivery
                npcdestination: 1
                materialid: 260
                amount: 1
                message: "<g>Thanks a lot!"

**Comment by davejones1997** [comment]
mine is working now, as well, what I worked out was that it couldn't find the quest at all. So I basically copied exactly the same quest as above that was working, deleted all the steps and rewards, and it started working. It was weird.
