### ISSUE TITLE
Help me /npc create ERROR Java

### ISSUE THREAD

**Issue by CatMilk** [CitizensDev/Citizens#469]
Hellllooo
Please help me fast
## i think alot of peoples have the same error

My Citizen Version 1.1.3
When i try to spawn a NPC
it give this mensage:

In-Game:
http://imgur.com/VFbPy

Console:
(only a part of the console)
http://imgur.com/XYPIF

**Comment by Sdrubs** [comment]
You have latest RB? (1.0.1) because Citizens 1.1.3 only run right on 1.0.1

**Comment by CatMilk** [comment]
??? 1.0.1?? CraftBukkit? where i can download give me a link please

**Comment by Sdrubs** [comment]
Oh,download it from the official bukkit forums.
www.bukkit.org.

**Comment by fullwall** [comment]
You need to update your Bukkit.
