### ISSUE TITLE
Players cant use Traders even with permission nodes

### ISSUE THREAD

**Issue by Karzire** [CitizensDev/Citizens#47]
For Some Reason Players cant use Npcs. They can select them but can use the. I have the Nodes set up for players to use them  which are citizens.use.trader, and citizens.trader.stock. So please help.

**Comment by Coffehedake** [comment]
Just a suggestion, try citizens.use.trader.use (I think that was it) I think one of us is using the old permissions nodes, could be me though, but worth a shot.

**Comment by aPunch** [comment]
citizens.trader.use.trade
