### ISSUE TITLE
Guard individual flags.

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#48]
With the -a flag a guard attacks their owner, however this fails to happen with their name and -p.

With the -m flag and a mob type it always fails and says "mob type" not recognized.

Due to my test server being constantly empty, haven't properly tested -p and -g.
Will let other testers clean these up.

**Comment by fullwall** [comment]
This _should_ be fixed in the latest commits.

**Comment by fullwall** [comment]
Wait... the mob type thing may not be working :S.

**Comment by sleepingwraith** [comment]
I'm having this issue with the 1.5 release....
