### ISSUE TITLE
Cloning items... [BUG]

### ISSUE THREAD

**Issue by puchat** [CitizensDev/Citizens#51]
Hello.
I found a bug.

Take diamond in your hand.
Remember: you can't be the owner of a trader. Type /npc setowner blahblah
Right-click on a trader and at the same time press Q on your keyboard. Diamond is now multiplied. :(

The same problem with holding food in hand while right-click on a trader.
You will be healed, but the food will not disappear. 
(For example try with apple).

I hope you will find a solution and repair the issue in the next update. :)

Sorry for my english, I'm still learning. :)

**Comment by aPunch** [comment]
This is a well known bug. It cannot be fixed at the moment due to Bukkit's lack of inventory events.
