### ISSUE TITLE
giving/taking money from traders

### ISSUE THREAD

**Issue by remypas** [CitizensDev/Citizens#516]
I'm setting up my server so my players can make their own traders. But somehow I can't get the /trader money give/take permissions set up right.  I gave the players the permissions:

-citizens.trader.modify.money
-citizens.trader.use.showmoney

however, when they use the comands 

/trader money or /trader money give/take 
it doesn't work.

On the wiki, there was the permissions node: -citizens.citizens.trader.modify.money I thought this was a typo. but eventually tried this one to but no luck.

Who can help me, and give me the right permissions to give my payers to start making their own traders?

**Comment by remypas** [comment]
anyone?

**Comment by IDragonfire** [comment]
I know the permission node has change ...
The "trader.use.showmoney" node
and "trader.modify.money" node exists in 
https://github.com/CitizensDev/Citizens/blob/master/src/trader/net/citizensnpcs/traders/TraderCommands.java
but no command method use these permissions ...
In which version "/trader money" works?

**Comment by IDragonfire** [comment]
Where did you find these command?

/trader money?

**Comment by remypas** [comment]
I found the /trader money (give/take) on theis page
http://wiki.citizensnpcs.net/index.php?title=Trader
I figured a player could just use /trader money
to see the traders balance. But I guess that command is /trader showmoney.

But the issue of the trader money (give/take) now working is the most pressing one. Since it'll be needed for the players to maintain their own traders

**Comment by IDragonfire** [comment]
the wiki ist outdated xD
These command doesn't exists atm^^

https://github.com/IDragonfire/Citizens/commit/531bc287b67a1fdda1af46a7efaa47510e5c67d2

Please use /npc money ...

**Comment by remypas** [comment]
so I add the permission node
-npc.money.modify
to the group I want to have the permission
and they use the command 
/npc money (give/take) (Amount)

I'll test run it.

**Comment by remypas** [comment]
I figured it out. Thanks for poinitng me in the direction of logical thinking.

I added permission node 
-citizens.basic.modify.money
that did the trick!
