### ISSUE TITLE
Quester [quets.yml] [player combat]

### ISSUE THREAD

**Issue by Jenjen1324** [CitizensDev/Citizens#520]
I try'd to make an Assasination quest but when I have killed someone it just sais: "Quest isn't completet yet"

Code:

Assasination:
    texts:
        description: <b>Assasination - Reward  1000 gold
        completion: <b>Here is your reward, 1000 gold
        acceptance: <b>Go out and kill another player, return to me when you are done to get your reward.
    repeats: 1
    objectives:
        '0':
            '0':
                type: player combat
                amount: 1
                string: 'g:default'
    rewards:
        '0':
            type: money
            money: 1000

**Comment by ProjectZain** [comment]
try changing the type from player combat to combat.

**Comment by Jenjen1324** [comment]
Still didn't work

**Comment by ProjectZain** [comment]
is your spacing okay? paste your code in pastebin.com and post a link. I'll check your work.

**Comment by Jenjen1324** [comment]
http://pastebin.com/Wuz5X2SG

**Comment by Jenjen1324** [comment]
The beginning is on Line 35

**Comment by ProjectZain** [comment]
Everything seems to be okay, but if you're trying to make it so they can kill any player I would replace g:default with a *

**Comment by Jenjen1324** [comment]
It worked now thanks alot.
