### ISSUE TITLE
Players cannot use npc

### ISSUE THREAD

**Issue by Dybas** [CitizensDev/Citizens#533]
I use citizens with op and everything is good but when player tries to use trader or healer than nothing happens.
And when right clicked at blackshimt it says that dont have permissions.Even admin with '*' (without op) has the same
List of my plugins:
BlockDoor, WorldGuard, FalseBookChat, HelpPages, AutoSave, ModTRS, FalseBookCore, WorldEdit, FalseBookBlock, AutoMessage, VanishNoPickup, Stargate, AuthMe, HeroChat, iConomy, PvPTime, FalseBookIC, Permissions, FalseBookExtra, CommandBook, FalseBookCart, MyWarp, MoveCraft, Citizens, LWC, Jobs, MyHome, BookWorm, ChestShop
I have heard that citizens does not support permissions 3 by TheYeti, I hope that's not true...

**Comment by Dybas** [comment]
Pliiiiiiisssssssssssssssssssss
Heeeeeeeeeeeeeeeeeeeeeeelp

**Comment by IDragonfire** [comment]
Try another Permission plugin ...

**Comment by Dybas** [comment]
I have tried permissionsbukkit but there was needet to change chat plugin,because it daoesn't have prefixes and suffixes...
Its too big work

**Comment by IDragonfire** [comment]
I like PermissionEx 

http://dev.bukkit.org/server-mods/permissionsex/

**Comment by Dybas** [comment]
It works!!
I'm very thankfull
It's wonerfull plugin!!
