### ISSUE TITLE
Suggestion:  Allow multiple rewards per objective / quest.

### ISSUE THREAD

**Issue by quickclay** [CitizensDev/Citizens#541]
It would be great if we could give someone multiple kinds of quest awards when they complete a quest, rather than just a number of one item.

**Comment by l1amm** [comment]
You can....

**Comment by quickclay** [comment]
How? I've tried adding serveral reward lines and it only accepts the last item listed.

**Comment by quickclay** [comment]
Aha. I thought the reward number had to correlate with the objective number. Nvm. :)
