### ISSUE TITLE
quest.yml configuration

### ISSUE THREAD

**Issue by luigivampa** [CitizensDev/Citizens#549]
I've made a quest to deliver some pork. How do I configure the quest.yml so that the first npc (the quester) gives you the pork to deliver. Currently after you accept the quest you have to go and get the pork yourself. Since it's a delivery for a butcher he should supply the pork to be delivered. Here's what I've got so far:

Porkrun:
    texts:
        description: <g>Deliver some pork.
        completion: <g>Payment received.
        acceptance: <g>Quest Accepted.
    repeats: -1
    objectives:
        '0':
            '0':
                type: delivery
                npcdestination: 6
                materialid: 319
                amount: 1
                message: <g>Delivered pork.
    rewards:
        '0':
            type: money
            money: 5
            take: false

**Comment by notcam45** [comment]
I don't think it's possible yet, bet a very nice suggestion. I would suggest making the quest config more user friendly and esier to understand. Use the old uQuest config for documentation, it's very easy to use. -For Developers

**Comment by l1amm** [comment]
make the first objective on the quest to go to the location of the npc that gave you the quest,
and make the reward for completing the first objective pork.

**Comment by luigivampa** [comment]
Thanks for the reply people. Took your suggestion l1amm. A bit of a hack but works a treat!
