### ISSUE TITLE
Does not save configuration on server reload/shutdown

### ISSUE THREAD

**Issue by grandwazir** [CitizensDev/Citizens#55]
Citizens does not appear to save its configuration when the server is reloaded or shutdown. I've lost so many NPCs this way I've lost count.

**Comment by aPunch** [comment]
Do you mean all NPC types or just one, such as traders? We are working on fixing trader saving for 1.1.

**Comment by grandwazir** [comment]
I only use basic NPCs on my server so I can not comment for the others.

**Comment by aPunch** [comment]
Type /citizens save before shutting off your server or type /stop to shut down your server.

**Comment by grandwazir** [comment]
I do use /stop to stop the server. The restart script shuts the whole thing down gracefully and Citizens is still not saving data correctly.

**Comment by aPunch** [comment]
What version are you using?

**Comment by grandwazir** [comment]
[1.0.9d](Odyssey)

**Comment by aPunch** [comment]
Saving issues should be fixed in 1.1, you can try out a development build or wait for 1.1 to be released.
