### ISSUE TITLE
[Question] Possible to complete quest without returning to quest giver?

### ISSUE THREAD

**Issue by l1amm** [CitizensDev/Citizens#556]
Title basically says it all.
Is it possible to have a quest EITHER automatically complete after the last objective is completed, without making the player return to the quest giver?
AND/OR Is it possible to make it so a different NPC completes it instead of the quest giver?

**Comment by byklop** [comment]
I'm interested what is the answer for this too. If it is possible then how to make such a quest?

**Comment by Farwaykorse** [comment]
add this to the objective you want to end the quest with:
    finishhere: true

Completing with a different npc:
You can't add a click on character, but you can use a move-location, at the other npc's location. Or make deliveries to them.
