### ISSUE TITLE
Guard bouncers & arrows

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#56]
If you give an aggro bouncer guard a bow to kill things and the mob in his blacklist comes within range or a player attacks him, the guard spams the ground with arrows like crazy making a huge mess as well as shooting himself. 90% of the time the guard dies before the mob does. One time it crashed the server when a player was shot with arrows, however I wasn't able to replicate the problem again.

**Comment by fullwall** [comment]
Which version is this?

**Comment by defaultsucks** [comment]
This is 1.0.9d sir.

**Comment by mbsuperstar1** [comment]
On the latest development build this has been fixed...

However a new issue has risen..they are too accurate!
Maybe a configuration default on accuracy? And an admin command to change this per guard...
I don't mean to sound like a scrub..in range they hardly miss!

**Comment by aPunch** [comment]
mb, I'm closing this issue. File another issue with the tag "Suggestion" with your suggestion.
