### ISSUE TITLE
More quest.yml config dilemmas

### ISSUE THREAD

**Issue by luigivampa** [CitizensDev/Citizens#567]
Here is the reward from 'build rights' quest in my quest.yml

```
rewards:
    '0':
        type: rank
        rank: 'user'
```

It adds the player to the user group (build: true) as it should but does not remove them from the default group (build: false).
The permissions config.yml looks like

```
luigi_vampa:
    groups:
    - default
    - user
```

If I remove the '- default' line manually it works fine but I can't figure out how to remove it from within the quest. I've tried dropping the rank node and using the command node instead but that doesn't seem to add anything to the permissions config. Some of the lines I've tried are

```
        type: command

        command: permissions removegroup <player> default (this was as a second reward after using rank node)
        command: permissions setgroup <player>  user
        command: permissions addgroup <player>  user

        server: true
```

Has anyone any ideas?
Thanks.

**Comment by luigivampa** [comment]
Edit:
Sorted it. Helps if you write the command properly in the first place.

```
        type: command
        command: permissions player setgroup <player> user
        server: false
```

**Comment by Farwaykorse** [comment]
You could use the rank reward to do this:

<pre>
rewards:
    '0':
            type: rank
            rank: default
            replace: true
            with: user
</pre>


Full rank options:

<pre>
requirements: 
    '[integer]':
            type: rank
            rank: [text rank]

rewards:
    '[integer]':
            type: rank
            rank: [text rank]
            replace: [boolean]      # optional, needs: with:
            with: [text rank]       # optional, needs: replace: true
            take: [boolean]         # optional, rewards default false, no function when replace and with are active
</pre>
