### ISSUE TITLE
Quests won't load!

### ISSUE THREAD

**Issue by MaximeJakubowski** [CitizensDev/Citizens#577]
hey,
I have downloaded the citizens plugin and i'm very happy with it,
but after a few days, when i just learned to use the questers, the quests won't load anymore!
I al ready tried to remove the last quest I've made and trieded to reinstall te plugin but the quests just won't load!

Thanks

Ps.: Sorry if my English is bad, I'm from Belgium.

Edit: I just starded a new server, problem is gone...

**Comment by Fireelf15** [comment]
If you post the text someone could help you better.

**Comment by MaximeJakubowski** [comment]
solved
