### ISSUE TITLE
Quester Issue (Development Build)

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#58]
Currently it still shows un-repeatable quests as one of those available for you to start until you right click it.

It would be a much friendlier system if it no longer showed that quest once you have completed it the required amount of times.

Also upon starting a quest it doesn't show you the objective until you type /quest status.
It'd be much smoother if it said:

Challenge Accepted.
You need to... (objective)

It would be much friendlier than requiring you to type a command every quest start.

**Comment by fullwall** [comment]
First issue should be fixed in the next commit. For the second issue, isn't this the sort of thing that should be specified in the acceptance test in quests.yml?
