### ISSUE TITLE
Item id bugs

### ISSUE THREAD

**Issue by hemirt** [CitizensDev/Citizens#589]
i created quest, collect cobblestone - heres the issue - it collect grass/dirt, but there is another step - give cobblestone to npc - in  that two cases there is itemid = 4, but only give cobblestone works, pls help

**Comment by Fireelf15** [comment]
I don't understand the "it collect grass/dirt, but there is another step" are you saying the quest is to collect dirt AND cobblestone then bring both back? If you could, please post the code you used. That would help troubleshooting a lot!

**Comment by hemirt** [comment]
"Q5 collect and deliver":
    texts:
        description: "collect 5 cobble and delivery it to NPC 1"
        completion: "here is your reward"
        acceptance: "thx for accept"
    repeats: -1
    objectives:
        '0':
            '0':
                type: collect
                materialid: 4 
                amount: 5
                optional: False
                finishhere: False
                message: "Great you colected cobble"
        '1':
            '0':
                type: delivery
                materialid: 4 
                amount: 5
                npcdestination: 1
                optional: False
                finishhere: False
                message: "thx for delivering"
    rewards:
        '0':
            type: money
            money: 5

but there is bug i want collect 4 = cobble but it collect dirt, cobble doesnt work

**Comment by Fireelf15** [comment]
Collect quests are buggy, cobblestone for instance. When you have to mine cobblestone, not smooth stone that gives you cobblestone. What I do is make it a delivery quest so you don't need to track the mining itself, just the giving.
