### ISSUE TITLE
Quester NPE

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#59]
New issue

http://dev.bukkit.org/paste/3853/

OLD ISSUE
If you logout and log back into your minecraft world, quests you have already completed the max number of times fail to remember this information. Allowing you to abuse a great rewarding quest over and over again.

**Comment by fullwall** [comment]
Which quest is this? Can you confirm it's still an issue?

**Comment by mbsuperstar1** [comment]
Cannot re-create currently.
