### ISSUE TITLE
Can no longer attack guards

### ISSUE THREAD

**Issue by charlie1990** [CitizensDev/Citizens#596]
For some reason I can't attack guards anymore, they run up and hit me and damage me but if I try and fight back nothing happens, I was able to attack guards in a previous citizens build(can't remember which one). I'm running the latest bukkit build and devBuild- version of Citizens. Can anyone help out with this? If it helps my plugins are

Vault
VoxelPort
Essentials
EssentialsSpawn
EssentialsChat
WorldGuard
WorldEdit
LogBlock
McMMO
AnCasino
BOSEconomy
Lagmeter
Nocheat
LWC
uHome
Register

I thought maybe my global worldguard flags were interfering but i removed worldguard to test that theory and it didn't change anything

**Comment by Farwaykorse** [comment]
Is this the same? https://github.com/CitizensDev/Citizens/issues/477
If so, you might want to participate in it and close this issue. (saves work for the programmers ;) )

**Comment by charlie1990** [comment]
same issue but their fix didn't help me so i wasnt sure if i should make a new one or not
