### ISSUE TITLE
Multiple Priorities!

### ISSUE THREAD

**Issue by mbsuperstar1** [CitizensDev/Citizens#61]
-5 mbsuperstar1
-10 mbsuperstar1
-a

Make -a override all other permissions? This will fix removing it removing all priorities...

Also, prevent 1 name having 2 priorities? Thanks.

**Comment by fullwall** [comment]
Won't doing -5 then -10 change the priority to 10?

**Comment by mbsuperstar1** [comment]
Nope :S

**Comment by fullwall** [comment]
You made a mistake in the command.
