### ISSUE TITLE
rank rewards - adding FromGroup parameter

### ISSUE THREAD

**Issue by Kozzy68** [CitizensDev/Citizens#662]
Hi, would it be possible to add from group rank parameter ? I like to create quest as promotion reward but I dont like promoted users to get demoted for completing it. 

Thanks

**Comment by charlie1990** [comment]
Not totally sure what you're saying here. Are you saying users with a higher rank then the quest are doing it and getting demoted? If so that's an easy fix add a requirement to the quest specifying what rank they have to be to accept it

**Comment by Kozzy68** [comment]
oooo thank you :) that will fix it for me.
