### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by xxrepresent** [CitizensDev/Citizens#671]
http://pastebin.com/6ZcULg5t

**Comment by gummby8** [comment]
Same error

http://pastebin.com/JuJjNBpp

**Comment by sandia** [comment]
I have the same

**Comment by Corwent** [comment]
generating new files fixes this.

**Comment by DreamPhreak** [comment]
Thank you corwent, i cant believe i forgot to update the files too, and your comment reminded me. :)

**Comment by xxrepresent** [comment]
I got this error when doing a clean install though. No old files or anything. Just put the .jar in my plugins folder :I
