### ISSUE TITLE
npc disapear after restart

### ISSUE THREAD

**Issue by arriej** [CitizensDev/Citizens#672]
hello,

i host my server on an internet host.
when i stop my server and restart it my npc are gone 

there is no error to see in the log file.

tnx

**Comment by dRoseMirakel** [comment]
I think cuz its like a player yet no player, since it ses player stuffs :) but no clue im having the same so I thought it might be cuz it seems to be an player.

tho I have worse problems cuz I cant seem to bribe them :P

**Comment by Thyadar** [comment]
Try to turn down the time when the plugin saves the new NPCs.
The time is set in /plugins/Citizens/citizens.yml
At the point: 
  saving:
    delay: <random number>
(Right under the pathing-part)

Try to solve the problem with dely 500 for the beginning (which is about every 30 secs, as soon
as you know that this solves you problem you can set it higher again).

Greetings

**Comment by arriej** [comment]
for a wierd reason its fixt that are standing now..

tnxx :P
