### ISSUE TITLE
Guards will not return to posts.

### ISSUE THREAD

**Issue by hqt99** [CitizensDev/Citizens#685]
Guards (bouncers) will not return to posts (spawn location) after killing a monster. Perhaps I just have the YML file wrong, however I have looked though it for 2 days thinking that this was an issue on my end. I have 1.1.4 on bukkit 1.1 R1. Everything else (that I have tried) seems to be working. 

I have:
- deleted citizens and re-installed
- deleted individual guards and re built them
- moved them manually
- changed stationary-return-ticks to different numbers
- restarted server
- checked for error messages in start up
- had some one else look at my config files so I knew i wasn't insane
- bathed a goat in chickens blood to have the Minecraft gods shine down on me

If anyone else solved this please help out. For an example you can visit server: logon.dyndns.tv there are some in the starting area.

**Comment by Telanisanna** [comment]
Have the same Problem ! They Return to there Posts if you turn them NON-Aggro  with /guard aggro !

But i hope they fix the Problem because if i have 20 City Defenders i dont wanne to turn all 20 alltime Aggro / NON-Aggro!

**Comment by hqt99** [comment]
I don't know what or why but they started working on there own. I made no changes to any files just all I have done between the time I made first post and this one is run a defrag on my server. No idea....
