### ISSUE TITLE
Guard /  bouncers / High priority

### ISSUE THREAD

**Issue by mazius123** [CitizensDev/Citizens#686]
Citizens-1.1.4

Hey  i have problem with bouncers (with one of guards types) so here is the problem:
when I make bouncer set the radius and etc... , he attack the flaged mobs but when the mob dies he didnt come back to his possition , he stuck
he come back only if he broke the seted radius. , please fix it faster and reply to me (skype:vaidas.mazius123 , or mazius123cash@inbox.lt) if you fix it or for more information.

Setting setted by me : 
'0':
  guard:
    flags:
      creeper:
        priority: '1'
        safe: 'false'
        type: MOB
      skeleton:
        priority: '3'
        safe: 'true'
        type: MOB
      karma:
        safe: 'false'
        priority: '2'
        type: GROUP
      spider:
        type: MOB
        safe: 'false'
        priority: '4'
    type: BOUNCER
    toggle: 'true'
    radius: '15.0'
    aggressive: 'true'
  basic:
    name: sargybinis
    color: f
    look-when-close: 'false'
    items: 272:0,298:0,307:0,308:0,0:0,
    location: world,-193.64081153667752,71.0,255.43724796614,179.0965,9.900123
    owner: mazius123
    inventory: 272/1/0,AIR*35,
    balance: '0.0'
    talk: 'true'
    talk-when-close: 'false'

**Comment by Telanisanna** [comment]
I think about this Problem are 3-4 open Issus plz use the open Issus and dont create allwhile a new Issus because the Developer have other Problems i think......

**Comment by mazius123** [comment]
Telanisanna , thanx for answer ;D
