### ISSUE TITLE
Trader unlimited stacks

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#69]
I'm not sure if this is just a cosmetic bug, whether it's client side or not, but my trader has a 64 stack of items that he sells and I've set his stock to unlimited. Whenever I purchase something from him the stack number still goes down. After there's just one item left it doesn't disappear so this isn't a serious problem. Just thought I'd bring it to your attention.

**Comment by fullwall** [comment]
_Might_ be fixed in latest dev builds, can you confirm/deny?

**Comment by defaultsucks** [comment]
Fixed ^.^
