### ISSUE TITLE
Money not being deducted from users accounts

### ISSUE THREAD

**Issue by kripts** [CitizensDev/Citizens#696]
I am experiencing a problem with the new update for CB 1.1 RB, When purchasing from the traders money doesnt get deducted from the player, I am using Iconomy, Its says it costs x amount yet the purchase still goes through without any problem or charge?

**Comment by aoconnell** [comment]
im also having the same issue.
bukkit 1.1 R1
pex 1.8
citizens 1.1.4
many plugins - all on latest rec builds, most on 1.1 compat versions.
have a blacksmith setup. worked fine on 1.0.1 but now doesnt charge for the repair.
everything else which uses iconomy is working fine.

**Comment by kripts** [comment]
Same, other plugins work fine just that traders dont charge, not tried the blacksmith yet

**Comment by aoconnell** [comment]
i had some other unrelated stuff happening as well. got tired trying to track problems down cos i cant just keep restarting a server with players on it. redownloaded all plugins to my desktop server, modified the new configs to match my old ones and all works ok, just copied over the plugins folder to the dedi and all is good now. if i had to guess id say it was a problem with either register or vault. now running register 1.5 and vault 1.2.6

**Comment by kripts** [comment]
Okay ill do updates, thanks for the information :)

**Comment by kripts** [comment]
Still not deducting money from the players, anyone else having this problem and found a fix? I have updated to the new Citizens still nothing

**Comment by kripts** [comment]
Still broke, I cant get the money to be deducted from the users account?

**Comment by ghost** [comment]
Having this problem still, too. Would love some clarification on it.

**Comment by kripts** [comment]
Fixed it, Seems that the Citizens Plugin clashes with ChatManager, Once removed it will now deduct money from the users.
