### ISSUE TITLE
Traders lose their buy/sell tables

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#70]
In 1.1 dev build #99 the traders lose the item buying/selling information completely. I've tried saving everything with /citizens save and then reloading, however that doesn't help.

**Comment by fullwall** [comment]
What kind of buy/sell tables are you talking about?

**Comment by defaultsucks** [comment]
If you add buy/sell information to a trader he loses it after a reload. For ex. you make it so a trader sells and buys iron ingots, diamonds, coal. He sells and buys them just fine minus the buying 2 items instead of one bug that's in a seperate issue. After you reload citizens the trader stops buying/selling everything. Saving in advance doesn't work either.

**Comment by defaultsucks** [comment]
This issue is fixed in the latest dev builds.
