### ISSUE TITLE
Guards won't use waypoints or return to their posts after combat

### ISSUE THREAD

**Issue by Darkterror67** [CitizensDev/Citizens#701]
I don't entirely know how tickets work, so I'll just put in as much information as I can. 

My server is run on craftbukkit 1.1 with the plugins AncientGates, CraftBookMechanisms, WorldEdit, Pail, PermissionsBukkit, MantaMobControl, DirtPaths, WorldGuard, NarrowtuxLib, PailPlus, dynmap, BorderGuard, AntiCreeper, TelePads, NoPortals, iConomy, Showcase, CraftBookCommon, BioMed, CraftBukkitUpToDate, mcMMO, Simple Prefix, Essentials, Citizens, EssentialsSpawn, and EssentialsChat. I just got the newest version of citizens, 1.1.4, and I reset all the old data.

When I created a Guard named 'Knavesmire/Guard', toggled him to bouncer, and gave him the flags for the mobs zombie, skeleton, spider, and the groups 'Orc', 'Goblin', and 'Outcast'. He is set to aggro and radius 10. He will attack enemies, but when he is done fighting, he will just stay where he is looking in the same direction. If they have waypoints, the same thing occurs without the combat part, they just wont move. Pathing working with all my other types of npc, and this happens with all guards.

-If this is not formatted correctly, please tell me.

**Comment by mazius123** [comment]
I have the same problem ... , i like how long you writed this text ;D

**Comment by angelofdev** [comment]
Same issue here. 
I find that when the mob outruns them they return to their original position. 
Otherwise they just stay in the spot they killed the mob.

**Comment by Darkterror67** [comment]
This issue is being closed as it was resolved in Citizens version 1.1.5.

**Comment by mazius123** [comment]
Darkterror67  thanx to you if its true ;D
