### ISSUE TITLE
Bouncer not returning to baseLocation because of unreleased Entity

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#708]
So after alot of debugging and frustration of the issue where bouncers would not move back to the baseLocation, I realized that the bouncers weren't going back because the entity targeted is dead. I don't know why the entity isn't released on death, but this modified method should do the trick.

``` java
private boolean findTarget(HumanNPC npc) 
    {
        Guard guard = npc.getType("guard");
        if (!guard.isAggressive())
            return false;
        LivingEntity entity = Targeter.findTarget(Targeter.getNearby(
                npc.getPlayer(), guard.getProtectionRadius()), npc);
        if (entity != null
                && LocationUtils.withinRange(entity.getLocation(),
                        npc.getBaseLocation(), guard.getProtectionRadius())) 
        {
            if (entity.isDead())
            {
                return false;
            }

            guard.target(entity, npc);
            return true;
        }
        return false;
    }
```

I'm leaving this open till it is fixed in the master branch.

**Comment by cryptodechange** [comment]
Worked for me. Though still having some weird issues.

1) Guards got trapped within each other and constantly looked down?
2) Guard didn't return after chain attack (killed one creeper, then moved on to another)

**Comment by ghost** [comment]
The guards will do this as a part of their pathing system. As for looking down, they also look for enemies on the Z axis to their radius value. Try setting the guards' radius lower else they will try to path their way to underground mobs.

That's quite odd that they aren't returning. I don't use the pathing system however. The pathing system is buggy and won't return to the yaw that it spawned with.

Teleporting is less realistic, but has its ups.

Try this:

`private boolean startReturning(HumanNPC npc) 
    {
        if (findTarget(npc))
          return false;
        //PathUtils.createPath(npc, npc.getBaseLocation(), -1,
                //Settings.getInt("MaxStationaryReturnTicks"));
        npc.teleport(npc.getBaseLocation());
        return true;
    }`

**Comment by cryptodechange** [comment]
Bouncers are not working at all now. Though I believe this is due to the new CraftBukkit updates https://github.com/CitizensDev/Citizens/issues/709

**Comment by ghost** [comment]
Fixed with my merge request
