### ISSUE TITLE
Citizens doesn't load Quests anymore since update to 1.1.4

### ISSUE THREAD

**Issue by Thyadar** [CitizensDev/Citizens#717]
Hey everyone.

Ive just updated Citizens to the current version on my server. Bukkit is the version which is recommended on the citizens-page (http://wiki.citizensnpcs.net/index.php?title=Main_Page).

Since then Citizens doesn't load my quests.
Ive updated strictly as the guide on the page.

Am I the only one whos having that problem or is there someone else who has the same one?
Or does anyone have a solution for that?
(My quest.yaml didn't change since the update and the yaml parser still tells me that the yaml is ok)

Thanks!
- D

**Comment by Thyadar** [comment]
Addition: This is what the console says if i type in /quest reload

20:28:16 [INFO] [Citizens] ?7Reloading...

> 20:28:16 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xFFFD) special characters are not allowed
> in "<string>", position 1370
> 
> 20:28:16 [SEVERE] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
> 
> 20:28:16 [SEVERE] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
> 
> 20:28:16 [SEVERE] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
> 
> 20:28:16 [SEVERE] at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:37)
> 
> 20:28:16 [SEVERE] at net.citizensnpcs.questers.data.QuestProperties.initialize(QuestProperties.java:13)
> 
> 20:28:16 [SEVERE] at net.citizensnpcs.questers.QuesterCommands.reloadQuests(QuesterCommands.java:221)
> 
> 20:28:16 [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> 20:28:16 [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
> 
> 20:28:16 [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
> 
> 20:28:16 [SEVERE] at java.lang.reflect.Method.invoke(Method.java:597)
> 
> 20:28:16 [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
> 
> 20:28:16 [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
> 
> 20:28:16 [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:193)
> 
> 20:28:16 [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
> 
> 20:28:16 [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
> 
> 20:28:16 [SEVERE] at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
> 
> 20:28:16 [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
> 
> 20:28:16 [SEVERE] Caused by: unacceptable character '?' (0xFFFD) special characters are not allowed
> in "<string>", position 1370
> 
> 20:28:16 [SEVERE] at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
> 
> 20:28:16 [SEVERE] at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
> 
> 20:28:16 [SEVERE] at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
> 
> 20:28:16 [SEVERE] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
> 
> 20:28:16 [SEVERE] ... 25 more
> 
> 20:28:16 [INFO] [Citizens] ?aLoaded ?e0?a quests.

**Comment by littlebaka** [comment]
I have the same error =/ 
� <=== the bad
