### ISSUE TITLE
No Quester examples

### ISSUE THREAD

**Issue by Gousby** [CitizensDev/Citizens#72]
As I am a beginner plug-ins manager, I'm not exactly sure I did something right.. But that's why I'm here. For help. 

As the wiki states, there are examples quest I can use to format a quest I create, said examples are not there. Only a "{}"

I've searched far and wide for said examples but to no avail. Where can I locate these example quest?

**Comment by havejack** [comment]
Its cause There not offcially done Just wait plz

**Comment by Gousby** [comment]
I know that. I'm waiting but just wondering if I can get a head start like other people

**Comment by aPunch** [comment]
You can get a head start by coming on IRC and asking for an example file.
