### ISSUE TITLE
Civilians Reset

### ISSUE THREAD

**Issue by dakmech9** [CitizensDev/Citizens#721]
Ok, one day I made like 20 civilians with all diffrent types of traders, then my server crashes. They all get reset. I redo them. I turn it off for school, it still resets. Why? Someone tell me how to fix this
Edit. Forgot to add its the same types of traders but just diffrent items

**Comment by dakmech9** [comment]
Creating empty config: C:\Users\UNAVAIBLE\Desktop\Minecraft Related\Bukkit\plugins\Essentials\userdata\diamonds.yml 
This is what I see in a bit after i make a NPC. The UNAVAIBLE part shows my name. Please tell me what this means?

**Comment by kripts** [comment]
I dont have this config in that directory, I would suggest that is a problem with Essentials and not with Citizens, try the Essentials Live help, located here:
http://wbe001.mibbit.com/?settings=c1051a91518990e6c1fb32ce820ba234&server=irc.esper.net&nick=EssMib_%3F%3F%3F%3F&channel=%23essentials

**Comment by dakmech9** [comment]
I FOUND IT, it wasnt essentials, after i deleted FalseBook all npcs reapeared when i restarted server i think
