### ISSUE TITLE
Talkclose Always false..

### ISSUE THREAD

**Issue by dakmech9** [CitizensDev/Citizens#722]
Everytime I do /npc talkclose true it says its true, so i walk about 10 blocks and come back, not talk. So I decide to test with 1k blocks. Still a no Why? Help me fix this!

**Comment by kripts** [comment]
just type /npc talkclose after selecting the npc, sometimes it bugs up, and a server restart is needed

**Comment by dakmech9** [comment]
Ill try but on my other Issue, when i restart they delete the npc

**Comment by kripts** [comment]
try going into your citizens.yml and looking under the save option I have mine on the default:

  saving:
    delay: 72000
    save-often: true
    use-task: true
This saves every 15 mins.

**Comment by dakmech9** [comment]
Eh, i figured it out myself, it was because of either Essentials or Falsebook im still testing it though
