### ISSUE TITLE
Freaking items bug...

### ISSUE THREAD

**Issue by douglas-srs** [CitizensDev/Citizens#727]
Hello, I'm here to report a huge bug that's is driving me crazy! Every time I login my itens are missing... All I have is the item that my NPC have! even the player that hasn't NPC's are missing itens sometime when reloging, may u fix it please? thx

**Comment by kripts** [comment]
You need to give a more detailed description, for anyone to help you with your issue, you log on and what items are missing from where? what do you mean all you have is the item that your NPC has? please provide more information.

**Comment by douglas-srs** [comment]
For example, if I have any kind of items in my inventory they gone after I login into the server! My armor, the blocks, anything that I have in inventory just miss... If the name matching my name has for example a flower in his hands, I will logon with the flower only... and in the same place that my NPC is!

Thx

**Comment by kripts** [comment]
So your saying if you name your NPC the same name as yours, it will overwrite the Items because the user configs both conflict, only way I can see possible at the moment is changing the NPC name, but im sure mine doesn't cause this problem.

**Comment by douglas-srs** [comment]
That's happening! I use authdb for authentication, do you know if there is a conflict on this?

**Comment by fullwall** [comment]
The NPC may be overwriting your handle (although we try to prevent this). Can you try without authDB perhaps?

**Comment by douglas-srs** [comment]
AuthDB Updated recently and now this issue appear to be fixed, thank you for your pacient!
:)
