### ISSUE TITLE
Splash potions turns to normal potions (traders)

### ISSUE THREAD

**Issue by mbastos** [CitizensDev/Citizens#769]
Hey there, I have an issue for you:
Ok, so, I create my trader NPC, and put a splash potion of Instant Healing 2 for selling, by now, everything okay. I can buy it when I set the owner to another people. But then, when I go away from the NPC, wait some time and then go back to him, the Splash potion is now a normal potion, yes, with Instant Healing 2, but not a splash as I let it.
Why does this happens? Can you help me please?

**Comment by fullwall** [comment]
Known issue.
