### ISSUE TITLE
NPCs disappear when I enter a world

### ISSUE THREAD

**Issue by limond** [CitizensDev/Citizens#78]
When I go into another world, and from there back into the first, then disappear many NPCs of the First World. 
- I use MultiVerse to teleport to an other world.
- I use CitizenSpout v0.1.7

Sorry for my bad english (I'm from Germany).

**Comment by defaultsucks** [comment]
Which version of citizens are you using?

**Comment by limond** [comment]
I use the version 1.0.9d.

**Comment by defaultsucks** [comment]
That's a common bug in 1.0.9d. Try out the latest dev builds. That's most likely fixed in there. I have multiverse and I'm not experiencing this problem. If it still occurs, it may be citizenspout, in which case you should post in their forum thread.

**Comment by mbsuperstar1** [comment]
CitizenSpout does not touch chunks so could not possibly cause an issue such as this.

**Comment by limond** [comment]
Now I use the latest dev build and I removed CitizenSpout and NPC-Quester but the NPCs still disappear.
