### ISSUE TITLE
[Feature Request] NPC inventories

### ISSUE THREAD

**Issue by Codisimus** [CitizensDev/Citizens#784]
I am working on adding Citizens support to my plugin Turnstile. I have everything programmed so Players can give items to the NPC in order to open the Turnstile. I tried this with Traders but only the owner can use it. For everyone else it says that the Trader is not buying that item. I just need an NPC that will act just like a Chest. Thanks for your time.

**Comment by fullwall** [comment]
Done in Citizens 2.0 (check out aPunch's github, although it won't be released for about a month most likely).

**Comment by Codisimus** [comment]
ace, I can wait a month. Thanks for your quick reply.
