### ISSUE TITLE
bPermissions not working - OP only

### ISSUE THREAD

**Issue by jasonrob77** [CitizensDev/Citizens#785]
Currently it seems citizens does not work with bPermissions, only the OP's can use any citizens commands. I am certain this is not a problem with my bPermissions config files as I have rewrote them several times. Other plug-ins work with bpermissions.
- I have tried disabling all other plugins
- I have upgraded to the latest dev craftbukkit: 1.1-R4-20120207.011818-41
- I have bpermissions 2.8.3
- I have citizens 1.1.5
- I have replaced the citizens and bpermissions jars (including the characters) several times.

Any help would be appreciated, I am going to try and change to PEX (which I really don't want to do).

**Comment by jasonrob77** [comment]
Changed to Permissionsbukkit, works fine. Compatibility problem with bPermissions and Citizens then (or something)

**Comment by charlie1990** [comment]
theres no compatibility problem i use bpermissions with citizens just fine, you just have something put in wrong

**Comment by jasonrob77** [comment]
Pah I refuse to believe this ;)

Cheers anyway
