### ISSUE TITLE
Double of every citizens/npc

### ISSUE THREAD

**Issue by Loserman778** [CitizensDev/Citizens#787]
Hey guys,

   A while ago i removed citizens because of conflicts. Now, i removed the other plugin from the server and re-implemented citizens. Now the problem i have is that citizens now has 2 of every NPC that i made. I'm not sure why. And on top of that, i cannot select the NPCs at all. Thanks in advanced

-Loserman778

**Comment by EHAndrew** [comment]
use /citizens clean

im having this same issue, plus some. this solves the cannot-select bug

**Comment by jenks1999** [comment]
perfect advice EHAndrew it solved my issue instantly. TY this issue should be closed?

**Comment by EHAndrew** [comment]
I dont have the issue anymore, but when I was, I had set MCMA to run /citizens clean every 5 minutes. It doesn't lag.
