### ISSUE TITLE
Citizens failed to pass event CHUNK_UPLOAD

### ISSUE THREAD

**Issue by Spongy2018** [CitizensDev/Citizens#79]
i get on my serve with no errors at all with anything and all my plugins work. Once someone quits tho i get this stupid error and i have no idea how to fix it. Please help me?! Here is the error 

18:03:09 [INFO] [BetterShop] Notice: Unused Configuration Nodes:
strings.commandlog, strings.listalias
18:03:09 [INFO] [BetterShop] Newer BetterShop version found on git (Sat Sep 03 0
2:09:14 EDT 2011)
18:03:09 [INFO] [BetterShop] BetterShop.csv loaded.
18:03:09 [INFO] [BetterShop] Attached to iConomy.
18:03:09 [INFO] [BetterShop] Attached to Permissions.
18:03:09 [INFO] [BetterShop] 'Help' support enabled.
18:03:09 [INFO] BetterShop version 1.6.6.6 is enabled!
18:03:09 [INFO] [ChopTree] Using Permissions.
18:03:09 [INFO] ChopTree 1.23 enabled!
18:03:09 [INFO] Loading ColoredSigns
18:03:09 [INFO] DreamLand version 2.4 is enabled!
18:03:09 [INFO] [HELP] 0 extra help entries loaded
18:03:09 [INFO] [HELP] Permissions enabled using: Permissions v2.7.7
18:03:09 [INFO] [HELP] 0.3.2 enabled
18:03:10 [INFO] [HeroicDeath] 1.9.1 enabled.
18:03:10 [INFO] [iConomy] Logging is currently disabled.
18:03:10 [INFO] [iConomy] v5.01 (Eruanna) loaded.
18:03:10 [INFO] [iConomy] Developed by: [Nijikokun]
18:03:10 [INFO] [iQuest] Loaded with Flatfile!
18:03:10 [INFO] iQuest v3.2.0,created by sddddgjd, enabled! With 53 quests loade
d!
18:03:10 [INFO] [jChat] Loaded configuration: plugins\jChat\config.yml
18:03:10 [INFO] [jChat] External permissions system found: Permissions v2.7.7
18:03:10 [INFO] [jChat] jChat v1.1.3 is enabled!
18:03:10 [INFO] Lockette version 1.3.8 is being enabled!  Yay!  (Core version 1.
0)
18:03:10 [INFO] Lockette: Detected craftbukkit build [1060] ok.
18:03:10 [INFO] [SuperpermBridge] Superperm/Permissions bridge enabled
18:03:10 [INFO] [iConomy] hooked into Permissions.
18:03:10 [INFO] Lockette: Linked to Permissions plugin version 2.7.7
18:03:10 [INFO] Lockette: Using ops file for admin permissions.
18:03:10 [INFO] Lockette: Ready to protect your containers.
18:03:10 [INFO] Memory max: 1070399488 bytes
18:03:10 [INFO] Memory total: 329310208 bytes
18:03:10 [INFO] Remote Toolkit Plugin V0.45b enabled!
18:03:10 [INFO] [MobDisguise] by desmin88 version 1.6 enabled.
18:03:10 [INFO] Version: 62
18:03:10 [INFO] [NarrowtuxLib] v0.6.2 by [narrowtux] enabled.
18:03:10 [INFO] [NarrowtuxLib] Payment method found (iConomy version: 5)
18:03:10 [INFO] ScheduledAnnouncer v1.7.0 is enabled!

18:03:10 [INFO] [ServerSave] Save interval is: 600 seconds.
18:03:10 [INFO] [ServerSave] ServerSave enabled!
18:03:12 [INFO] Spout 1.0.5.227 has been initialized
18:03:12 [INFO] SpoutEssentials v3.4 is enabled!
18:03:12 [INFO] SpoutEssentials: WorldGuard Module disabled
18:03:12 [INFO] SpoutEssentials: BOSEeconomy module disabled
18:03:12 [INFO] SpoutEssentials: MobDisguise module disabled
18:03:12 [INFO] [SpoutEssentials] Initiating auto-update...
18:03:12 [INFO] [SpoutEssentials] You already have the latest version of SpoutEs
sentials.
18:03:12 [INFO] Found and will use plugin Permissions v2.7.7
18:03:12 [INFO] Stackable: Configuration file loaded.
18:03:12 [INFO] Stackable: Version 0.5.1 enable.
18:03:12 [INFO] WorldEdit 4.6 enabled.
18:03:12 [INFO] WorldEdit: Permissions plugin detected! Using Permissions plugin
 for permissions.
18:03:12 [INFO] WorldGuard: Permissions plugin detected! Using Permissions plugi
n for permissions.
18:03:12 [INFO] WorldGuard: (world_main) Single session is enforced.
18:03:12 [INFO] WorldGuard: (world_main) TNT ignition is blocked.
18:03:12 [INFO] WorldGuard: (world_main) Lighters are blocked.
18:03:12 [INFO] WorldGuard: (world_main) Lava fire is PERMITTED.
18:03:12 [INFO] WorldGuard: (world_main) Fire spread is UNRESTRICTED.
18:03:12 [INFO] WorldGuard: Loaded configuration for world 'world_main"
18:03:12 [INFO] WorldGuard: (world_main_nightmare) Single session is enforced.
18:03:12 [INFO] WorldGuard: (world_main_nightmare) TNT ignition is blocked.
18:03:12 [INFO] WorldGuard: (world_main_nightmare) Lighters are blocked.
18:03:12 [INFO] WorldGuard: (world_main_nightmare) Lava fire is PERMITTED.
18:03:12 [INFO] WorldGuard: (world_main_nightmare) Fire spread is UNRESTRICTED.
18:03:12 [INFO] WorldGuard: Loaded configuration for world 'world_main_nightmare
"
18:03:12 [INFO] WorldGuard: (world_main_skylands) Single session is enforced.
18:03:12 [INFO] WorldGuard: (world_main_skylands) TNT ignition is blocked.
18:03:12 [INFO] WorldGuard: (world_main_skylands) Lighters are blocked.
18:03:12 [INFO] WorldGuard: (world_main_skylands) Lava fire is PERMITTED.
18:03:12 [INFO] WorldGuard: (world_main_skylands) Fire spread is UNRESTRICTED.
18:03:12 [INFO] WorldGuard: Loaded configuration for world 'world_main_skylands"

18:03:12 [INFO] WorldGuard: Unable to register missing event type SNOW_FORM
18:03:12 [INFO] WorldGuard 5.2.2 enabled.
18:03:12 [INFO] [xAuth] 'Help' support enabled
18:03:12 [INFO] [xAuth] 'Permissions' v2.7.7 support enabled!
18:03:12 [INFO] [xAuth] Connection to database established!
18:03:13 [INFO] [xAuth] Accounts: 7, Sessions: 1
18:03:13 [INFO] [xAuth] v2.0b4.1 Enabled!
18:03:13 [INFO] [Citizens] Loaded 0 quests.
18:03:13 [INFO] [Citizens] Permissions enabled.
18:03:13 [INFO] [Citizens] version [1.0.9d](Odyssey) loaded
18:03:13 [INFO] [Citizens] Payment method found (iConomy version: 5)
18:03:13 [INFO] PermissionsBukkit v1.2 is now enabled
18:03:14 [INFO] [Jobs v2.4.6] has been enabled succesfully.
18:03:14 [INFO] [Jobs] Successfully linked with iConomy 5.
18:03:14 [INFO] [Jobs] Successfully linked with Permissions.
18:03:14 [INFO] [SpoutBackpack] Permissions found, will use it.
18:03:14 [INFO] [SpoutBackpack] Version 1.9.5 is now enabled.
18:03:14 [INFO] [SpoutBackpack] Inventories loaded.
18:03:14 [INFO] [SpoutBackpack] Payment method found (iConomy v5).
18:03:14 [INFO] Server permissions file permissions.yml is empty, ignoring it
18:03:14 [INFO] Reload complete.
18:03:14 [WARNING] Can't keep up! Did the system time change, or is the server o
verloaded?
18:03:14 [INFO] [Citizens] Loaded 8 NPCs.
18:03:15 [INFO] [iQuest] Successfully linked with iConomy.
18:03:15 [INFO] [iQuest] Successfully linked with Permissions.

> reload
> 18:06:42 [INFO] BetterShop now unloaded
> 18:06:42 [INFO] [ChopTree] Saving changes...
> 18:06:42 [INFO] [ChopTree] Saved changes.
> 18:06:42 [INFO] ChopTree disabled!
> 18:06:42 [INFO] Unloading ColoredSigns
> 18:06:42 [INFO] DreamLand version 2.4 is disabled!
> 18:06:42 [INFO] [HELP] disabled
> 18:06:42 [INFO] [HeroicDeath] 1.9.1 disabled.
> 18:06:42 [INFO] [iConomy] Plugin disabled.
> 18:06:42 [INFO] [NarrowtuxLib] Payment method was disabled. No longer accepting
> payments.
> 18:06:42 [INFO] [Citizens] Payment method disabled.
> 18:06:42 [INFO] Saving all players quests to file...
> 18:06:42 [INFO] [iQuest] Done saving.
> 18:06:42 [INFO] iQuest v3.2.0,created by sddddgjd, disabled!
> 18:06:42 [INFO] [jChat] jChat is disabled
> 18:06:42 [INFO] Lockette: Closing all automatic doors.
> 18:06:42 [INFO] Remote Toolkit Plugin V0.45b disabled!
> 18:06:42 [INFO] [MobDisguise] by desmin88 version 1.6 disabled.
> 18:06:42 [INFO] [NarrowtuxLib] v0.6.2 by [narrowtux] disabled.
> 18:06:42 [INFO] ScheduledAnnouncer v1.7.0 is disabled!

18:06:42 [INFO] [ServerSave] ServerSave disabled!
18:06:42 [INFO] SpoutEssentials has been disabled. Bye bye!
18:06:42 [INFO] Stackable: Version 0.5.1 disable.
18:06:42 [INFO] WorldEdit: Permissions plugin detected! Using Permissions plugin
 for permissions.
18:06:42 [INFO] WorldGuard: Permissions plugin detected! Using Permissions plugi
n for permissions.
18:06:42 [INFO] WorldGuard 5.2.2 disabled.
18:06:42 [INFO] [xAuth] v2.0b4.1 Disabled!
18:06:42 [INFO] [Citizens] version [1.0.9d](Odyssey) disabled
18:06:42 [INFO] PermissionsBukkit v1.2 is now disabled
18:06:42 [INFO] [Jobs v2.4.6] has been disabled succesfully.
18:06:42 [INFO] [SpoutBackpack] Saving all inventories.
18:06:42 [INFO] [SpoutBackpack] Is now disabled.
18:06:42 [INFO] [SuperpermBridge] Superperm/Permissions bridge initialized
18:06:43 [INFO] Loading BetterShop version 1.6.6.6 ...
18:06:43 [INFO] [BetterShop] Notice: Unused Configuration Nodes:
strings.commandlog, strings.listalias
18:06:44 [INFO] [BetterShop] Newer BetterShop version found on git (Sat Sep 03 0
2:09:14 EDT 2011)
18:06:44 [INFO] [BetterShop] BetterShop.csv loaded.
18:06:44 [INFO] [BetterShop] Attached to iConomy.
18:06:44 [INFO] [BetterShop] Attached to Permissions.
18:06:44 [INFO] [BetterShop] 'Help' support enabled.
18:06:44 [INFO] BetterShop version 1.6.6.6 is enabled!
18:06:44 [INFO] [ChopTree] Using Permissions.
18:06:44 [INFO] ChopTree 1.23 enabled!
18:06:44 [INFO] Loading ColoredSigns
18:06:44 [INFO] DreamLand version 2.4 is enabled!
18:06:44 [INFO] [HELP] 0 extra help entries loaded
18:06:44 [INFO] [HELP] Permissions enabled using: Permissions v2.7.7
18:06:44 [INFO] [HELP] 0.3.2 enabled
18:06:44 [INFO] [HeroicDeath] 1.9.1 enabled.
18:06:45 [INFO] [iConomy] Logging is currently disabled.
18:06:45 [INFO] [iConomy] v5.01 (Eruanna) loaded.
18:06:45 [INFO] [iConomy] Developed by: [Nijikokun]
18:06:45 [INFO] [iQuest] Loaded with Flatfile!
18:06:45 [INFO] iQuest v3.2.0,created by sddddgjd, enabled! With 53 quests loade
d!
18:06:45 [INFO] [jChat] Loaded configuration: plugins\jChat\config.yml
18:06:45 [INFO] [jChat] External permissions system found: Permissions v2.7.7
18:06:45 [INFO] [jChat] jChat v1.1.3 is enabled!
18:06:45 [INFO] Lockette version 1.3.8 is being enabled!  Yay!  (Core version 1.
0)
18:06:45 [INFO] Lockette: Detected craftbukkit build [1060] ok.
18:06:45 [INFO] [SuperpermBridge] Superperm/Permissions bridge enabled
18:06:45 [INFO] [iConomy] hooked into Permissions.
18:06:45 [INFO] Lockette: Linked to Permissions plugin version 2.7.7
18:06:45 [INFO] Lockette: Using ops file for admin permissions.
18:06:45 [INFO] Lockette: Ready to protect your containers.
18:06:45 [INFO] Memory max: 1070399488 bytes
18:06:45 [INFO] Memory total: 329310208 bytes
18:06:45 [INFO] Remote Toolkit Plugin V0.45b enabled!
18:06:45 [INFO] [MobDisguise] by desmin88 version 1.6 enabled.
18:06:45 [INFO] [NarrowtuxLib] v0.6.2 by [narrowtux] enabled.
18:06:45 [INFO] Version: 62
18:06:45 [INFO] [NarrowtuxLib] Payment method found (iConomy version: 5)
18:06:45 [INFO] ScheduledAnnouncer v1.7.0 is enabled!

18:06:45 [INFO] [ServerSave] Save interval is: 600 seconds.
18:06:45 [INFO] [ServerSave] ServerSave enabled!
18:06:46 [INFO] Spout 1.0.5.227 has been initialized
18:06:46 [INFO] SpoutEssentials v3.4 is enabled!
18:06:46 [INFO] SpoutEssentials: WorldGuard Module disabled
18:06:46 [INFO] SpoutEssentials: BOSEeconomy module disabled
18:06:46 [INFO] SpoutEssentials: MobDisguise module disabled
18:06:46 [INFO] [SpoutEssentials] Initiating auto-update...
18:06:46 [INFO] [SpoutEssentials] You already have the latest version of SpoutEs
sentials.
18:06:46 [INFO] Found and will use plugin Permissions v2.7.7
18:06:46 [INFO] Stackable: Configuration file loaded.
18:06:46 [INFO] Stackable: Version 0.5.1 enable.
18:06:46 [INFO] WorldEdit 4.6 enabled.
18:06:46 [INFO] WorldEdit: Permissions plugin detected! Using Permissions plugin
 for permissions.
18:06:46 [INFO] WorldGuard: Permissions plugin detected! Using Permissions plugi
n for permissions.
18:06:46 [INFO] WorldGuard: (world_main) Single session is enforced.
18:06:46 [INFO] WorldGuard: (world_main) TNT ignition is blocked.
18:06:46 [INFO] WorldGuard: (world_main) Lighters are blocked.
18:06:46 [INFO] WorldGuard: (world_main) Lava fire is PERMITTED.
18:06:46 [INFO] WorldGuard: (world_main) Fire spread is UNRESTRICTED.
18:06:46 [INFO] WorldGuard: Loaded configuration for world 'world_main"
18:06:46 [INFO] WorldGuard: (world_main_nightmare) Single session is enforced.
18:06:46 [INFO] WorldGuard: (world_main_nightmare) TNT ignition is blocked.
18:06:46 [INFO] WorldGuard: (world_main_nightmare) Lighters are blocked.
18:06:46 [INFO] WorldGuard: (world_main_nightmare) Lava fire is PERMITTED.
18:06:46 [INFO] WorldGuard: (world_main_nightmare) Fire spread is UNRESTRICTED.
18:06:46 [INFO] WorldGuard: Loaded configuration for world 'world_main_nightmare
"
18:06:46 [INFO] WorldGuard: (world_main_skylands) Single session is enforced.
18:06:46 [INFO] WorldGuard: (world_main_skylands) TNT ignition is blocked.
18:06:46 [INFO] WorldGuard: (world_main_skylands) Lighters are blocked.
18:06:46 [INFO] WorldGuard: (world_main_skylands) Lava fire is PERMITTED.
18:06:46 [INFO] WorldGuard: (world_main_skylands) Fire spread is UNRESTRICTED.
18:06:46 [INFO] WorldGuard: Loaded configuration for world 'world_main_skylands"

18:06:46 [INFO] WorldGuard: Unable to register missing event type SNOW_FORM
18:06:47 [INFO] WorldGuard 5.2.2 enabled.
18:06:47 [INFO] [xAuth] 'Help' support enabled
18:06:47 [INFO] [xAuth] 'Permissions' v2.7.7 support enabled!
18:06:47 [INFO] [xAuth] Connection to database established!
18:06:47 [INFO] [xAuth] Accounts: 7, Sessions: 1
18:06:47 [INFO] [xAuth] v2.0b4.1 Enabled!
18:06:47 [INFO] [Citizens] Loaded 0 quests.
18:06:47 [INFO] [Citizens] Permissions enabled.
18:06:47 [INFO] [Citizens] version [1.0.9d](Odyssey) loaded
18:06:47 [INFO] [Citizens] Payment method found (iConomy version: 5)
18:06:47 [INFO] PermissionsBukkit v1.2 is now enabled
18:06:48 [INFO] [Jobs v2.4.6] has been enabled succesfully.
18:06:48 [INFO] [Jobs] Successfully linked with iConomy 5.
18:06:48 [INFO] [Jobs] Successfully linked with Permissions.
18:06:48 [INFO] [SpoutBackpack] Permissions found, will use it.
18:06:48 [INFO] [SpoutBackpack] Version 1.9.5 is now enabled.
18:06:48 [INFO] [SpoutBackpack] Inventories loaded.
18:06:48 [INFO] [SpoutBackpack] Payment method found (iConomy v5).
18:06:48 [INFO] Server permissions file permissions.yml is empty, ignoring it
18:06:48 [INFO] Reload complete.
18:06:48 [WARNING] Can't keep up! Did the system time change, or is the server o
verloaded?
18:06:48 [INFO] [Citizens] Loaded 8 NPCs.
18:06:50 [INFO] [iQuest] Successfully linked with iConomy.
18:06:50 [INFO] [iQuest] Successfully linked with Permissions.
18:07:17 [INFO] [Citizens] Creating new config file at plugins/Citizens/Player P
rofiles/Troy.yml.
18:07:17 [INFO] Troy [/192.168.1.150:25028] logged in with entity id 260 at ([wo
rld_main] 5.5, 65.62000000476837, 3.5)
18:08:31 [INFO] Connection reset
18:08:31 [INFO] Troy lost connection: disconnect.quitting
18:08:32 [SEVERE] Could not pass event CHUNK_UNLOAD to Citizens
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boole
an
        at com.citizens.SettingsManager$Constant.toBoolean(SettingsManager.java:
150)
        at com.citizens.utils.Messaging.debug(Messaging.java:68)
        at com.citizens.listeners.WorldListen.onChunkUnload(WorldListen.java:42)

```
    at org.bukkit.plugin.java.JavaPluginLoader$50.execute(JavaPluginLoader.j
```

ava:591)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:338)
        at net.minecraft.server.ChunkProviderServer.unloadChunks(ChunkProviderSe
rver.java:243)
        at net.minecraft.server.World.doTick(World.java:1719)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
18:08:32 [SEVERE] Could not pass event CHUNK_UNLOAD to Citizens
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boole
an
        at com.citizens.SettingsManager$Constant.toBoolean(SettingsManager.java:
150)
        at com.citizens.utils.Messaging.debug(Messaging.java:68)
        at com.citizens.listeners.WorldListen.onChunkUnload(WorldListen.java:42)

```
    at org.bukkit.plugin.java.JavaPluginLoader$50.execute(JavaPluginLoader.j
```

ava:591)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:338)
        at net.minecraft.server.ChunkProviderServer.unloadChunks(ChunkProviderSe
rver.java:243)
        at net.minecraft.server.World.doTick(World.java:1719)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by aPunch** [comment]
delete config files and let them regenerate
