### ISSUE TITLE
Feature: boolean isNPC(Player) method

### ISSUE THREAD

**Issue by daemitus** [CitizensDev/Citizens#80]
A comment was received about letting NPCs use Lockette/Deadbolt protected doors. If this sort of functionality is available already (I didnt see it) or you could add it, it would be appreciated.

**Comment by daemitus** [comment]
Apparently its all in CitizensManager, Ill take a stroll through that API and see what I can do.
-edit
the API isnt built with the jar? 
Trying to use com.citizens.npcs.NPCManager.isNPC(player) directly.

**Comment by aPunch** [comment]
net.citizensnpcs.api.CitizensManager in 1.1

**Comment by daemitus** [comment]
I guess thats why I couldnt find the API package in the current distro. Thanks
