### ISSUE TITLE
NPCs in /mvwho

### ISSUE THREAD

**Issue by krisdestruction** [CitizensDev/Citizens#826]
NPCs are conflicting with MV2 when mv's /mvwho is used. It is expected that when /mvwho is used, only players are shown.

**Comment by charlie1990** [comment]
I honestly think this is a multiverse bug not Citizens, either way this is pretty  well known, same thing goes for npc names showing up in the tab list when you move one of them

**Comment by krisdestruction** [comment]
Well I submitted to both. It's a problem whether or not it's common or not.

**Comment by krisdestruction** [comment]
Known issue by MV.
https://github.com/Multiverse/Multiverse-Core/issues/501
