### ISSUE TITLE
Not working with new bPermissions API

### ISSUE THREAD

**Issue by penorzilla** [CitizensDev/Citizens#862]
This needs to be updated so it can work with the new bPermissions API that was recently updated.

**Comment by l1amm** [comment]
You volunteering for the job? Good luck, dev seems REALLY inactive.

**Comment by Fureniku** [comment]
The entire project has been taken over by a new team who're working on a rewrite.

I'd suggest staying on a lower build of bPerms until they release. You can watch the wiki for a rough timeframe (I assume as they do the new pages they've got the relevant parts recoded)

**Comment by fullwall** [comment]
Should be fixed with switch to vault. By the way @Flenix there is no 'new team', the github tracker is just unwieldy.

**Comment by Fureniku** [comment]
Aaah, I was looking at the authors on the wiki and didn't see either of your names.. and as you hadn't been posting here in a while I assumed you had stopped for some reason? maybe I just missed them?
