### ISSUE TITLE
Guards Won't Attack?

### ISSUE THREAD

**Issue by LOLJaein** [CitizensDev/Citizens#867]
I've looked up youtube videos and everything but for some reason my guard wont attack enemy mobs. Even though I addflag them.
These are the commands i started with
/npc create Tim
/toggle guard
/guard bouncer
/guard radius 20
/guard af -m creeper

Spawned a creeper and he won't attack it.
He won't even attack the skeletons that shoot him

**\*  Sorry I fixed it! I didn't realize aggro was defaultly toggled off.
/guard aggro
Then it started mowing down everything. My bad

**Comment by l1amm** [comment]
LOLJaein, Can you close this issue please ??
