### ISSUE TITLE
Can't equip NPCs created in other worlds

### ISSUE THREAD

**Issue by DSoM** [CitizensDev/Citizens#869]
When I try to equip any NPC in a world rather than my main one, It won't use items I give. I thought it was some configuration matter, but I found no option to correct it.

Is this a kind of bug or something?

Thanks in advance for any help.

**Comment by l1amm** [comment]
Works fine for me, once again another pointless issue to drown out the ones that actually matter.

**Comment by DSoM** [comment]
Pointless issue? I'd never post this if it never had happened to me, and I didn't find any similar issue.

Today I found out that my NPCs were actually equiped, the equipment just didn't show up imediately as usual.
Thanks for the help, Diabloste.
