### ISSUE TITLE
Update from 1.0.9d to latest dev build

### ISSUE THREAD

**Issue by PaulTT88** [CitizensDev/Citizens#93]
Produced http://errorreport.citizensnpcs.net/?i=127 once it hit 16GB ram used.

http://nottingham.taylor-family.me.uk/ramwtf.png <-- I tried taking a full snapshot to get proper stacks but it kept crashing quicker than it'd build the snapshot.

Also seems to have made my npc-profiles.yml over 550mb in size...

http://errorreport.citizensnpcs.net/npc-profiles.txt <- pastebin didn't want a paste that size, so there's what it did with my npc-profiles.yml

Maybe make it wipe all waypoint data from previous npc-profiles.yml? Rather re-add the waypoints than have to start from scratch entirely, or have issues like this.

**Comment by defaultsucks** [comment]
That's exactly what happened to me. Look at my issue. It's called "Reloading with command waypoint spam".
