### ISSUE TITLE
trader drops item holded in hand

### ISSUE THREAD

**Issue by agronm** [CitizensDev/Citizens#94]
How to do it:
open trade panel
fast click on item holded in hand and turn to YOUR inventory
If you do it fast enough -> npc drops item.

**Comment by defaultsucks** [comment]
Which version of citizens is this on?

**Comment by agronm** [comment]
1.0.9d

**Comment by defaultsucks** [comment]
Switch to a dev build and try this. It may be fixed.

**Comment by agronm** [comment]
how can i download it?

**Comment by defaultsucks** [comment]
http://jenkins.citizensnpcs.net:81/job/Citizens/

Download the latest build. Back up your current citizens.jar and citizens folder, put the new citizens.jar in your plugins, start and stop the server to let it make a new folder, put all the other jar files in the citizens/types folder.
