### ISSUE TITLE
NullPointerExeption when guard is set to bouncer!

### ISSUE THREAD

**Issue by psychofad** [CitizensDev/Citizens#949]
I am using Craftbukkit 1.2.4 build # 2117
Citizens 1.1.6 dev build #47
PermissionsBukkit 1.6
Vault 1.2.13-b148

I created a guard...set him to aggro and he still does not move.  I have added all the flags for the mobs, everything appears to be configured correctly.  I tried a server restart and get the following error:

22:31:43 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
        at net.milkbowl.vault.permission.plugins.Permission_PermissionsBukkit.getPlayerGroups(Permission_PermissionsBukkit.java:200)
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:522)
        at net.citizensnpcs.permissions.PermissionManager.getGroups(PermissionManager.java:105)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:99)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:142)
        at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:33)
        at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:57)
        at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
        at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
        at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
        at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
        at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
        at com.bergerkiller.bukkit.nolagg.examine.TimedWrapper.run(TimedWrapper.java:20)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

**Comment by psychofad** [comment]
Update:

Using the following:
Citizens 1.1.6 dev build #49
Craftbukkit 1.2.4 R1.0 build # 2126

Same issues!  Is there a fix for this in the works?  Am I the only one experiencing this?

**Comment by bloodriot** [comment]
Can you please post your permissions files.
It sounds like you have nothing defined for the groups which could cause a null pointer.

**Comment by psychofad** [comment]
Ok...here goes...(I really need to clean some of the entries out of here from old plugins)

users:
  GrimmRecker:
    groups:
    - Builder
  EliMe74:
    groups:
    - Builder
  PsychoFad:
    groups:
    - SupremeRuler
  Collinwins:
    groups:
    - Builder
  Jacobbdoc:
    groups:
    - Builder
  TheTacoWins:
    groups:
    - Builder
  grimmlogo:
    groups:
    - default
    - Builder
  PsychoTester:
    groups:
    - Builder
    permissions:
      nolagg.clear: true
      nolagg.gc: true
groups:
  SupremeRuler:
    permissions:
      scrollingmenusign.denied: false
      permissions.build: true
      skinselector.Admin: true
      capeselector.Adminc: true
      capeselector.use: true
      skinselector.use: true
      spoutflight.fly: true
      spoutflight.nofalldmg: true
      myworlds.world.delete: true
    inheritance:
    - admin
  Mod:
    permissions:
      bukkit.command.ban: true
      bukkit.command.ban.ip: true
      bukkit.command.ban.player: true
      bukkit.command.gamemode: true
      bukkit.command.kick: true
      bukkit.command.unban: true
      bukkit.command.unban.ip: true
      bukkit.command.unban.player: true
      essentials.ban: true
      essentials.ban.notify: true
      essentials.banip: true
      essentials.broadcast: true
      essentials.clearinventory: true
      essentials.delwarp: true
      essentials.eco.loan: true
      essentials.ext: true
      essentials.getpos: true
      essentials.helpop.recieve: true
      essentials.home.others: true
      essentials.invsee: true
      essentials.jails: true
      essentials.jump: true
      essentials.kick: true
      essentials.kick.notify: true
      essentials.kill: true
      essentials.mute: true
      essentials.nick.others: true
      essentials.realname: true
      essentials.setwarp: true
      essentials.signs.create._: true
      essentials.signs.break._: true
      essentials.spawner: true
      essentials.thunder: true
      essentials.time: true
      essentials.time.set: true
      essentials.protect.alerts: true
      essentials.protect.admin: true
      essentials.protect.ownerinfo: true
      essentials.ptime: true
      essentials.ptime.others: true
      essentials.togglejail: true
      essentials.top: true
      essentials.tp: false
      essentials.tphere: false
      essentials.tppos: false
      essentials.tptoggle: false
      essentials.unban: true
      essentials.unbanip: true
      essentials.weather: true
      essentials.whois: true
      essentials.world: true
      groupmanager.listgroups: true
      groupmanager.mandemote: true
      groupmanager.manpromote: true
      groupmanager.manselect: true
      groupmanager.manuadd: true
      groupmanager.manudel: true
      groupmanager.manwhois: true
      groupmanager.notify.other: true
      warpz0r.warp: true
      warpz0r.set: true
      warpz0r.setcost: true
      warpz0r.remove: true
      warpz0r.list: true
      warpz0r.worldwarp: true
      warpz0r.use.warp: true
      warpz0r.sethome: true
      warpz0r.home: true
      warpz0r.worldhome: true
      warpz0r.bedhome: true
      warpz0r.use.home: true
      warpz0r.compasshome: true
      warpz0r.compassreset: true
      warpz0r.compasswarp: true
      warpz0r.use.compass: true
      warpz0r.use: true
      warpz0r.admin.warpto: true
      warpz0r.admin.sethome: true
      warpz0r.admin.home: true
      warpz0r.admin.clearhome: true
      warpz0r.admin: true
      warpz0r.free.warp: true
      warpz0r.free.setwarp: true
      warpz0r.free.removewarp: true
      warpz0r.free.sethome: true
      warpz0r.free.home: true
      warpz0r.free.bedhome: true
      warpz0r.free: true
      wormhole.use.sign: true
      wormhole.use.dialer: true
      wormhole.use.compass: true
      permissions.build: true
  default:
    permissions:
      bukkit.broadcast.user: true
      bukkit.command.kill: false
      essentials.help: true
      essentials.helpop: true
      essentials.list: true
      essentials.motd: true
      essentials.rules: true
      essentials.spawn: true
      groupmanager.notify.self: true
      warpz0r.warp: true
      warpz0r.set: true
      warpz0r.setcost: true
      warpz0r.remove: true
      warpz0r.list: true
      warpz0r.worldwarp: true
      warpz0r.use.warp: true
      warpz0r.sethome: true
      warpz0r.home: true
      warpz0r.worldhome: true
      warpz0r.bedhome: true
      warpz0r.use.home: true
      warpz0r.compasshome: true
      warpz0r.compassreset: true
      warpz0r.compasswarp: true
      warpz0r.use.compass: true
      warpz0r.use: true
      warpz0r.admin.warpto: true
      warpz0r.admin.sethome: true
      warpz0r.admin.home: true
      warpz0r.admin.clearhome: true
      warpz0r.admin: true
      warpz0r.free.warp: true
      warpz0r.free.setwarp: true
      warpz0r.free.removewarp: true
      warpz0r.free.sethome: true
      warpz0r.free.home: true
      warpz0r.free.bedhome: true
      warpz0r.free: true
      mcmmo._: true
      mcmmo.tools._: true
      mcmmo.ability._: true
      mcmmo.item._: true
      mcmmo.regeneration: true
      mcmmo.motd: true
      mcmmo.commands._: true
      mcmmo.chat._: true
      mcmmo.skills._: true
      wormhole.use.sign: true
      wormhole.use.dialer: true
      wormhole.use.compass: true
      permissions.build: true
  Builder:
    permissions:
      bukkit.command.time: true
      bukkit.command.time.add: true
      bukkit.command.time.set: true
      capeselector.Builderc: true
      capeselector.use: true
      chestsync.access.self: true
      chestsync.destroy.self: true
      chestsync.make.self: true
      dt._: true
      dt.travel: true
      essentials.afk: true
      essentials.back: true
      essentials.back.ondeath: true
      essentials.balance: true
      essentials.balance.others: true
      essentials.balancetop: true
      essentials.chat.color: true
      essentials.chat.question: true
      essentials.chat.shout: true
      essentials.compass: true
      essentials.depth: true
      essentials.help: true
      essentials.help._: true
      essentials.home: true
      essentials.ignore: true
      essentials.item: false
      essentials.kit: true
      essentials.kit.tools: true
      essentials.mail: true
      essentials.mail.send: true
      essentials.me: true
      essentials.msg: true
      essentials.motd: true
      essentials.nick: true
      essentials.pay: true
      essentials.ping: true
      essentials.powertool: true
      essentials.protect: true
      essentials.sethome: true
      essentials.signs.break.disposal: true
      essentials.signs.break.mail: true
      essentials.signs.break.protection: true
      essentials.signs.break.trade: true
      essentials.signs.create.disposal: true
      essentials.signs.create.mail: true
      essentials.signs.create.protection: true
      essentials.signs.create.trade: true
      essentials.signs.use._: true
      essentials.suicide: true
      essentials.time: true
      essentials.time.set: true
      essentials.tpa: true
      essentials.tpaccept: true
      essentials.tpahere: true
      essentials.tpdeny: true
      essentials.weather: true
      essentials.warp: false
      essentials.warp.list: false
      essentials.worth: true
      multiverse.access._: true
      multiverse.portal.access._: true
      myworlds.world.load: true
      myworlds.world.unload: true
      permissions.build: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: true
      scrollingmenusign.scroll: true
      scrollingmenusign.use.map: true
      scrollingmenusign.use.redstone: true
      scrollingmenusign.use.sign: true
      skinselector.Builder: true
      skinselector.use: true
      spoutflight.fly: true
      spoutflight.nofalldmg: true
      warpz0r.admin: true
      warpz0r.admin.clearhome: true
      warpz0r.admin.home: true
      warpz0r.admin.sethome: true
      warpz0r.admin.warpto: false
      warpz0r.bedhome: true
      warpz0r.compasshome: true
      warpz0r.compassreset: true
      warpz0r.compasswarp: true
      warpz0r.free: true
      warpz0r.free.bedhome: true
      warpz0r.free.home: true
      warpz0r.free.removewarp: true
      warpz0r.free.sethome: true
      warpz0r.free.setwarp: true
      warpz0r.free.warp: true
      warpz0r.home: true
      warpz0r.list: true
      warpz0r.remove: true
      warpz0r.set: true
      warpz0r.setcost: true
      warpz0r.sethome: true
      warpz0r.use: true
      warpz0r.use.compass: true
      warpz0r.use.home: true
      warpz0r.use.warp: true
      warpz0r.warp: true
      warpz0r.worldhome: true
      warpz0r.worldwarp: true
      wormhole.use.compass: true
      wormhole.use.dialer: true
      wormhole.use.sign: true
      bukkitinventorytools.sortinventory.use: true
      bukkitinventorytools.sortinventory.stack.tools: true
      bukkitinventorytools.sortinventory.stack.armor: true
      bukkitinventorytools.sortinventory.stack.weapons: true
      bukkitinventorytools.sortinventory.stack.food: true
      bukkitinventorytools.sortinventory.stack.vehicles: true
      bukkitinventorytools.sortinventory.stack.buckets: true
      bukkitinventorytools.digilock.create: true
      bukkitinventorytools.digilock.use: true
      bukkitinventorytools.bookshelf.create: true
      bukkitinventorytools.bookshelf.use: true
      bukkitinventorytools.book.create: true
      bukkitinventorytools.book.use: true
      bukkitinventorytools.backpack.use: true
      bukkitinventorytools.backpack.size9: true
      bukkitinventorytools.backpack.size18: true
      bukkitinventorytools.backpack.size27: true
      bukkitinventorytools.backpack.size36: true
      bukkitinventorytools.backpack.size45: true
      bukkitinventorytools.backpack.size54: true
      bukkitinventorytools.backpack.upgrade18: true
      bukkitinventorytools.backpack.upgrade27: true
      bukkitinventorytools.backpack.upgrade36: true
      bukkitinventorytools.backpack.upgrade45: true
      bukkitinventorytools.backpack.upgrade54: true
      bukkitinventorytools.backpack.clear: true
      bukkitinventorytools.backpack.workbench: true
      bukkitinventorytools.backpack.reload: true
      bukkitinventorytools.backpack.nodrop: true
      mcmmo.commands.ptp: false
      jobs.use: true
      skyblock.newisland: true
      skyblock.join: true
      nocheat.checks.moving: true
      citizens.trader.use._: true
      citizens.basic.use._: true
      citizens.guard.use._: true
      citizens.blacksmith.use._: true
      citizens.healer.use._: true
      citizens.wizard.use._: true
      citizens.quester.use.quests._: true
      citizens.quester.use._: true
      bankcraft.use: true
      adventour.user._: true
    worlds:
      world:
        essentials.sell: false
        nozombe.zombe.fly: true
        alphachest.chest: true
        alphachest.workbench: true
        tombstone.use: true
        tombstone.freechest: true
        tombstone.large: true
        tombstone.lwc: true
        tombstone.sign: true
        tombstone.freesign: true
        tombstone.cmd.tomblist: true
        tombstone.cmd.tombfind: true
        tombstone.cmd.tombreset: true
  Admin:
    permissions:
      bukkit.broadcast: true
      bukkit.broadcast.admin: true
      bukkit.command: true
      bukkit.command.give: true
      bukkit.command.help: true
      bukkit.command.kill: true
      bukkit.command.list: true
      bukkit.command.me: true
      bukkit.command.op: true
      bukkit.command.op.give: true
      bukkit.command.op.take: true
      bukkit.command.plugins: true
      bukkit.command.reload: true
      bukkit.command.save: true
      bukkit.command.save.disable: true
      bukkit.command.save.enable: true
      bukkit.command.save.perform: true
      bukkit.command.say: true
      bukkit.command.stop: true
      bukkit.command.teleport: true
      bukkit.command.tell: true
      bukkit.command.time: true
      bukkit.command.time.add: true
      bukkit.command.time.set: true
      bukkit.command.version: true
      bukkit.command.whitelist: true
      bukkit.command.whitelist.add: true
      bukkit.command.whitelist.disable: true
      bukkit.command.whitelist.enable: true
      bukkit.command.whitelist.list: true
      bukkit.command.whitelist.reload: true
      bukkit.command.whitelist.remove: true
      essentials.backup: false
      essentials.essentials: false
      essentials.setspawn: false
      essentials.reloadall: false
      essentials.plugin: false
      essentials._: true
      groupmanager.mantogglevalidate: true
      groupmanager.mansave: true
      groupmanager.mangcheckp: true
      groupmanager.manglistp: true
      groupmanager.manucheckp: true
      groupmanager.manulistp: true
      warpz0r.warp: true
      warpz0r.set: true
      warpz0r.setcost: true
      warpz0r.remove: true
      warpz0r.list: true
      warpz0r.worldwarp: true
      warpz0r.use.warp: true
      warpz0r.sethome: true
      warpz0r.home: true
      warpz0r.worldhome: true
      warpz0r.bedhome: true
      warpz0r.use.home: true
      warpz0r.compasshome: true
      warpz0r.compassreset: true
      warpz0r.compasswarp: true
      warpz0r.use.compass: true
      warpz0r.use: true
      warpz0r.admin.warpto: true
      warpz0r.admin.sethome: true
      warpz0r.admin.home: true
      warpz0r.admin.clearhome: true
      warpz0r.admin: true
      warpz0r.free.warp: true
      warpz0r.free.setwarp: true
      warpz0r.free.removewarp: true
      warpz0r.free.sethome: true
      warpz0r.free.home: true
      warpz0r.free.bedhome: true
      warpz0r.free: true
      wormhole.use.sign: true
      wormhole.use.dialer: true
      wormhole.use.compass: true
      scrollingmenusign.denied: false
      permissions.build: true
  unLoggedinGroup: {}
messages:
  build: '&cYou do not have permission to build here.'

**Comment by psychofad** [comment]
It is indented properly but copy and pasting it here it loses the formatting...weird

But at least you get the point!

**Comment by bloodriot** [comment]
Did you happen to use the -a or -g flags to define the guard's targets?

**Comment by psychofad** [comment]
Nope.  I used the -m flag and defined each mob seperately.  I also tried using the  -p flag to define a player name.  Still he just stands there.  If you attack him he will aggro you until you either die, kill him, or log off though.

**Comment by bloodriot** [comment]
Alright I'll try to replicate on my server when I get home tonight.
On Apr 10, 2012 11:09 AM, "psychofad" <
reply@reply.github.com>
wrote:

> Nope.  I used the -m flag and defined each mob seperately.  I also tried
> using the      -p flag to define a player name.  Still he just stands
> there.  If you attack him he will aggro you until you either die, kill him,
> or log off though.
>

**Comment by psychofad** [comment]
Wow!

Vault just updated and now my guard is working great!

Apparently there was an issue with vault!  I'm closing this issue as it is fixed....Thank You for trying to help!!
