### ISSUE TITLE
NPCs Despawn After a While

### ISSUE THREAD

**Issue by fuzzwolf** [CitizensDev/Citizens#955]
I've noticed that NPCs tend to disappear if nobody is near them, with the exception of our spawn. I am currently running the 1.2 development (not Citizens 2) version with Minecraft 1.2.4. This could perhaps be a CraftBukkit++ issue. I imagine the despawning accommodates chunk unloading. Any ideas? Possible fix in the next official release? Thanks.

**Comment by exestino** [comment]
I found that NPC disappear because of MineBackup plugin is saving world. When i remove that plugin the NPC stayed in place. I placed back MineBackup 5.9.3 wich is the newest build but the result is the same. When saving world NPC dissapear.
I using Craftbukkit 1.2.5 R1.0

**Comment by fuzzwolf** [comment]
It worked! Thank you so much. :D
