### ISSUE TITLE
Guards stop attacking mobs

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#96]
This doesn't display any errors in the console, but when guards attack just one mob in their blacklist or the mob leaves their radius, they just walk back to their original coordinates and stop reacting completely unless I kill them. Then the same thing repeats.

**Comment by Coffeehedake** [comment]
I can second this. Sometimes they do not even _start_ to attack. (using build 145)

**Comment by fullwall** [comment]
_might_ be fixed in newest builds

**Comment by defaultsucks** [comment]
This is fixed in the newest builds, however it gave some new issues. I can't explain them in text so I'll just make a short video showing exactly what happens and post a new issue.
