### ISSUE TITLE
Plugin Localization

### ISSUE THREAD

**Issue by riffbyte** [CitizensDev/Citizens#975]
Hi!
I am using this plugin on russian server and all messages and NPC names are in russian. Mesages are OK, but whenever I restart the server, all nicknames are replaced with ?????. I tried encoding npc-profiles.yml in UTF-8 and UTF-8 (without BOM) but result remained the samw.
What can I do to translate the plugin correctly?

**Comment by notcam45** [comment]
Its as simple as using /npc set "Russian Message Here"

**Comment by riffbyte** [comment]
I wish it was :D

**Comment by riffbyte** [comment]
OK, the problem was in code transforming.
Now all messages are OK, but I encountered another problem (see UPD).

**Comment by fullwall** [comment]
I don't know if minecraft supports usernames with utf characters in them.

**Comment by riffbyte** [comment]
These are displaynames, so it is OK.
Problem is actually solved, I don't quite know why, but it it :3
