### ISSUE TITLE
Questers - Delivery

### ISSUE THREAD

**Issue by RincewindSCC** [CitizensDev/Citizens#98]
After assigning a delivery quest to a NPC and accepting the quest, no matter what I seem to do doesn't advance the quest. For example if the objective is to delivery 4 cobblestone to a npc even if I collect the cobble and have it in my hand the npc doesn't seem to take the items. 

Running "/quest status" shows "Delivering 0 cobblestone to ENDQUEST".

Running #145 and the quest is as follows:

deliverytest:
    texts:
        description: A delivery quest
        completion: You delivered the items
        acceptance: <g>Challenge <y>accepted<g>.
    repeatable: false
    objectives:
        '0':
            '0':
                type: delivery
                npcdestination: 1
                materialid: 4
                amount: 4
                message: Delivered. Now come back here!
    rewards:
        '0':
            type: item
            id: 4
            amount: 64
            take: false

**Comment by fullwall** [comment]
Should work now.
