### ISSUE TITLE
Citizen2 and Alchemist bugs.

### ISSUE THREAD

**Issue by Rusher-ranger** [CitizensDev/Citizens#981]
Hi ! i'm french, sorry for my bad english.

Bug list :
Citizens2 Build 131 and Alchemist 1.0 :
- Pathfinding not reloaded.
- Npc mob after reload is invisible.
- Alchemiste not reloaded.
- When change default repices in config is not loaded.

Bukit version : 1.2.5 R1.0

**Comment by aPunch** [comment]
Report this as a Citizens2 issue here: http://issues.citizensnpcs.net

In fact, I believe this issue has already been reported there. Alchemist bugs can be reported here: http://github.com/aPunch/Alchemist/issues
