### ISSUE TITLE
Could not load 'plugins/blacksmith-1.0-SNAPSHOT.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#988]
I just installed Citizens 2 #140 (21.04.2012 02:12:51)
And get this error (http://pastebin.com/ef370cCs)
when I tried to install Blacksmith.
## Please Help me, raphael811

Sorry for bad english

**Comment by aPunch** [comment]
Blacksmiths require Vault and an economy plugin that supports Vault (iConomy, etc.)
