### ISSUE TITLE
Questers multiple objectives

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#99]
I've tested a quest called traderhelp. Here's the quest:

traderhelp:
    texts:
        description: I was attacked by a horde, take them down?
        completion: <g>You are so kind! Thank you.
        acceptance: <g>Challenge <y>accepted<g>!
    repeatable: true
    objectives:
        '0':
            '0':
                type: hunt
                uses: 10
                string: zombie, skeleton
                materialid: 1
                amount: 3
                message: You sure took down those monsters
    objectives:
        '0':
            '1':
                type: collect
                materialid: 3
                amount: 3
                message: A voice echoes... "I want that dirt 
    rewards:
        '0':
            type: item
            id: 1
            amount: 64
            take: false

Multiple objectives do not work. It seems to only display one objective that's on the very bottom. I've tried removing the second objectives: , tried messing around with the numbers but it didn't do anything.

Also it seems that the hunt type amount doesn't work. In there it says amount: 3 but I can just kill one mob and it works.

**Comment by RincewindSCC** [comment]
Try using the below, works for me:

objectives:
'0':
'0':
type: hunt
uses: 10
string: zombie, skeleton
materialid: 1
amount: 3
message: You sure took down those monsters
'1':
type: collect
materialid: 3
amount: 3
message: A voice echoes... "I want that dirt

**Comment by defaultsucks** [comment]
That just stacks all the objectives together. I've just tried it. If it's the other way around it should have steps. You do something, you run back to the npc or maybe it just tells you what to do next.

**Comment by ggirelli** [comment]
If I understand correctly what you want to do, in other words making the player collect dirt only AFTER having killed N monsters... as said [here](http://wiki.citizensnpcs.net/1.x/Quests.yml) you have to do so:

`````` traderhelp:
    texts:
        description: I was attacked by a horde, take them down?
        completion: You are so kind! Thank you.
        acceptance: Challenge accepted!
    repeatable: true
    objectives:
        '0':
            '0':
                type: hunt
                uses: 10
                string: zombie, skeleton
                materialid: 1
                amount: 3
                message: You sure took down those monsters
        '1':
            '0':
                type: collect
                materialid: 3
                amount: 3
                message: A voice echoes... "I want that dirt
    rewards:
        '0':
            type: item
            id: 1
            amount: 64
            take: false```
``````
