### ISSUE TITLE
Blacksmith won't install.

### ISSUE THREAD

**Issue by cjbigred** [CitizensDev/Citizens#994]
Using citizens 1.2 got blacksmith installed in /plugins and also (i think ) i have the right version of vault installed, kinda a pain to find vault for some reason. and when i do /blacksmith help i get  " The command was not recognized,  See /blacksmith help for a list of commands"    any help would be gracious, maybe a ling to vault incase mine is wrong. or something. it just wont work =( also have iconomy. when i do "/toggle blacksmith" i get invalid npc type.

**Comment by aPunch** [comment]
You don't install Blacksmith into the plugins folder for Citizens 1.x. You must install the NPC types into the plugins/Citizens/types folder.
