### ISSUE TITLE
ALL NPC are GONE!

### ISSUE THREAD

**Issue by fredghostkyle** [CitizensDev/Citizens#998]
ok, i was using bukkit 1.2.5 R-1
Vault is uptodate, i hade like 24 NPCs, i want them BACK!
i did NOT do /npc remove. and if i did i did not to "all".

Plez help. i have NO CLUE why!

thanks,
fredghostkyle!

PS: i have VAULT!!!!!!!!!!!!!!!!!!!!!!! (100% up to date)

**Comment by Jonilo5** [comment]
I know, me too, i did 3 NPCs and when I reload my server they are all gone! :(
hope we find an answer :)

**Comment by Jonilo5** [comment]
same problem

**Comment by CR33PAH** [comment]
This is because you do not have the plugin Vault installed. Download it and install it. then restart your server. They will be there.

Link for Vault: http://dev.bukkit.org/server-mods/vault/

Hope this helps ^_^

**Comment by fredghostkyle** [comment]
ummmm... 1/2 of my plugins use VAULT! i think it is on and working.!!!!!!!! i think it is something else. NOT VAULT i can know when a plugin in not working (Vault is NOT one of them).

**Comment by fredghostkyle** [comment]
WTF no one has answered my problem WTF WTF!!!!!!!!!

WTF!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by CR33PAH** [comment]
That does not mean you have to write "WTF" four times and put 50+ !s Have you tried reinstalling Citizens 1.2? 

Sent from Yahoo! Mail on Android

**Comment by Fureniku** [comment]
Well, I was going to tell you how to do this but from the way you've acted I don't think I will now.

OK, I'm not that mean. Never, ever /reload a server - its a really bad command. ALWAYS do this. If you do from console just don't put the /:

/save-all
/citizens save
/stop

/reload only works when you have no/very few plugins installed. Every plugin has to support the command or it will bug, and most devs know reloading can cause file corruption and therefore don't support it anyway. Citizens for example doesn't, Spout is another example (they warn you if you try though)

If you want to reload a plugin you can usually do /[pluginname] reload - if they have a command for it. For example /citizens reload for this, and /quester reload specifically to reload quests.

**Comment by fredghostkyle** [comment]
ok, thanks...... i never do /reload. it lags my server and it makes it so that i can't use console commands (PEX) so ya, but it is fine, i will reset the config files anyway, thanks SO MUCH!
